// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * GatewayDetails is the detail payload for a Gateway.
 */
export interface GatewayDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "gatewayClassRef": types$0.ObjectRef;
    "addresses"?: string[] | null;
    "listeners"?: types$0.GatewayListenerDetails[] | null;
    "conditions"?: types$0.ConditionState[] | null;
    "summary": types$0.ConditionsSummary;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
}
