// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * NodeCondition represents a node condition.
 */
export interface NodeCondition {
    "kind": string;
    "status": string;
    "reason"?: string;
    "message"?: string;
}

/**
 * NodeDetails represents comprehensive node information for the object panel.
 */
export interface NodeDetails {
    "name": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;
    "unschedulable": boolean;
    "roles": string;
    "internalIP": string;
    "externalIP"?: string;
    "hostname": string;
    "architecture": string;
    "os": string;
    "osImage": string;
    "kernelVersion": string;
    "containerRuntime": string;
    "kubeletVersion": string;
    "cpuCapacity": string;
    "cpuAllocatable": string;
    "memoryCapacity": string;
    "memoryAllocatable": string;
    "podsCapacity": string;
    "podsAllocatable": string;
    "storageCapacity"?: string;
    "podsCount": number;
    "restarts": number;
    "cpuRequests": string;
    "cpuLimits": string;
    "memRequests": string;
    "memLimits": string;
    "cpuUsage"?: string;
    "memoryUsage"?: string;
    "kind": string;
    "cpu": string;
    "memory": string;
    "pods": string;
    "conditions": NodeCondition[] | null;
    "taints"?: NodeTaint[] | null;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
    "podsList"?: types$0.PodSimpleInfo[] | null;
}

/**
 * NodeTaint represents a node taint.
 */
export interface NodeTaint {
    "key": string;
    "value"?: string;
    "effect": string;
}
