// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../../k8s.io/apimachinery/pkg/apis/meta/v1/models.js";

/**
 * CRDCondition represents a CRD status condition.
 */
export class CRDCondition {
    "kind": string;
    "status": string;
    "reason"?: string;
    "message"?: string;
    "lastTransitionTime"?: v1$0.Time;

    /** Creates a new CRDCondition instance. */
    constructor($$source: Partial<CRDCondition> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CRDCondition instance from a string or object.
     */
    static createFrom($$source: any = {}): CRDCondition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CRDCondition($$parsedSource as Partial<CRDCondition>);
    }
}

/**
 * CRDNames represents the names specification of a CRD.
 */
export class CRDNames {
    "plural": string;
    "singular": string;
    "kind": string;
    "listKind"?: string;
    "shortNames"?: string[];
    "categories"?: string[];

    /** Creates a new CRDNames instance. */
    constructor($$source: Partial<CRDNames> = {}) {
        if (!("plural" in $$source)) {
            this["plural"] = "";
        }
        if (!("singular" in $$source)) {
            this["singular"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CRDNames instance from a string or object.
     */
    static createFrom($$source: any = {}): CRDNames {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shortNames" in $$parsedSource) {
            $$parsedSource["shortNames"] = $$createField4_0($$parsedSource["shortNames"]);
        }
        if ("categories" in $$parsedSource) {
            $$parsedSource["categories"] = $$createField5_0($$parsedSource["categories"]);
        }
        return new CRDNames($$parsedSource as Partial<CRDNames>);
    }
}

/**
 * CRDVersion represents a version of a CRD.
 */
export class CRDVersion {
    "name": string;
    "served": boolean;
    "storage": boolean;
    "deprecated"?: boolean;
    "schema"?: { [_ in string]?: any };

    /** Creates a new CRDVersion instance. */
    constructor($$source: Partial<CRDVersion> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("served" in $$source)) {
            this["served"] = false;
        }
        if (!("storage" in $$source)) {
            this["storage"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CRDVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): CRDVersion {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("schema" in $$parsedSource) {
            $$parsedSource["schema"] = $$createField4_0($$parsedSource["schema"]);
        }
        return new CRDVersion($$parsedSource as Partial<CRDVersion>);
    }
}

/**
 * CustomResourceDefinitionDetails represents comprehensive CRD information.
 */
export class CustomResourceDefinitionDetails {
    "kind": string;
    "name": string;
    "group": string;
    "scope": string;
    "details": string;
    "versions": CRDVersion[];
    "names": CRDNames;
    "conversionStrategy"?: string;
    "conditions"?: CRDCondition[];
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };

    /** Creates a new CustomResourceDefinitionDetails instance. */
    constructor($$source: Partial<CustomResourceDefinitionDetails> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }
        if (!("names" in $$source)) {
            this["names"] = (new CRDNames());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomResourceDefinitionDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomResourceDefinitionDetails {
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField8_0 = $$createType6;
        const $$createField9_0 = $$createType7;
        const $$createField10_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField5_0($$parsedSource["versions"]);
        }
        if ("names" in $$parsedSource) {
            $$parsedSource["names"] = $$createField6_0($$parsedSource["names"]);
        }
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField8_0($$parsedSource["conditions"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField9_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField10_0($$parsedSource["annotations"]);
        }
        return new CustomResourceDefinitionDetails($$parsedSource as Partial<CustomResourceDefinitionDetails>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = CRDVersion.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = CRDNames.createFrom;
const $$createType5 = CRDCondition.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
