// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../../k8s.io/apimachinery/pkg/apis/meta/v1/models.js";

/**
 * CRDCondition represents a CRD status condition.
 */
export interface CRDCondition {
    "kind": string;
    "status": string;
    "reason"?: string;
    "message"?: string;
    "lastTransitionTime"?: v1$0.Time;
}

/**
 * CRDNames represents the names specification of a CRD.
 */
export interface CRDNames {
    "plural": string;
    "singular": string;
    "kind": string;
    "listKind"?: string;
    "shortNames"?: string[] | null;
    "categories"?: string[] | null;
}

/**
 * CRDVersion represents a version of a CRD.
 */
export interface CRDVersion {
    "name": string;
    "served": boolean;
    "storage": boolean;
    "deprecated"?: boolean;
    "schema"?: { [_ in string]?: any } | null;
}

/**
 * CustomResourceDefinitionDetails represents comprehensive CRD information.
 */
export interface CustomResourceDefinitionDetails {
    "kind": string;
    "name": string;
    "group": string;
    "scope": string;
    "details": string;
    "versions": CRDVersion[] | null;
    "names": CRDNames;
    "conversionStrategy"?: string;
    "conditions"?: CRDCondition[] | null;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
}
