// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App provides the backend façade exposed to Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capabilities$0 from "./capabilities/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as objectcatalog$0 from "./objectcatalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as snapshot$0 from "./refresh/snapshot/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resourcemodel$0 from "./resourcemodel/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFavorite generates an ID, assigns Order, appends the favorite, and persists.
 */
export function AddFavorite(fav: $models.Favorite): $CancellablePromise<$models.Favorite> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.AddFavorite", fav);
}

/**
 * ApplyClusterWorkspace serializes selection mutation before foreground
 * activation and returns the resulting authoritative workspace snapshot.
 */
export function ApplyClusterWorkspace(command: $models.ClusterWorkspaceCommand): $CancellablePromise<$models.ClusterWorkspaceResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ApplyClusterWorkspace", command);
}

/**
 * ApplyObjectYaml performs a kubectl-edit-style patch using the original editor
 * baseline plus the user's edited YAML.
 */
export function ApplyObjectYaml(clusterID: string, req: $models.ObjectYAMLMutationRequest): $CancellablePromise<$models.ObjectYAMLMutationResponse | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ApplyObjectYaml", clusterID, req);
}

/**
 * ApplyTheme loads a saved theme by ID and copies its palette values into the
 * active settings fields, then persists. The frontend re-reads settings to
 * pick up the changes.
 */
export function ApplyTheme(id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ApplyTheme", id);
}

function BindingModelAnchor(): $CancellablePromise<$models.BindingModelAnchor> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.BindingModelAnchor");
}

export function CancelDrainNodeJob(clusterID: string, jobID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.CancelDrainNodeJob", clusterID, jobID);
}

/**
 * CheckForUpdates performs only release discovery. Download and restart remain
 * separate user-consent commands.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.CheckForUpdates");
}

/**
 * CheckObjectYamlOwnership reports which fields the edited YAML would take
 * ownership of from other field managers. It is advisory: the caller decides
 * whether to proceed, and the save itself never goes through server-side
 * apply (which would make this editor co-owner of the entire document).
 */
export function CheckObjectYamlOwnership(clusterID: string, req: $models.ObjectYAMLMutationRequest): $CancellablePromise<$models.ObjectYAMLOwnershipCheckResponse | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.CheckObjectYamlOwnership", clusterID, req);
}

export function ClearAppLogs(): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ClearAppLogs");
}

/**
 * ClearAppState deletes persisted state files and resets in-memory caches for a clean restart.
 */
export function ClearAppState(): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ClearAppState");
}

/**
 * ClearGridTablePersistence removes all GridTable persistence entries for v1.
 */
export function ClearGridTablePersistence(): $CancellablePromise<number> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ClearGridTablePersistence");
}

/**
 * CloseShellSession terminates an active shell session.
 */
export function CloseShellSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.CloseShellSession", sessionID);
}

/**
 * DeleteFavorite removes a favorite by ID and re-indexes Order. Returns an error if not found.
 */
export function DeleteFavorite(id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.DeleteFavorite", id);
}

/**
 * DeleteGridTablePersistence removes a single GridTable persistence entry.
 */
export function DeleteGridTablePersistence(key: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.DeleteGridTablePersistence", key);
}

/**
 * DeleteGridTablePersistenceEntries removes multiple GridTable persistence entries at once.
 */
export function DeleteGridTablePersistenceEntries(keys: string[] | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.DeleteGridTablePersistenceEntries", keys);
}

/**
 * DeleteTheme removes a theme from the library by ID.
 */
export function DeleteTheme(id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.DeleteTheme", id);
}

export function DiscoverNodeLogs(clusterID: string, nodeName: string): $CancellablePromise<$models.NodeLogDiscoveryResponse> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.DiscoverNodeLogs", clusterID, nodeName);
}

/**
 * DownloadApplicationUpdate downloads, verifies, and prepares the exact
 * release version the user approved.
 */
export function DownloadApplicationUpdate(version: string): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.DownloadApplicationUpdate", version);
}

export function ExportFavorites(): $CancellablePromise<$models.DataManagementResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ExportFavorites");
}

export function ExportSettings(): $CancellablePromise<$models.DataManagementResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ExportSettings");
}

export function FetchContainerLogs(clusterID: string, req: $models.ContainerLogsFetchRequest): $CancellablePromise<$models.ContainerLogsFetchResponse> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.FetchContainerLogs", clusterID, req);
}

export function FetchNodeLogs(clusterID: string, nodeName: string, req: $models.NodeLogFetchRequest): $CancellablePromise<$models.NodeLogFetchResponse> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.FetchNodeLogs", clusterID, nodeName, req);
}

/**
 * FindCatalogObjectByUID resolves a single catalog object in the requested
 * cluster by resource UID.
 */
export function FindCatalogObjectByUID(clusterID: string, uid: string): $CancellablePromise<objectcatalog$0.Summary | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.FindCatalogObjectByUID", clusterID, uid);
}

/**
 * FindCatalogObjectMatch resolves a single catalog object in the requested
 * cluster by canonical identity.
 */
export function FindCatalogObjectMatch(clusterID: string, $namespace: string, group: string, version: string, kind: string, name: string): $CancellablePromise<objectcatalog$0.Summary | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.FindCatalogObjectMatch", clusterID, $namespace, group, version, kind, name);
}

/**
 * GetAppInfo returns the application version information
 */
export function GetAppInfo(): $CancellablePromise<$models.AppInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetAppInfo");
}

export function GetAppLogs(): $CancellablePromise<$models.LogEntry[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetAppLogs");
}

export function GetAppLogsSince(sequence: number): $CancellablePromise<$models.LogEntry[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetAppLogsSince", sequence);
}

export function GetAppSettings(): $CancellablePromise<$models.AppSettings | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetAppSettings");
}

export function GetAppSettingsSchema(): $CancellablePromise<$models.AppSettingsSchema | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetAppSettingsSchema");
}

/**
 * GetClusterAllowedNamespaces returns the persisted namespace scope for the
 * cluster in the order the user saved it. Empty means no scope.
 */
export function GetClusterAllowedNamespaces(clusterID: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetClusterAllowedNamespaces", clusterID);
}

/**
 * GetClusterTabOrder returns the persisted cluster tab order.
 */
export function GetClusterTabOrder(): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetClusterTabOrder");
}

/**
 * GetClusterWorkspaceStateForWindow projects process-wide cluster state with
 * the visible cluster belonging to the requesting peer window.
 */
export function GetClusterWorkspaceStateForWindow(windowID: string): $CancellablePromise<$models.ClusterWorkspaceState> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetClusterWorkspaceStateForWindow", windowID);
}

export function GetContainerLogsScopeContainers(clusterID: string, scope: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetContainerLogsScopeContainers", clusterID, scope);
}

/**
 * GetFavorites returns all saved favorites.
 */
export function GetFavorites(): $CancellablePromise<$models.Favorite[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetFavorites");
}

/**
 * GetGridTablePersistence returns all persisted GridTable entries for v1.
 */
export function GetGridTablePersistence(): $CancellablePromise<{ [_ in string]?: json$0.RawMessage } | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetGridTablePersistence");
}

/**
 * GetKubeconfigSearchPaths returns the configured kubeconfig search paths.
 */
export function GetKubeconfigSearchPaths(): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetKubeconfigSearchPaths");
}

/**
 * GetKubeconfigs returns the available kubeconfigs and the current discovery state.
 */
export function GetKubeconfigs(): $CancellablePromise<$models.KubeconfigDiscoveryResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetKubeconfigs");
}

/**
 * GetKubernetesAPIClientDiagnostics returns per-cluster Kubernetes API client usage.
 */
export function GetKubernetesAPIClientDiagnostics(): $CancellablePromise<$models.KubernetesAPIClientDiagnostics[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetKubernetesAPIClientDiagnostics");
}

/**
 * GetObjectYAMLByGVK fetches a Kubernetes object by its fully-qualified
 * apiVersion + kind and returns its YAML representation. apiVersion must
 * be in the standard Kubernetes "group/version" form (or just "version"
 * for core resources like "v1").
 * 
 * Unlike GetObjectYAML, this function resolves the GVR strictly from the
 * supplied group/version/kind and does not fall back to first-match-wins
 * on bare kind. That's the whole point of the fix — callers that know
 * which CRD they want can get exactly that one, even when another CRD
 * registers the same Kind under a different group.
 */
export function GetObjectYAMLByGVK(clusterID: string, apiVersion: string, kind: string, $namespace: string, name: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetObjectYAMLByGVK", clusterID, apiVersion, kind, $namespace, name);
}

export function GetPodContainers(clusterID: string, $namespace: string, podName: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetPodContainers", clusterID, $namespace, podName);
}

/**
 * GetRevisionHistory returns the rollout revision history for a named workload.
 * Supports Deployment, StatefulSet, and DaemonSet. Other kinds return an error.
 * Results are sorted descending by revision number (newest first).
 * 
 * Multi-cluster safety: all Kubernetes requests are scoped to the cluster
 * identified by clusterID, preventing cross-cluster data leakage.
 */
export function GetRevisionHistory(clusterID: string, $namespace: string, group: string, version: string, workloadKind: string, name: string): $CancellablePromise<$models.RevisionEntry[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetRevisionHistory", clusterID, $namespace, group, version, workloadKind, name);
}

/**
 * GetSelectionDiagnostics returns rolling selection mutation timing and outcome stats.
 */
export function GetSelectionDiagnostics(): $CancellablePromise<$models.SelectionDiagnostics | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetSelectionDiagnostics");
}

/**
 * GetShellSessionBacklog returns buffered shell output for replaying on reattach.
 */
export function GetShellSessionBacklog(sessionID: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetShellSessionBacklog", sessionID);
}

/**
 * GetTargetPorts returns the TCP ports a target can be forwarded on.
 */
export function GetTargetPorts(clusterID: string, $namespace: string, targetKind: string, targetGroup: string, targetVersion: string, targetName: string): $CancellablePromise<$models.ContainerPortInfo[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetTargetPorts", clusterID, $namespace, targetKind, targetGroup, targetVersion, targetName);
}

/**
 * GetThemes returns the saved theme library.
 */
export function GetThemes(): $CancellablePromise<$models.Theme[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetThemes");
}

/**
 * GetZoomLevel returns the persisted zoom level (50-200), defaulting to 100.
 */
export function GetZoomLevel(): $CancellablePromise<number> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.GetZoomLevel");
}

/**
 * HydrateCatalogCustomRows fetches rich custom-resource row facts for the
 * current catalog page. It intentionally works only on caller-provided page
 * rows so production Custom tables keep catalog-backed paging without starting
 * the legacy full CRD fanout domains.
 */
export function HydrateCatalogCustomRows(clusterID: string, rows: snapshot$0.ResourceQueryRow[] | null): $CancellablePromise<snapshot$0.CustomResourceSummary[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.HydrateCatalogCustomRows", clusterID, rows);
}

export function IgnoreClusterAttentionFindingType(clusterID: string, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.IgnoreClusterAttentionFindingType", clusterID, findingType);
}

export function IgnoreClusterAttentionObjectFinding(clusterID: string, ref: resourcemodel$0.ResourceRef, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.IgnoreClusterAttentionObjectFinding", clusterID, ref, findingType);
}

export function IgnoreGlobalAttentionFindingType(clusterID: string, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.IgnoreGlobalAttentionFindingType", clusterID, findingType);
}

export function ImportFavorites(): $CancellablePromise<$models.DataManagementResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ImportFavorites");
}

export function ImportSettings(): $CancellablePromise<$models.DataManagementResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ImportSettings");
}

/**
 * IsWorkloadHPAManaged checks whether any HorizontalPodAutoscaler in the given
 * namespace targets the specified workload GVK + name. Used by the object panel
 * to switch HPA-managed workloads from arbitrary scaling to fixed zero/resume
 * actions.
 */
export function IsWorkloadHPAManaged(clusterID: string, $namespace: string, group: string, version: string, kind: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.IsWorkloadHPAManaged", clusterID, $namespace, group, version, kind, name);
}

/**
 * ListPortForwards returns all active port forwarding sessions.
 */
export function ListPortForwards(): $CancellablePromise<$models.PortForwardSession[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ListPortForwards");
}

export function ListRuntimeOperations(): $CancellablePromise<$models.RuntimeOperation[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ListRuntimeOperations");
}

/**
 * ListShellSessions returns all active shell exec sessions.
 */
export function ListShellSessions(): $CancellablePromise<$models.ShellSessionInfo[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ListShellSessions");
}

/**
 * LogAppLogsFromFrontend appends a log entry originating from the frontend to the application log store.
 */
export function LogAppLogsFromFrontend(level: string, message: string, source: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.LogAppLogsFromFrontend", level, message, source);
}

/**
 * LogAppLogsFromFrontendWithCluster appends a frontend log entry with structured cluster metadata.
 */
export function LogAppLogsFromFrontendWithCluster(level: string, message: string, source: string, clusterID: string, clusterName: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.LogAppLogsFromFrontendWithCluster", level, message, source, clusterID, clusterName);
}

/**
 * MatchThemeForCluster returns the first saved theme whose ClusterPattern
 * matches the given context name using app glob rules: * matches any sequence,
 * ? matches any single character, and character classes such as [a-z] are
 * supported. An empty ClusterPattern is treated as "*" and matches every
 * context name. Returns nil if no theme matches.
 */
export function MatchThemeForCluster(contextName: string): $CancellablePromise<$models.Theme | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.MatchThemeForCluster", contextName);
}

/**
 * MergeObjectYamlWithLatest reloads the live object from the target cluster and
 * applies the user's local edits onto it using the same patch family kubectl
 * edit uses: strategic merge for registered built-ins, JSON merge patch
 * fallback otherwise.
 */
export function MergeObjectYamlWithLatest(clusterID: string, req: $models.ObjectYAMLReloadMergeRequest): $CancellablePromise<$models.ObjectYAMLReloadMergeResponse | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.MergeObjectYamlWithLatest", clusterID, req);
}

/**
 * OpenKubeconfigSearchPathDialog opens a directory picker for kubeconfig search paths.
 */
export function OpenKubeconfigSearchPathDialog(): $CancellablePromise<string> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.OpenKubeconfigSearchPathDialog");
}

/**
 * QueryPermissions evaluates a batch of permission queries using SSRR caching
 * with SSAR fallback. All errors are per-item; the top-level error is always nil.
 */
export function QueryPermissions(queries: capabilities$0.PermissionQuery[] | null): $CancellablePromise<capabilities$0.QueryPermissionsResponse | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.QueryPermissions", queries);
}

/**
 * RemoveApplicationUpdateSkip clears the durable version skip and offers the
 * release again when it remains available.
 */
export function RemoveApplicationUpdateSkip(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.RemoveApplicationUpdateSkip");
}

/**
 * ReorderThemes sets the theme ordering. The ids slice must contain exactly the
 * same IDs as the current theme list (first-match priority depends on order).
 */
export function ReorderThemes(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ReorderThemes", ids);
}

/**
 * ResizeShellSession notifies Kubernetes about the new TTY size.
 */
export function ResizeShellSession(sessionID: string, columns: number, rows: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ResizeShellSession", sessionID, columns, rows);
}

/**
 * RestartAndApplyApplicationUpdate starts the prepared updater helper only
 * after explicit user consent.
 */
export function RestartAndApplyApplicationUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.RestartAndApplyApplicationUpdate");
}

export function RestoreClusterAttentionFindingType(clusterID: string, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.RestoreClusterAttentionFindingType", clusterID, findingType);
}

export function RestoreClusterAttentionObjectFinding(clusterID: string, ref: resourcemodel$0.ResourceRef, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.RestoreClusterAttentionObjectFinding", clusterID, ref, findingType);
}

export function RestoreGlobalAttentionFindingType(clusterID: string, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.RestoreGlobalAttentionFindingType", clusterID, findingType);
}

/**
 * RetryClusterAuth triggers a manual authentication recovery attempt for a specific cluster.
 * Called when user clicks "Retry" for a specific cluster after re-authenticating externally.
 */
export function RetryClusterAuth(clusterID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.RetryClusterAuth", clusterID);
}

/**
 * RunObjectAction is the single Wails mutation contract for Kubernetes object
 * actions. The target always carries clusterId + full GVK + name, and namespace
 * when the target is namespaced.
 */
export function RunObjectAction(req: $models.ObjectActionRequest): $CancellablePromise<$models.ObjectActionResponse> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.RunObjectAction", req);
}

/**
 * SaveCsvFile writes a frontend-built CSV string to a user-selected file. The content
 * is produced client-side from the table's displayed columns, so the exported CSV
 * matches the on-screen table exactly; this keeps only the file IO (and the
 * potentially large byte payload) on the Go side. Returns the chosen path and size.
 */
export function SaveCsvFile(defaultFilename: string, content: string): $CancellablePromise<$models.CatalogQueryCSVExport> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SaveCsvFile", defaultFilename, content);
}

/**
 * SaveTheme creates or updates a theme in the library. If a theme with the
 * same ID exists it is updated in place; otherwise the theme is appended.
 */
export function SaveTheme(theme: $models.Theme): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SaveTheme", theme);
}

/**
 * SendShellInput writes stdin data to an active exec session.
 */
export function SendShellInput(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SendShellInput", sessionID, data);
}

export function SetAppLogsPanelVisible(visible: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SetAppLogsPanelVisible", visible);
}

/**
 * SetClusterAllowedNamespaces validates, normalizes, and persists the
 * namespace scope for one cluster, then requests a rebuild of that cluster's
 * refresh subsystem when the scope's namespace SET changed — reordering
 * persists but does not rebuild. It returns the normalized list. An
 * empty/nil list clears the scope. The whole batch is rejected on the first
 * invalid name: nothing is persisted and no rebuild is requested.
 */
export function SetClusterAllowedNamespaces(clusterID: string, namespaces: string[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SetClusterAllowedNamespaces", clusterID, namespaces);
}

/**
 * SetClusterTabOrder stores the persisted cluster tab order.
 */
export function SetClusterTabOrder(order: string[] | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SetClusterTabOrder", order);
}

/**
 * SetFavoriteOrder reorders favorites according to the given ID list.
 * Any favorites not in the list are appended in their existing relative order.
 */
export function SetFavoriteOrder(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SetFavoriteOrder", ids);
}

/**
 * SetGridTablePersistence stores a GridTable persistence payload by key.
 */
export function SetGridTablePersistence(key: string, payload: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SetGridTablePersistence", key, payload);
}

/**
 * SetKubeconfigSearchPaths persists the search paths and refreshes kubeconfig discovery.
 */
export function SetKubeconfigSearchPaths(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SetKubeconfigSearchPaths", paths);
}

export function SetSidebarVisible(visible: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SetSidebarVisible", visible);
}

/**
 * SetZoomLevel persists the zoom level (clamped to 50-200).
 */
export function SetZoomLevel(level: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SetZoomLevel", level);
}

/**
 * SkipApplicationUpdate durably suppresses the exact offered version before
 * hiding it from the current process.
 */
export function SkipApplicationUpdate(version: string): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.SkipApplicationUpdate", version);
}

/**
 * StartShellSession launches a kubectl exec session and begins streaming data back to the frontend.
 */
export function StartShellSession(clusterID: string, req: $models.ShellSessionRequest): $CancellablePromise<$models.ShellSession | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.StartShellSession", clusterID, req);
}

/**
 * StopPortForward terminates a specific port forwarding session.
 */
export function StopPortForward(sessionID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.StopPortForward", sessionID);
}

export function UpdateAppPreferences(request: $models.UpdateAppPreferencesRequest): $CancellablePromise<$models.UpdateAppPreferencesResponse | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.UpdateAppPreferences", request);
}

/**
 * UpdateFavorite replaces a favorite by ID, preserving its Order. Returns an error if not found.
 */
export function UpdateFavorite(fav: $models.Favorite): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.UpdateFavorite", fav);
}

/**
 * ValidateThemeClusterPattern checks whether a theme cluster pattern can be
 * parsed by the app glob matcher without mutating saved settings.
 */
export function ValidateThemeClusterPattern(pattern: string): $CancellablePromise<$models.ThemeClusterPatternValidationResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.App.ValidateThemeClusterPattern", pattern);
}

void BindingModelAnchor;
