// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DesktopService is the sole Wails-bound backend service. It owns transport
 * method names and delegates behavior to focused collaborators.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capabilities$0 from "./capabilities/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as objectcatalog$0 from "./objectcatalog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as snapshot$0 from "./refresh/snapshot/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resourcemodel$0 from "./resourcemodel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as panelwindow$0 from "../internal/panelwindow/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcceptPanelTabTransfer(ownerWindowName: string, transferID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.AcceptPanelTabTransfer", ownerWindowName, transferID);
}

export function AcknowledgeApplicationQuitPreflight(ownerWindowName: string, transactionID: string, allowed: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.AcknowledgeApplicationQuitPreflight", ownerWindowName, transactionID, allowed);
}

export function AcknowledgePanelWindowClose(windowName: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.AcknowledgePanelWindowClose", windowName);
}

export function AcknowledgePanelWindowDock(ownerWindowName: string, windowName: string, transferID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.AcknowledgePanelWindowDock", ownerWindowName, windowName, transferID);
}

export function AcknowledgePanelWindowGuard(windowName: string, requestID: string, allowed: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.AcknowledgePanelWindowGuard", windowName, requestID, allowed);
}

export function AcknowledgePanelWindowReady(windowName: string, transferID: string): $CancellablePromise<panelwindow$0.WindowDescriptor> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.AcknowledgePanelWindowReady", windowName, transferID);
}

export function AcknowledgeWorkspaceWindowClose(ownerWindowName: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.AcknowledgeWorkspaceWindowClose", ownerWindowName);
}

export function AddFavorite(favorite: $models.Favorite): $CancellablePromise<$models.Favorite> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.AddFavorite", favorite);
}

export function ApplyClusterWorkspace(command: $models.ClusterWorkspaceCommand): $CancellablePromise<$models.ClusterWorkspaceResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ApplyClusterWorkspace", command);
}

export function ApplyObjectYaml(clusterID: string, request: $models.ObjectYAMLMutationRequest): $CancellablePromise<$models.ObjectYAMLMutationResponse | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ApplyObjectYaml", clusterID, request);
}

export function ApplyTheme(id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ApplyTheme", id);
}

export function AuthorizePanelObjectOpen(ownerWindowName: string, windowName: string, panelID: string, ref: panelwindow$0.ObjectReference, activeView: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.AuthorizePanelObjectOpen", ownerWindowName, windowName, panelID, ref, activeView);
}

export function AuthorizePanelTabClose(ownerWindowName: string, windowName: string, panelID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.AuthorizePanelTabClose", ownerWindowName, windowName, panelID);
}

export function BeginPanelWindowDock(windowName: string, targetPosition: string, snapshot: panelwindow$0.GroupSnapshot): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.BeginPanelWindowDock", windowName, targetPosition, snapshot);
}

export function BeginPanelWindowOpen(windowName: string, snapshot: panelwindow$0.GroupSnapshot): $CancellablePromise<panelwindow$0.WindowDescriptor> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.BeginPanelWindowOpen", windowName, snapshot);
}

function BindingModelAnchor(): $CancellablePromise<$models.BindingModelAnchor> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.BindingModelAnchor");
}

export function CancelDrainNodeJob(clusterID: string, jobID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.CancelDrainNodeJob", clusterID, jobID);
}

export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.CheckForUpdates");
}

export function CheckObjectYamlOwnership(clusterID: string, request: $models.ObjectYAMLMutationRequest): $CancellablePromise<$models.ObjectYAMLOwnershipCheckResponse | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.CheckObjectYamlOwnership", clusterID, request);
}

export function ClearAppLogs(): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ClearAppLogs");
}

export function ClearAppState(): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ClearAppState");
}

export function ClearGridTablePersistence(): $CancellablePromise<number> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ClearGridTablePersistence");
}

export function CloseShellSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.CloseShellSession", sessionID);
}

export function DeleteFavorite(id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.DeleteFavorite", id);
}

export function DeleteGridTablePersistence(key: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.DeleteGridTablePersistence", key);
}

export function DeleteGridTablePersistenceEntries(keys: string[] | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.DeleteGridTablePersistenceEntries", keys);
}

export function DeleteTheme(id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.DeleteTheme", id);
}

export function DiscoverNodeLogs(clusterID: string, nodeName: string): $CancellablePromise<$models.NodeLogDiscoveryResponse> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.DiscoverNodeLogs", clusterID, nodeName);
}

export function DownloadApplicationUpdate(version: string): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.DownloadApplicationUpdate", version);
}

export function ExportFavorites(): $CancellablePromise<$models.DataManagementResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ExportFavorites");
}

export function ExportSettings(): $CancellablePromise<$models.DataManagementResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ExportSettings");
}

export function FailPanelTabTransfer(callerWindowName: string, transferID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.FailPanelTabTransfer", callerWindowName, transferID);
}

export function FailPanelWindowTransfer(callerWindowName: string, windowName: string, transferID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.FailPanelWindowTransfer", callerWindowName, windowName, transferID);
}

export function FetchContainerLogs(clusterID: string, request: $models.ContainerLogsFetchRequest): $CancellablePromise<$models.ContainerLogsFetchResponse> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.FetchContainerLogs", clusterID, request);
}

export function FetchNodeLogs(clusterID: string, nodeName: string, request: $models.NodeLogFetchRequest): $CancellablePromise<$models.NodeLogFetchResponse> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.FetchNodeLogs", clusterID, nodeName, request);
}

export function FindCatalogObjectByUID(clusterID: string, uid: string): $CancellablePromise<objectcatalog$0.Summary | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.FindCatalogObjectByUID", clusterID, uid);
}

export function FindCatalogObjectMatch(clusterID: string, $namespace: string, group: string, version: string, kind: string, name: string): $CancellablePromise<objectcatalog$0.Summary | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.FindCatalogObjectMatch", clusterID, $namespace, group, version, kind, name);
}

export function FocusPanelWindow(ownerWindowName: string, windowName: string, panelID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.FocusPanelWindow", ownerWindowName, windowName, panelID);
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetAppInfo");
}

export function GetAppLogs(): $CancellablePromise<$models.LogEntry[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetAppLogs");
}

export function GetAppLogsSince(sequence: number): $CancellablePromise<$models.LogEntry[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetAppLogsSince", sequence);
}

export function GetAppSettings(): $CancellablePromise<$models.AppSettings | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetAppSettings");
}

export function GetAppSettingsSchema(): $CancellablePromise<$models.AppSettingsSchema | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetAppSettingsSchema");
}

export function GetClusterAllowedNamespaces(clusterID: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetClusterAllowedNamespaces", clusterID);
}

export function GetClusterTabOrder(): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetClusterTabOrder");
}

export function GetClusterWorkspaceStateForWindow(windowID: string): $CancellablePromise<$models.ClusterWorkspaceState> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetClusterWorkspaceStateForWindow", windowID);
}

export function GetContainerLogsScopeContainers(clusterID: string, scope: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetContainerLogsScopeContainers", clusterID, scope);
}

export function GetFavorites(): $CancellablePromise<$models.Favorite[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetFavorites");
}

export function GetGridTablePersistence(): $CancellablePromise<{ [_ in string]?: json$0.RawMessage } | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetGridTablePersistence");
}

export function GetKubeconfigSearchPaths(): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetKubeconfigSearchPaths");
}

export function GetKubeconfigs(): $CancellablePromise<$models.KubeconfigDiscoveryResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetKubeconfigs");
}

export function GetKubernetesAPIClientDiagnostics(): $CancellablePromise<$models.KubernetesAPIClientDiagnostics[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetKubernetesAPIClientDiagnostics");
}

export function GetNativeWindowDescriptor(windowName: string): $CancellablePromise<panelwindow$0.NativeDescriptor> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetNativeWindowDescriptor", windowName);
}

export function GetObjectYAMLByGVK(clusterID: string, apiVersion: string, kind: string, $namespace: string, name: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetObjectYAMLByGVK", clusterID, apiVersion, kind, $namespace, name);
}

export function GetPodContainers(clusterID: string, $namespace: string, podName: string): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetPodContainers", clusterID, $namespace, podName);
}

export function GetRevisionHistory(clusterID: string, $namespace: string, group: string, version: string, workloadKind: string, name: string): $CancellablePromise<$models.RevisionEntry[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetRevisionHistory", clusterID, $namespace, group, version, workloadKind, name);
}

export function GetSelectionDiagnostics(): $CancellablePromise<$models.SelectionDiagnostics | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetSelectionDiagnostics");
}

export function GetShellSessionBacklog(sessionID: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetShellSessionBacklog", sessionID);
}

export function GetTargetPorts(clusterID: string, $namespace: string, targetKind: string, targetGroup: string, targetVersion: string, targetName: string): $CancellablePromise<$models.ContainerPortInfo[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetTargetPorts", clusterID, $namespace, targetKind, targetGroup, targetVersion, targetName);
}

export function GetThemes(): $CancellablePromise<$models.Theme[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetThemes");
}

export function GetZoomLevel(): $CancellablePromise<number> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.GetZoomLevel");
}

export function HydrateCatalogCustomRows(clusterID: string, rows: snapshot$0.ResourceQueryRow[] | null): $CancellablePromise<snapshot$0.CustomResourceSummary[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.HydrateCatalogCustomRows", clusterID, rows);
}

export function IgnoreClusterAttentionFindingType(clusterID: string, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.IgnoreClusterAttentionFindingType", clusterID, findingType);
}

export function IgnoreClusterAttentionObjectFinding(clusterID: string, ref: resourcemodel$0.ResourceRef, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.IgnoreClusterAttentionObjectFinding", clusterID, ref, findingType);
}

export function IgnoreGlobalAttentionFindingType(clusterID: string, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.IgnoreGlobalAttentionFindingType", clusterID, findingType);
}

export function ImportFavorites(): $CancellablePromise<$models.DataManagementResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ImportFavorites");
}

export function ImportSettings(): $CancellablePromise<$models.DataManagementResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ImportSettings");
}

export function IsWorkloadHPAManaged(clusterID: string, $namespace: string, group: string, version: string, kind: string, name: string): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.IsWorkloadHPAManaged", clusterID, $namespace, group, version, kind, name);
}

export function ListPortForwards(): $CancellablePromise<$models.PortForwardSession[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ListPortForwards");
}

export function ListRuntimeOperations(): $CancellablePromise<$models.RuntimeOperation[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ListRuntimeOperations");
}

export function ListShellSessions(): $CancellablePromise<$models.ShellSessionInfo[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ListShellSessions");
}

export function LogAppLogsFromFrontend(level: string, message: string, source: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.LogAppLogsFromFrontend", level, message, source);
}

export function LogAppLogsFromFrontendWithCluster(level: string, message: string, source: string, clusterID: string, clusterName: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.LogAppLogsFromFrontendWithCluster", level, message, source, clusterID, clusterName);
}

export function MatchThemeForCluster(contextName: string): $CancellablePromise<$models.Theme | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.MatchThemeForCluster", contextName);
}

export function MergeObjectYamlWithLatest(clusterID: string, request: $models.ObjectYAMLReloadMergeRequest): $CancellablePromise<$models.ObjectYAMLReloadMergeResponse | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.MergeObjectYamlWithLatest", clusterID, request);
}

export function OpenKubeconfigSearchPathDialog(): $CancellablePromise<string> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.OpenKubeconfigSearchPathDialog");
}

export function QueryPermissions(queries: capabilities$0.PermissionQuery[] | null): $CancellablePromise<capabilities$0.QueryPermissionsResponse | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.QueryPermissions", queries);
}

export function RemoveApplicationUpdateSkip(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RemoveApplicationUpdateSkip");
}

export function ReorderThemes(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ReorderThemes", ids);
}

export function RequestPanelObjectOpen(windowName: string, ref: panelwindow$0.ObjectReference, activeView: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RequestPanelObjectOpen", windowName, ref, activeView);
}

export function RequestPanelTabClose(windowName: string, panelID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RequestPanelTabClose", windowName, panelID);
}

export function RequestPanelTabTransfer(callerWindowName: string, request: panelwindow$0.TabTransferRequest): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RequestPanelTabTransfer", callerWindowName, request);
}

export function RequestPanelWindowClose(callerWindowName: string, windowName: string, reason: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RequestPanelWindowClose", callerWindowName, windowName, reason);
}

export function RequestPanelWindowGuard(ownerWindowName: string, windowName: string, requestID: string, reason: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RequestPanelWindowGuard", ownerWindowName, windowName, requestID, reason);
}

export function ResizeShellSession(sessionID: string, columns: number, rows: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ResizeShellSession", sessionID, columns, rows);
}

export function RestartAndApplyApplicationUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RestartAndApplyApplicationUpdate");
}

export function RestoreClusterAttentionFindingType(clusterID: string, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RestoreClusterAttentionFindingType", clusterID, findingType);
}

export function RestoreClusterAttentionObjectFinding(clusterID: string, ref: resourcemodel$0.ResourceRef, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RestoreClusterAttentionObjectFinding", clusterID, ref, findingType);
}

export function RestoreGlobalAttentionFindingType(clusterID: string, findingType: string): $CancellablePromise<snapshot$0.AttentionIgnoreRules | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RestoreGlobalAttentionFindingType", clusterID, findingType);
}

export function RetryClusterAuth(clusterID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RetryClusterAuth", clusterID);
}

export function RoutePanelWindowCommand(windowName: string, eventName: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RoutePanelWindowCommand", windowName, eventName);
}

export function RunObjectAction(request: $models.ObjectActionRequest): $CancellablePromise<$models.ObjectActionResponse> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.RunObjectAction", request);
}

export function SaveCsvFile(defaultFilename: string, content: string): $CancellablePromise<$models.CatalogQueryCSVExport> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SaveCsvFile", defaultFilename, content);
}

export function SaveTheme(theme: $models.Theme): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SaveTheme", theme);
}

export function SendShellInput(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SendShellInput", sessionID, data);
}

export function SetAppLogsPanelVisible(visible: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SetAppLogsPanelVisible", visible);
}

export function SetClusterAllowedNamespaces(clusterID: string, namespaces: string[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SetClusterAllowedNamespaces", clusterID, namespaces);
}

export function SetClusterTabOrder(order: string[] | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SetClusterTabOrder", order);
}

export function SetFavoriteOrder(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SetFavoriteOrder", ids);
}

export function SetGridTablePersistence(key: string, payload: json$0.RawMessage): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SetGridTablePersistence", key, payload);
}

export function SetKubeconfigSearchPaths(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SetKubeconfigSearchPaths", paths);
}

export function SetSidebarVisible(visible: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SetSidebarVisible", visible);
}

export function SetZoomLevel(level: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SetZoomLevel", level);
}

export function SkipApplicationUpdate(version: string): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.SkipApplicationUpdate", version);
}

export function StartShellSession(clusterID: string, request: $models.ShellSessionRequest): $CancellablePromise<$models.ShellSession | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.StartShellSession", clusterID, request);
}

export function StopPortForward(sessionID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.StopPortForward", sessionID);
}

export function UpdateAppPreferences(request: $models.UpdateAppPreferencesRequest): $CancellablePromise<$models.UpdateAppPreferencesResponse | null> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.UpdateAppPreferences", request);
}

export function UpdateFavorite(favorite: $models.Favorite): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.UpdateFavorite", favorite);
}

export function UpdatePanelWindowSnapshot(windowName: string, snapshot: panelwindow$0.GroupSnapshot): $CancellablePromise<void> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.UpdatePanelWindowSnapshot", windowName, snapshot);
}

export function ValidateThemeClusterPattern(pattern: string): $CancellablePromise<$models.ThemeClusterPatternValidationResult> {
    return $Call.ByName("github.com/luxury-yacht/app/backend.DesktopService.ValidateThemeClusterPattern", pattern);
}

void BindingModelAnchor;
