// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as appupdates$0 from "./internal/appupdates/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resourcemodel$0 from "./resourcemodel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as admission$0 from "./resources/admission/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apiextensions$0 from "./resources/apiextensions/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backendtlspolicy$0 from "./resources/backendtlspolicy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clusterrole$0 from "./resources/clusterrole/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clusterrolebinding$0 from "./resources/clusterrolebinding/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configmap$0 from "./resources/configmap/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cronjob$0 from "./resources/cronjob/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as daemonset$0 from "./resources/daemonset/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as deployment$0 from "./resources/deployment/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as endpointslice$0 from "./resources/endpointslice/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "./resources/events/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gateway$0 from "./resources/gateway/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gatewayclass$0 from "./resources/gatewayclass/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as helm$0 from "./resources/helm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hpa$0 from "./resources/hpa/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ingress$0 from "./resources/ingress/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ingressclass$0 from "./resources/ingressclass/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as job$0 from "./resources/job/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as limitrange$0 from "./resources/limitrange/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as listenerset$0 from "./resources/listenerset/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as namespaces$0 from "./resources/namespaces/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as networkpolicy$0 from "./resources/networkpolicy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nodes$0 from "./resources/nodes/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as persistentvolume$0 from "./resources/persistentvolume/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as persistentvolumeclaim$0 from "./resources/persistentvolumeclaim/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as poddisruptionbudget$0 from "./resources/poddisruptionbudget/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as referencegrant$0 from "./resources/referencegrant/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as replicaset$0 from "./resources/replicaset/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resourcequota$0 from "./resources/resourcequota/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as role$0 from "./resources/role/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rolebinding$0 from "./resources/rolebinding/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as secret$0 from "./resources/secret/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "./resources/service/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as serviceaccount$0 from "./resources/serviceaccount/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as statefulset$0 from "./resources/statefulset/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storageclass$0 from "./resources/storageclass/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./resources/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updateidentity$0 from "../internal/updateidentity/models.js";

/**
 * AppInfo contains application version information
 */
export interface AppInfo {
    "version": string;
    "buildTime": string;
    "gitCommit": string;
    "isBeta": boolean;
    "expiryDate"?: string;
    "update"?: UpdateInfo | null;
}

export interface AppLogsAddedEvent {
    "sequence": number;
}

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type AppSettings = types$0.AppSettings;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type AppSettingsSchema = types$0.AppSettingsSchema;

export interface BackendErrorEvent {
    "clusterId": string;
    "resourceKind"?: string;
    "identifier"?: string;
    "message": string;
    "error"?: string;
    "source"?: string;
}

/**
 * CatalogQueryCSVExport describes a file-backed catalog query export.
 */
export interface CatalogQueryCSVExport {
    "path": string;
    "bytes": number;
}

export interface ClusterAuthEvent {
    "clusterId": string;
    "clusterName": string;
    "reason": string;
    "class": string;
    "kind": string;
    "summary": string;
    "execCommand": string;
}

export interface ClusterAuthProgressEvent {
    "clusterId": string;
    "clusterName": string;
    "reason": string;
    "class": string;
    "kind": string;
    "summary": string;
    "execCommand": string;
    "secondsUntilRetry": number;
    "errorClass": string;
}

export interface ClusterHealthEvent {
    "clusterId": string;
    "clusterName": string;
    "reason"?: string;
}

export enum ClusterHealthState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ClusterHealthUnknown = "unknown",
    ClusterHealthHealthy = "healthy",
    ClusterHealthDegraded = "degraded",
};

export interface ClusterLifecycleEvent {
    "clusterId": string;
    "state": ClusterLifecycleState;
    "previousState": string;
}

/**
 * ClusterLifecycleState represents the current lifecycle phase of a cluster connection.
 */
export enum ClusterLifecycleState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ClusterStateConnecting = "connecting",
    ClusterStateAuthFailed = "auth_failed",
    ClusterStateConnected = "connected",
    ClusterStateLoading = "loading",
    ClusterStateLoadingSlow = "loading_slow",
    ClusterStateDegraded = "degraded",
    ClusterStateReady = "ready",
    ClusterStateDisconnected = "disconnected",
    ClusterStateReconnecting = "reconnecting",
};

export interface ClusterScopeChangedEvent {
    "clusterId": string;
}

export interface ClusterWorkspaceAuthState {
    "state": string;
    "reason": string;
    "errorClass": string;
    "secondsUntilRetry": number;
    "class": string;
    "kind": string;
    "summary": string;
    "execCommand": string;
}

export interface ClusterWorkspaceClusterState {
    "clusterId": string;
    "clusterName": string;
    "lifecycle": ClusterLifecycleState;
    "auth": ClusterWorkspaceAuthState;
    "health": ClusterHealthState;
    "scopeRevision": number;
}

export interface ClusterWorkspaceCommand {
    "windowId": string;
    "selectedKubeconfigs": string[] | null;
    "updateSelectedKubeconfigs": boolean;
    "visibleClusterId": string;
}

export interface ClusterWorkspaceResult {
    "state": ClusterWorkspaceState;
    "error"?: string;
}

export interface ClusterWorkspaceState {
    "selectedKubeconfigs": string[] | null;
    "visibleClusterId": string;
    "clusters": { [_ in string]?: ClusterWorkspaceClusterState } | null;
}

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type ContainerLogsFetchRequest = types$0.ContainerLogsFetchRequest;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type ContainerLogsFetchResponse = types$0.ContainerLogsFetchResponse;

/**
 * ContainerPortInfo describes a port exposed by a container.
 */
export interface ContainerPortInfo {
    "port": number;
    "name"?: string;
    "protocol"?: string;
}

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type CustomResourceDefinitionDetails = apiextensions$0.CustomResourceDefinitionDetails;

export interface DataManagementResult {
    "path": string;
    "canceled": boolean;
    "imported"?: number;
}

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type DebugContainerResponse = types$0.DebugContainerResponse;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type DrainNodeOptions = types$0.DrainNodeOptions;

/**
 * Favorite represents a user-saved view bookmark.
 */
export interface Favorite {
    "id": string;
    "name": string;
    "clusterSelection": string;
    "clusterId"?: string;
    "clusterName"?: string;
    "viewType": string;
    "view": string;
    "namespace": string;
    "panes": { [_ in string]?: FavoritePaneState } | null;
    "order": number;
}

/**
 * FavoriteFilterSelection preserves the semantic difference between every,
 * no, and some selected dropdown values.
 */
export interface FavoriteFilterSelection {
    "mode": string;
    "values"?: string[] | null;
}

/**
 * FavoriteFilters holds the search and filter state for a favorite.
 */
export interface FavoriteFilters {
    "search": string;
    "kinds": FavoriteFilterSelection;
    "namespaces": FavoriteFilterSelection;
    "clusters": FavoriteFilterSelection;
    "queryFacets"?: { [_ in string]?: FavoriteFilterSelection } | null;
    "caseSensitive": boolean;
    "includeMetadata": boolean;
}

/**
 * FavoritePaneState holds the complete GridTable state for one named pane.
 */
export interface FavoritePaneState {
    "filters": FavoriteFilters;
    "tableState": FavoriteTableState;
}

/**
 * FavoriteTableState holds the table display state for a favorite.
 */
export interface FavoriteTableState {
    "sortColumn": string;
    "sortDirection": string;
    "columnVisibility": { [_ in string]?: boolean } | null;
    "columnOrder"?: string[] | null;
}

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type HelmReleaseDetails = helm$0.HelmReleaseDetails;

export interface KubeconfigDiscoveryResult {
    "kubeconfigs": KubeconfigInfo[] | null;
    "state": KubeconfigDiscoveryState;
    "searchPaths": string[] | null;
}

export enum KubeconfigDiscoveryState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KubeconfigDiscoveryStateAvailable = "available",
    KubeconfigDiscoveryStateSearchPathsMissing = "search_paths_missing",
    KubeconfigDiscoveryStateNoKubeconfigs = "no_kubeconfigs",
};

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type KubeconfigInfo = types$0.KubeconfigInfo;

/**
 * KubernetesAPIClientDiagnostics reports per-cluster Kubernetes API client usage.
 */
export interface KubernetesAPIClientDiagnostics {
    "clusterId": string;
    "clusterName": string;
    "configuredQPS": number;
    "configuredBurst": number;
    "qps1s": number;
    "qps10s": number;
    "qps60s": number;
    "peakQPS1s": number;
    "totalRequests": number;
    "status2xx": number;
    "status3xx": number;
    "status4xx": number;
    "status5xx": number;
    "status429": number;
    "errors": number;
    "lastRequestMs"?: number;
}

/**
 * LogEntry represents a single log entry
 */
export interface LogEntry {
    "sequence": number;
    "timestamp": string;
    "level": string;
    "message": string;
    "source"?: string;
    "clusterId"?: string;
    "clusterName"?: string;
    "operationId"?: string;
}

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type NodeLogDiscoveryResponse = types$0.NodeLogDiscoveryResponse;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type NodeLogFetchRequest = types$0.NodeLogFetchRequest;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type NodeLogFetchResponse = types$0.NodeLogFetchResponse;

export interface ObjectActionDebugContainerOptions {
    "image": string;
    "targetContainer"?: string;
}

export interface ObjectActionPortForwardOptions {
    "containerPort": number;
    "localPort": number;
}

export interface ObjectActionRequest {
    "action": string;
    "target": ObjectActionTargetRef;
    "replicas"?: number | null;
    "suspend"?: boolean | null;
    "drainOptions"?: DrainNodeOptions | null;
    "portForward"?: ObjectActionPortForwardOptions | null;
    "debugContainer"?: ObjectActionDebugContainerOptions | null;
    "revision"?: number | null;
    "finalizer"?: string;
    "finalizerPath"?: string;
}

export interface ObjectActionResponse {
    "name"?: string;
    "jobId"?: string;
    "sessionId"?: string;
    "debugContainer"?: DebugContainerResponse | null;
}

/**
 * ObjectActionTargetRef is the canonical object identity for state-changing
 * app actions. Core resources use group="" with version="v1".
 */
export type ObjectActionTargetRef = resourcemodel$0.ResourceRef;

/**
 * ObjectYAMLMutationRequest captures the payload required to validate or apply object YAML.
 */
export interface ObjectYAMLMutationRequest {
    "baseYAML": string;
    "yaml": string;
    "kind": string;
    "apiVersion": string;
    "namespace": string;
    "name": string;
    "uid": string;
    "resourceVersion": string;
}

/**
 * ObjectYAMLMutationResponse returns basic metadata after a validation/apply attempt.
 */
export interface ObjectYAMLMutationResponse {
    "resourceVersion": string;
}

/**
 * ObjectYAMLOwnershipCheckResponse lists the ownership conflicts a save would
 * create. An empty list means the save takes no contested ownership.
 */
export interface ObjectYAMLOwnershipCheckResponse {
    "conflicts": ObjectYAMLOwnershipConflict[] | null;
}

/**
 * ObjectYAMLOwnershipConflict describes one edited field whose current owner
 * is another field manager.
 */
export interface ObjectYAMLOwnershipConflict {
    "field": string;
    "manager": string;
    "message": string;
}

/**
 * ObjectYAMLReloadMergeRequest captures the baseline editor state and the
 * current local draft so the backend can merge them with the latest live
 * object using kubectl-like patch semantics.
 */
export interface ObjectYAMLReloadMergeRequest {
    "baseYAML": string;
    "draftYAML": string;
    "kind": string;
    "apiVersion": string;
    "namespace": string;
    "name": string;
    "uid": string;
}

/**
 * ObjectYAMLReloadMergeResponse returns both the merged draft and the latest
 * live YAML the merge was based on.
 */
export interface ObjectYAMLReloadMergeResponse {
    "mergedYAML": string;
    "currentYAML": string;
    "resourceVersion": string;
}

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type PodDetailInfo = types$0.PodDetailInfo;

/**
 * PortForwardSession represents an active port forwarding session.
 */
export interface PortForwardSession {
    "id": string;
    "clusterId": string;
    "clusterName": string;
    "namespace": string;
    "podName": string;
    "containerPort": number;
    "localPort": number;
    "targetKind": string;
    "targetGroup": string;
    "targetVersion": string;
    "targetName": string;
    "status": PortForwardStatus;
    "statusReason"?: string;
    "startedAt": string;
}

/**
 * PortForwardStatus is the lifecycle status of a port-forward session. It is a
 * closed set so the compiler rejects an invalid or typo'd status at every
 * assignment site, making an unrepresentable status impossible.
 */
export enum PortForwardStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PortForwardStatusConnecting = "connecting",
    PortForwardStatusActive = "active",
    PortForwardStatusReconnecting = "reconnecting",
    PortForwardStatusError = "error",
    PortForwardStatusStopped = "stopped",
};

/**
 * PortForwardStatusEvent is emitted on status changes.
 */
export interface PortForwardStatusEvent {
    "sessionId": string;
    "clusterId": string;
    "status": PortForwardStatus;
    "statusReason"?: string;
    "localPort"?: number;
    "podName"?: string;
}

/**
 * RevisionEntry describes a single historical revision of a workload rollout.
 */
export interface RevisionEntry {
    /**
     * Revision is the monotonically increasing revision number.
     */
    "revision": number;

    /**
     * CreatedAt is the ISO-8601 creation timestamp of the underlying ReplicaSet or ControllerRevision.
     */
    "createdAt": string;

    /**
     * ChangeCause is the value of the kubernetes.io/change-cause annotation, if present.
     */
    "changeCause": string;

    /**
     * Current indicates that this revision matches the workload's active revision.
     */
    "current": boolean;

    /**
     * PodTemplate is the YAML-serialised pod template spec for this revision.
     */
    "podTemplate": string;
}

export interface RuntimeOperation {
    "id": string;
    "type": RuntimeOperationType;
    "clusterId": string;
    "clusterName"?: string;
    "target"?: RuntimeOperationTargetRef | null;
    "status": string;
    "statusReason"?: string;
    "startedAt": string;
    "displayName"?: string;
    "summary"?: { [_ in string]?: string } | null;
}

export type RuntimeOperationTargetRef = resourcemodel$0.ResourceRef;

export enum RuntimeOperationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeOperationShell = "shell",
    RuntimeOperationPortForward = "port-forward",
    RuntimeOperationDrain = "drain",
};

/**
 * SelectionDiagnostics summarizes cluster selection mutation performance.
 */
export interface SelectionDiagnostics {
    "activeQueueDepth": number;
    "maxQueueDepth": number;
    "sampleCount": number;
    "totalMutations": number;
    "completedMutations": number;
    "failedMutations": number;
    "canceledMutations": number;
    "supersededMutations": number;
    "lastUpdatedMs"?: number;
    "lastReason"?: string;
    "lastError"?: string;
    "lastQueueMs"?: number;
    "lastTotalMs"?: number;
    "queueP50Ms"?: number;
    "queueP95Ms"?: number;
    "totalP50Ms"?: number;
    "totalP95Ms"?: number;
    "intentP50Ms"?: number;
    "intentP95Ms"?: number;
    "commitP50Ms"?: number;
    "commitP95Ms"?: number;
    "clientSyncP50Ms"?: number;
    "clientSyncP95Ms"?: number;
    "refreshP50Ms"?: number;
    "refreshP95Ms"?: number;
    "catalogP50Ms"?: number;
    "catalogP95Ms"?: number;
}

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type ShellOutputEvent = types$0.ShellOutputEvent;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type ShellSession = types$0.ShellSession;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type ShellSessionInfo = types$0.ShellSessionInfo;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type ShellSessionRequest = types$0.ShellSessionRequest;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type ShellStatusEvent = types$0.ShellStatusEvent;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type Theme = types$0.Theme;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type ThemeClusterPatternValidationResult = types$0.ThemeClusterPatternValidationResult;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type UpdateAppPreferencesRequest = types$0.UpdateAppPreferencesRequest;

/**
 * Per-kind detail DTOs are no longer re-exported here. The generated
 * ResourceGateway.Get<Kind> methods (resource_details_generated.go) reference
 * each kind's DTO by its own package (e.g. deployment.DeploymentDetails), and Wails reaches every
 * nested sub-type through those parent structs — so no package-backend alias is
 * needed for any kind DTO or its sub-types. What remains is app-level and shared
 * types (settings, logs, shell, cluster-tab infos, common ref/condition/route
 * sub-types in resources/types) plus the three DTOs whose detail binding is
 * hand-written and therefore still named in package backend (HelmReleaseDetails,
 * PodDetailInfo, CustomResourceDefinitionDetails).
 */
export type UpdateAppPreferencesResponse = types$0.UpdateAppPreferencesResponse;

export interface UpdateInfo {
    "status": appupdates$0.Status;
    "currentVersion"?: string;
    "availableVersion"?: string;
    "releaseName"?: string;
    "publishedAt"?: string;
    "releaseNotes"?: string;
    "progressPercent"?: number | null;
    "canCheck": boolean;
    "canInstall": boolean;
    "distribution"?: updateidentity$0.Distribution;
    "eligibilityReason"?: updateidentity$0.EligibilityReason;
    "recoveryTarget"?: updateidentity$0.RecoveryTarget;
    "error"?: string;
}

/**
 * BindingModelAnchor keeps object-detail DTOs reachable by the Wails generator
 * without exporting the backend-only Get<Kind> wrappers to TypeScript.
 */
export interface BindingModelAnchor {
    "BackendTLSPolicy": backendtlspolicy$0.BackendTLSPolicyDetails | null;
    "ClusterRole": clusterrole$0.ClusterRoleDetails | null;
    "ClusterRoleBinding": clusterrolebinding$0.ClusterRoleBindingDetails | null;
    "ConfigMap": configmap$0.ConfigMapDetails | null;
    "CronJob": cronjob$0.CronJobDetails | null;
    "DaemonSet": daemonset$0.DaemonSetDetails | null;
    "Deployment": deployment$0.DeploymentDetails | null;
    "EndpointSlice": endpointslice$0.EndpointSliceDetails | null;
    "Event": events$0.EventDetails | null;
    "GRPCRoute": types$0.GRPCRouteDetails | null;
    "Gateway": gateway$0.GatewayDetails | null;
    "GatewayClass": gatewayclass$0.GatewayClassDetails | null;
    "HTTPRoute": types$0.HTTPRouteDetails | null;
    "HorizontalPodAutoscaler": hpa$0.HorizontalPodAutoscalerDetails | null;
    "Ingress": ingress$0.IngressDetails | null;
    "IngressClass": ingressclass$0.IngressClassDetails | null;
    "Job": job$0.JobDetails | null;
    "LimitRange": limitrange$0.LimitRangeDetails | null;
    "ListenerSet": listenerset$0.ListenerSetDetails | null;
    "MutatingWebhookConfiguration": admission$0.MutatingWebhookConfigurationDetails | null;
    "Namespace": namespaces$0.NamespaceDetails | null;
    "NetworkPolicy": networkpolicy$0.NetworkPolicyDetails | null;
    "Node": nodes$0.NodeDetails | null;
    "PersistentVolume": persistentvolume$0.PersistentVolumeDetails | null;
    "PersistentVolumeClaim": persistentvolumeclaim$0.PersistentVolumeClaimDetails | null;
    "PodDisruptionBudget": poddisruptionbudget$0.PodDisruptionBudgetDetails | null;
    "ReferenceGrant": referencegrant$0.ReferenceGrantDetails | null;
    "ReplicaSet": replicaset$0.ReplicaSetDetails | null;
    "ResourceQuota": resourcequota$0.ResourceQuotaDetails | null;
    "Role": role$0.RoleDetails | null;
    "RoleBinding": rolebinding$0.RoleBindingDetails | null;
    "Secret": secret$0.SecretDetails | null;
    "Service": service$0.ServiceDetails | null;
    "ServiceAccount": serviceaccount$0.ServiceAccountDetails | null;
    "StatefulSet": statefulset$0.StatefulSetDetails | null;
    "StorageClass": storageclass$0.StorageClassDetails | null;
    "TLSRoute": types$0.TLSRouteDetails | null;
    "ValidatingWebhookConfiguration": admission$0.ValidatingWebhookConfigurationDetails | null;
    "CustomResourceDefinition": CustomResourceDefinitionDetails | null;
    "HelmRelease": HelmReleaseDetails | null;
    "Pod": PodDetailInfo | null;
}
