import type { ResourceFormDefinition } from './types';

export const deploymentDefinition: ResourceFormDefinition = {
  kind: 'Deployment',
  sections: [
    {
      title: 'Metadata',
      fields: [
        {
          key: 'name',
          label: 'Name',
          path: ['metadata', 'name'],
          type: 'text',
          placeholder: 'deployment-name',
        },
        {
          key: 'namespace',
          label: 'Namespace',
          path: ['metadata', 'namespace'],
          type: 'namespace-select',
        },
        {
          key: 'replicas',
          label: 'Replicas',
          path: ['spec', 'replicas'],
          type: 'number',
          placeholder: '1',
          min: 0,
          max: 999,
          integer: true,
          inputWidth: '6ch',
        },
        {
          key: 'serviceAccountName',
          label: 'Service Account',
          path: ['spec', 'template', 'spec', 'serviceAccountName'],
          type: 'text',
          placeholder: 'default',
          omitIfEmpty: true,
        },
        {
          key: 'selectors',
          label: 'Selectors',
          path: ['spec', 'selector', 'matchLabels'],
          type: 'selector-list',
          mirrorPaths: [
            ['metadata', 'labels'],
            ['spec', 'template', 'metadata', 'labels'],
          ],
          addLabel: 'Add Selector',
          addGhostText: 'Add selector',
          inlineLabels: true,
          leftAlignEmptyActions: true,
        },
        {
          key: 'labels',
          label: 'Labels',
          path: ['metadata', 'labels'],
          type: 'key-value-list',
          excludedKeysSourcePath: ['spec', 'selector', 'matchLabels'],
          addLabel: 'Add Label',
          addGhostText: 'Add label',
          inlineLabels: true,
          leftAlignEmptyActions: true,
          blankNewKeys: true,
        },
        {
          key: 'annotations',
          label: 'Annotations',
          path: ['metadata', 'annotations'],
          type: 'key-value-list',
          addLabel: 'Add Annotation',
          addGhostText: 'Add annotation',
          inlineLabels: true,
          leftAlignEmptyActions: true,
          blankNewKeys: true,
        },
      ],
    },
    {
      title: 'Containers',
      fields: [
        {
          key: 'containers',
          label: 'Containers',
          path: ['spec', 'template', 'spec', 'containers'],
          type: 'group-list',
          fullWidth: true,
          itemTitleField: 'name',
          itemTitleFallback: 'Container',
          fields: [
            {
              key: 'name',
              label: 'Name',
              path: ['name'],
              type: 'text',
              placeholder: 'container-name',
            },
            {
              key: 'image',
              label: 'Image',
              path: ['image'],
              type: 'text',
              placeholder: 'repo/image:tag',
              groupWithNext: true,
            },
            {
              key: 'imagePullPolicy',
              label: 'Pull Policy',
              path: ['imagePullPolicy'],
              type: 'select',
              dropdownWidth: 'calc(12ch + 40px)',
              options: [
                { label: 'Always', value: 'Always' },
                { label: 'IfNotPresent', value: 'IfNotPresent' },
                { label: 'Never', value: 'Never' },
              ],
            },
            {
              key: 'command',
              label: 'Command',
              path: ['command'],
              type: 'string-list',
              placeholder: '/bin/sh, -c',
            },
            {
              key: 'args',
              label: 'Args',
              path: ['args'],
              type: 'string-list',
              placeholder: 'arg1, arg2',
            },
            {
              key: 'env',
              label: 'Env Vars',
              path: ['env'],
              type: 'group-list',
              leftAlignEmptyActions: true,
              addGhostText: 'Add env var',
              fieldGap: 'wide',
              fields: [
                {
                  key: 'name',
                  label: 'Name',
                  path: ['name'],
                  type: 'text',
                  placeholder: 'name',
                  fieldFlex: '0 0 auto',
                  inputWidth: 'calc(25ch + 20px)',
                },
                {
                  key: 'value',
                  label: 'Value',
                  path: ['value'],
                  type: 'text',
                  placeholder: 'value',
                  fieldFlex: '0 0 auto',
                  inputWidth: 'calc(25ch + 20px)',
                },
              ],
              defaultValue: { name: '', value: '' },
            },
            {
              key: 'ports',
              label: 'Ports',
              path: ['ports'],
              type: 'group-list',
              leftAlignEmptyActions: true,
              addGhostText: 'Add port',
              fieldGap: 'wide',
              fields: [
                {
                  key: 'name',
                  label: 'Name',
                  path: ['name'],
                  type: 'text',
                  placeholder: 'optional',
                  omitIfEmpty: true,
                  fieldFlex: '0 0 auto',
                  inputWidth: 'calc(10ch + 20px)',
                },
                {
                  key: 'containerPort',
                  label: 'Port',
                  path: ['containerPort'],
                  type: 'number',
                  placeholder: '80',
                  min: 1,
                  max: 65535,
                  integer: true,
                  fieldFlex: '0 0 auto',
                  inputWidth: 'calc(5ch + 20px)',
                },
                {
                  key: 'protocol',
                  label: 'Protocol',
                  path: ['protocol'],
                  type: 'select',
                  includeEmptyOption: false,
                  implicitDefault: 'TCP',
                  fieldFlex: '0 0 auto',
                  options: [
                    { label: 'TCP', value: 'TCP' },
                    { label: 'UDP', value: 'UDP' },
                  ],
                },
              ],
              defaultValue: { protocol: 'TCP' },
            },
            {
              key: 'resources',
              label: 'Resources',
              path: ['resources'],
              type: 'container-resources',
            },
            {
              key: 'volumeMounts',
              label: 'Vol Mounts',
              path: ['volumeMounts'],
              type: 'group-list',
              leftAlignEmptyActions: true,
              addGhostText: 'Add volume mount',
              disabledGhostText: 'Add a Volume below to enable Volume Mounts',
              fieldGap: 'wide',
              wrapFields: true,
              rowAlign: 'start',
              fields: [
                {
                  key: 'name',
                  label: 'Name',
                  path: ['name'],
                  type: 'select',
                  dynamicOptionsPath: ['spec', 'template', 'spec', 'volumes'],
                  dynamicOptionsField: 'name',
                  fieldFlex: '0 0 100%',
                  inputWidth: 'calc(30ch + 20px)',
                },
                {
                  key: 'mountPath',
                  label: 'Path',
                  path: ['mountPath'],
                  type: 'text',
                  placeholder: '/mnt/data',
                  fieldFlex: '0 0 auto',
                  inputWidth: 'calc(30ch + 20px)',
                  labelWidth: '4rem',
                },
                {
                  key: 'readOnly',
                  label: 'Read Only',
                  path: ['readOnly'],
                  type: 'boolean-toggle',
                  fieldFlex: '0 0 auto',
                },
                {
                  key: 'subPath',
                  label: 'Sub Path',
                  path: ['subPath'],
                  type: 'text',
                  placeholder: 'optional',
                  alternatePath: ['subPathExpr'],
                  alternateLabel: 'Use Expression',
                  fieldFlex: '0 0 100%',
                  inputWidth: 'calc(30ch + 20px)',
                  labelWidth: '4rem',
                },
              ],
              defaultValue: { name: '', mountPath: '' },
            },
          ],
          defaultValue: { name: '', image: '', ports: [], env: [], volumeMounts: [] },
        },
      ],
    },
    {
      title: 'Volumes',
      fields: [
        {
          key: 'volumes',
          label: 'Volumes',
          path: ['spec', 'template', 'spec', 'volumes'],
          type: 'group-list',
          fullWidth: true,
          itemTitleField: 'name',
          itemTitleFallback: 'Volume',
          fields: [
            {
              key: 'name',
              label: 'Name',
              path: ['name'],
              type: 'text',
              placeholder: 'volume-name',
            },
            {
              key: 'source',
              label: 'Source',
              path: ['source'],
              type: 'volume-source',
            },
          ],
          defaultValue: {},
        },
      ],
    },
  ],
};
