// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * NamespaceDetails represents comprehensive namespace information.
 */
export interface NamespaceDetails {
    "kind": string;
    "name": string;
    "details": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;
    "hasWorkloads": boolean;
    "workloadsUnknown"?: boolean;
    "finalizers"?: string[] | null;
    "conditions"?: types$0.ConditionState[] | null;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
    "resourceQuotas"?: types$0.ObjectRef[] | null;
    "limitRanges"?: types$0.ObjectRef[] | null;
}
