// Code generated by genappbindings; DO NOT EDIT.

package backend

import (
	"context"
	"github.com/luxury-yacht/app/backend/resources/admission"
	"github.com/luxury-yacht/app/backend/resources/apiextensions"
	"github.com/luxury-yacht/app/backend/resources/backendtlspolicy"
	"github.com/luxury-yacht/app/backend/resources/clusterrole"
	"github.com/luxury-yacht/app/backend/resources/clusterrolebinding"
	"github.com/luxury-yacht/app/backend/resources/common"
	"github.com/luxury-yacht/app/backend/resources/configmap"
	"github.com/luxury-yacht/app/backend/resources/cronjob"
	"github.com/luxury-yacht/app/backend/resources/daemonset"
	"github.com/luxury-yacht/app/backend/resources/deployment"
	"github.com/luxury-yacht/app/backend/resources/endpointslice"
	"github.com/luxury-yacht/app/backend/resources/events"
	"github.com/luxury-yacht/app/backend/resources/gateway"
	"github.com/luxury-yacht/app/backend/resources/gatewayclass"
	"github.com/luxury-yacht/app/backend/resources/grpcroute"
	"github.com/luxury-yacht/app/backend/resources/helm"
	"github.com/luxury-yacht/app/backend/resources/hpa"
	"github.com/luxury-yacht/app/backend/resources/httproute"
	"github.com/luxury-yacht/app/backend/resources/ingress"
	"github.com/luxury-yacht/app/backend/resources/ingressclass"
	"github.com/luxury-yacht/app/backend/resources/job"
	"github.com/luxury-yacht/app/backend/resources/limitrange"
	"github.com/luxury-yacht/app/backend/resources/listenerset"
	"github.com/luxury-yacht/app/backend/resources/namespaces"
	"github.com/luxury-yacht/app/backend/resources/networkpolicy"
	"github.com/luxury-yacht/app/backend/resources/nodes"
	"github.com/luxury-yacht/app/backend/resources/persistentvolume"
	"github.com/luxury-yacht/app/backend/resources/persistentvolumeclaim"
	"github.com/luxury-yacht/app/backend/resources/poddisruptionbudget"
	"github.com/luxury-yacht/app/backend/resources/pods"
	"github.com/luxury-yacht/app/backend/resources/referencegrant"
	"github.com/luxury-yacht/app/backend/resources/replicaset"
	"github.com/luxury-yacht/app/backend/resources/resourcequota"
	"github.com/luxury-yacht/app/backend/resources/role"
	"github.com/luxury-yacht/app/backend/resources/rolebinding"
	"github.com/luxury-yacht/app/backend/resources/secret"
	"github.com/luxury-yacht/app/backend/resources/service"
	"github.com/luxury-yacht/app/backend/resources/serviceaccount"
	"github.com/luxury-yacht/app/backend/resources/statefulset"
	"github.com/luxury-yacht/app/backend/resources/storageclass"
	"github.com/luxury-yacht/app/backend/resources/tlsroute"
)

// objectDetailFetchers maps a kind's dispatch key to its typed detail retrieval.
var objectDetailFetchers = map[string]objectDetailFetcher{
	"backendtlspolicy": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := backendtlspolicy.NewService(deps).BackendTLSPolicy(ctx, namespace, name)
			return detail, err
		},
	},
	"clusterrole": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := clusterrole.NewService(deps).ClusterRole(ctx, name)
			return detail, err
		},
	},
	"clusterrolebinding": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := clusterrolebinding.NewService(deps).ClusterRoleBinding(ctx, name)
			return detail, err
		},
	},
	"configmap": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := configmap.NewService(deps).ConfigMap(ctx, namespace, name)
			return detail, err
		},
	},
	"cronjob": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := cronjob.NewService(deps).CronJob(ctx, namespace, name)
			return detail, err
		},
	},
	"customresourcedefinition": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := apiextensions.NewService(deps).CustomResourceDefinition(ctx, name)
			return detail, err
		},
	},
	"daemonset": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := daemonset.NewService(deps).DaemonSet(ctx, namespace, name)
			return detail, err
		},
	},
	"deployment": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := deployment.NewService(deps).Deployment(ctx, namespace, name)
			return detail, err
		},
	},
	"endpointslice": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := endpointslice.NewService(deps).EndpointSlice(ctx, namespace, name)
			return detail, err
		},
	},
	"event": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := events.NewService(deps).Event(ctx, namespace, name)
			return detail, err
		},
	},
	"gateway": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := gateway.NewService(deps).Gateway(ctx, namespace, name)
			return detail, err
		},
	},
	"gatewayclass": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := gatewayclass.NewService(deps).GatewayClass(ctx, name)
			return detail, err
		},
	},
	"grpcroute": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := grpcroute.NewService(deps).GRPCRoute(ctx, namespace, name)
			return detail, err
		},
	},
	"helmrelease": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := helm.NewService(helm.Dependencies{Common: deps}).ReleaseDetails(ctx, namespace, name)
			return detail, err
		},
	},
	"horizontalpodautoscaler": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := hpa.NewService(deps).HorizontalPodAutoscaler(ctx, namespace, name)
			return detail, err
		},
	},
	"httproute": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := httproute.NewService(deps).HTTPRoute(ctx, namespace, name)
			return detail, err
		},
	},
	"ingress": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := ingress.NewService(deps).Ingress(ctx, namespace, name)
			return detail, err
		},
	},
	"ingressclass": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := ingressclass.NewService(deps).IngressClass(ctx, name)
			return detail, err
		},
	},
	"job": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := job.NewService(deps).Job(ctx, namespace, name)
			return detail, err
		},
	},
	"limitrange": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := limitrange.NewService(deps).LimitRange(ctx, namespace, name)
			return detail, err
		},
	},
	"listenerset": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := listenerset.NewService(deps).ListenerSet(ctx, namespace, name)
			return detail, err
		},
	},
	"mutatingwebhookconfiguration": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := admission.NewService(deps).MutatingWebhookConfiguration(ctx, name)
			return detail, err
		},
	},
	"namespace": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := namespaces.NewService(deps).Namespace(ctx, name)
			return detail, err
		},
	},
	"networkpolicy": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := networkpolicy.NewService(deps).NetworkPolicy(ctx, namespace, name)
			return detail, err
		},
	},
	"node": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := nodes.NewService(deps).Node(ctx, name)
			return detail, err
		},
	},
	"persistentvolume": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := persistentvolume.NewService(deps).PersistentVolume(ctx, name)
			return detail, err
		},
	},
	"persistentvolumeclaim": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := persistentvolumeclaim.NewService(deps).PersistentVolumeClaim(ctx, namespace, name)
			return detail, err
		},
	},
	"pod": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := pods.GetPod(ctx, deps, namespace, name, true)
			return detail, err
		},
	},
	"poddisruptionbudget": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := poddisruptionbudget.NewService(deps).PodDisruptionBudget(ctx, namespace, name)
			return detail, err
		},
	},
	"referencegrant": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := referencegrant.NewService(deps).ReferenceGrant(ctx, namespace, name)
			return detail, err
		},
	},
	"replicaset": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := replicaset.NewService(deps).ReplicaSet(ctx, namespace, name)
			return detail, err
		},
	},
	"resourcequota": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := resourcequota.NewService(deps).ResourceQuota(ctx, namespace, name)
			return detail, err
		},
	},
	"role": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := role.NewService(deps).Role(ctx, namespace, name)
			return detail, err
		},
	},
	"rolebinding": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := rolebinding.NewService(deps).RoleBinding(ctx, namespace, name)
			return detail, err
		},
	},
	"secret": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := secret.NewService(deps).Secret(ctx, namespace, name)
			return detail, err
		},
	},
	"service": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := service.NewService(deps).GetService(ctx, namespace, name)
			return detail, err
		},
	},
	"serviceaccount": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := serviceaccount.NewService(deps).ServiceAccount(ctx, namespace, name)
			return detail, err
		},
	},
	"statefulset": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := statefulset.NewService(deps).StatefulSet(ctx, namespace, name)
			return detail, err
		},
	},
	"storageclass": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := storageclass.NewService(deps).StorageClass(ctx, name)
			return detail, err
		},
	},
	"tlsroute": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := tlsroute.NewService(deps).TLSRoute(ctx, namespace, name)
			return detail, err
		},
	},
	"validatingwebhookconfiguration": {
		withDeps: func(ctx context.Context, deps common.Dependencies, namespace, name string) (interface{}, error) {
			detail, err := admission.NewService(deps).ValidatingWebhookConfiguration(ctx, name)
			return detail, err
		},
	},
}
