// Code generated by genappbindings; DO NOT EDIT.

package backend

import (
	"github.com/luxury-yacht/app/backend/resources/admission"
	"github.com/luxury-yacht/app/backend/resources/clusterrole"
	"github.com/luxury-yacht/app/backend/resources/clusterrolebinding"
	"github.com/luxury-yacht/app/backend/resources/configmap"
	"github.com/luxury-yacht/app/backend/resources/cronjob"
	"github.com/luxury-yacht/app/backend/resources/daemonset"
	"github.com/luxury-yacht/app/backend/resources/deployment"
	"github.com/luxury-yacht/app/backend/resources/endpointslice"
	"github.com/luxury-yacht/app/backend/resources/gatewayapi"
	"github.com/luxury-yacht/app/backend/resources/hpa"
	"github.com/luxury-yacht/app/backend/resources/ingress"
	"github.com/luxury-yacht/app/backend/resources/ingressclass"
	"github.com/luxury-yacht/app/backend/resources/job"
	"github.com/luxury-yacht/app/backend/resources/limitrange"
	"github.com/luxury-yacht/app/backend/resources/namespaces"
	"github.com/luxury-yacht/app/backend/resources/networkpolicy"
	"github.com/luxury-yacht/app/backend/resources/nodes"
	"github.com/luxury-yacht/app/backend/resources/persistentvolume"
	"github.com/luxury-yacht/app/backend/resources/persistentvolumeclaim"
	"github.com/luxury-yacht/app/backend/resources/poddisruptionbudget"
	"github.com/luxury-yacht/app/backend/resources/replicaset"
	"github.com/luxury-yacht/app/backend/resources/resourcequota"
	"github.com/luxury-yacht/app/backend/resources/role"
	"github.com/luxury-yacht/app/backend/resources/rolebinding"
	"github.com/luxury-yacht/app/backend/resources/secret"
	"github.com/luxury-yacht/app/backend/resources/service"
	"github.com/luxury-yacht/app/backend/resources/serviceaccount"
	"github.com/luxury-yacht/app/backend/resources/statefulset"
	"github.com/luxury-yacht/app/backend/resources/storageclass"
)

func (a *App) GetBackendTLSPolicy(clusterID, namespace, name string) (*BackendTLSPolicyDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "BackendTLSPolicy", namespace, name, func() (*BackendTLSPolicyDetails, error) {
		return gatewayapi.NewService(deps).BackendTLSPolicy(namespace, name)
	})
}

func (a *App) GetClusterRole(clusterID, name string) (*ClusterRoleDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "ClusterRole", name, func() (*ClusterRoleDetails, error) {
		return clusterrole.NewService(deps).ClusterRole(name)
	})
}

func (a *App) GetClusterRoleBinding(clusterID, name string) (*ClusterRoleBindingDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "ClusterRoleBinding", name, func() (*ClusterRoleBindingDetails, error) {
		return clusterrolebinding.NewService(deps).ClusterRoleBinding(name)
	})
}

func (a *App) GetConfigMap(clusterID, namespace, name string) (*ConfigMapDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ConfigMap", namespace, name, func() (*ConfigMapDetails, error) {
		return configmap.NewService(deps).ConfigMap(namespace, name)
	})
}

func (a *App) GetCronJob(clusterID, namespace, name string) (*CronJobDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "CronJob", namespace, name, func() (*CronJobDetails, error) {
		return cronjob.NewService(deps).CronJob(namespace, name)
	})
}

func (a *App) GetDaemonSet(clusterID, namespace, name string) (*DaemonSetDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "DaemonSet", namespace, name, func() (*DaemonSetDetails, error) {
		return daemonset.NewService(deps).DaemonSet(namespace, name)
	})
}

func (a *App) GetDeployment(clusterID, namespace, name string) (*DeploymentDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Deployment", namespace, name, func() (*DeploymentDetails, error) {
		return deployment.NewService(deps).Deployment(namespace, name)
	})
}

func (a *App) GetEndpointSlice(clusterID, namespace, name string) (*EndpointSliceDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "EndpointSlice", namespace, name, func() (*EndpointSliceDetails, error) {
		return endpointslice.NewService(deps).EndpointSlice(namespace, name)
	})
}

func (a *App) GetGRPCRoute(clusterID, namespace, name string) (*GRPCRouteDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "GRPCRoute", namespace, name, func() (*GRPCRouteDetails, error) {
		return gatewayapi.NewService(deps).GRPCRoute(namespace, name)
	})
}

func (a *App) GetGateway(clusterID, namespace, name string) (*GatewayDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Gateway", namespace, name, func() (*GatewayDetails, error) {
		return gatewayapi.NewService(deps).Gateway(namespace, name)
	})
}

func (a *App) GetGatewayClass(clusterID, name string) (*GatewayClassDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "GatewayClass", name, func() (*GatewayClassDetails, error) {
		return gatewayapi.NewService(deps).GatewayClass(name)
	})
}

func (a *App) GetHTTPRoute(clusterID, namespace, name string) (*HTTPRouteDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "HTTPRoute", namespace, name, func() (*HTTPRouteDetails, error) {
		return gatewayapi.NewService(deps).HTTPRoute(namespace, name)
	})
}

func (a *App) GetHorizontalPodAutoscaler(clusterID, namespace, name string) (*HorizontalPodAutoscalerDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "HPA", namespace, name, func() (*HorizontalPodAutoscalerDetails, error) {
		return hpa.NewService(deps).HorizontalPodAutoscaler(namespace, name)
	})
}

func (a *App) GetIngress(clusterID, namespace, name string) (*IngressDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Ingress", namespace, name, func() (*IngressDetails, error) {
		return ingress.NewService(deps).Ingress(namespace, name)
	})
}

func (a *App) GetIngressClass(clusterID, name string) (*IngressClassDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "IngressClass", name, func() (*IngressClassDetails, error) {
		return ingressclass.NewService(deps).IngressClass(name)
	})
}

func (a *App) GetJob(clusterID, namespace, name string) (*JobDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Job", namespace, name, func() (*JobDetails, error) {
		return job.NewService(deps).Job(namespace, name)
	})
}

func (a *App) GetLimitRange(clusterID, namespace, name string) (*LimitRangeDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "LimitRange", namespace, name, func() (*LimitRangeDetails, error) {
		return limitrange.NewService(deps).LimitRange(namespace, name)
	})
}

func (a *App) GetListenerSet(clusterID, namespace, name string) (*ListenerSetDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ListenerSet", namespace, name, func() (*ListenerSetDetails, error) {
		return gatewayapi.NewService(deps).ListenerSet(namespace, name)
	})
}

func (a *App) GetMutatingWebhookConfiguration(clusterID, name string) (*MutatingWebhookConfigurationDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "MutatingWebhookConfiguration", name, func() (*MutatingWebhookConfigurationDetails, error) {
		return admission.NewService(deps).MutatingWebhookConfiguration(name)
	})
}

func (a *App) GetNamespace(clusterID, name string) (*NamespaceDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "Namespace", name, func() (*NamespaceDetails, error) {
		return namespaces.NewService(deps).Namespace(name)
	})
}

func (a *App) GetNetworkPolicy(clusterID, namespace, name string) (*NetworkPolicyDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "NetworkPolicy", namespace, name, func() (*NetworkPolicyDetails, error) {
		return networkpolicy.NewService(deps).NetworkPolicy(namespace, name)
	})
}

func (a *App) GetNode(clusterID, name string) (*NodeDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "Node", name, func() (*NodeDetails, error) {
		return nodes.NewService(deps).Node(name)
	})
}

func (a *App) GetPersistentVolume(clusterID, name string) (*PersistentVolumeDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "PersistentVolume", name, func() (*PersistentVolumeDetails, error) {
		return persistentvolume.NewService(deps).PersistentVolume(name)
	})
}

func (a *App) GetPersistentVolumeClaim(clusterID, namespace, name string) (*PersistentVolumeClaimDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "PVC", namespace, name, func() (*PersistentVolumeClaimDetails, error) {
		return persistentvolumeclaim.NewService(deps).PersistentVolumeClaim(namespace, name)
	})
}

func (a *App) GetPodDisruptionBudget(clusterID, namespace, name string) (*PodDisruptionBudgetDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "PodDisruptionBudget", namespace, name, func() (*PodDisruptionBudgetDetails, error) {
		return poddisruptionbudget.NewService(deps).PodDisruptionBudget(namespace, name)
	})
}

func (a *App) GetReferenceGrant(clusterID, namespace, name string) (*ReferenceGrantDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ReferenceGrant", namespace, name, func() (*ReferenceGrantDetails, error) {
		return gatewayapi.NewService(deps).ReferenceGrant(namespace, name)
	})
}

func (a *App) GetReplicaSet(clusterID, namespace, name string) (*ReplicaSetDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ReplicaSet", namespace, name, func() (*ReplicaSetDetails, error) {
		return replicaset.NewService(deps).ReplicaSet(namespace, name)
	})
}

func (a *App) GetResourceQuota(clusterID, namespace, name string) (*ResourceQuotaDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ResourceQuota", namespace, name, func() (*ResourceQuotaDetails, error) {
		return resourcequota.NewService(deps).ResourceQuota(namespace, name)
	})
}

func (a *App) GetRole(clusterID, namespace, name string) (*RoleDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Role", namespace, name, func() (*RoleDetails, error) {
		return role.NewService(deps).Role(namespace, name)
	})
}

func (a *App) GetRoleBinding(clusterID, namespace, name string) (*RoleBindingDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "RoleBinding", namespace, name, func() (*RoleBindingDetails, error) {
		return rolebinding.NewService(deps).RoleBinding(namespace, name)
	})
}

func (a *App) GetSecret(clusterID, namespace, name string) (*SecretDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Secret", namespace, name, func() (*SecretDetails, error) {
		return secret.NewService(deps).Secret(namespace, name)
	})
}

func (a *App) GetService(clusterID, namespace, name string) (*ServiceDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Service", namespace, name, func() (*ServiceDetails, error) {
		return service.NewService(deps).GetService(namespace, name)
	})
}

func (a *App) GetServiceAccount(clusterID, namespace, name string) (*ServiceAccountDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ServiceAccount", namespace, name, func() (*ServiceAccountDetails, error) {
		return serviceaccount.NewService(deps).ServiceAccount(namespace, name)
	})
}

func (a *App) GetStatefulSet(clusterID, namespace, name string) (*StatefulSetDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "StatefulSet", namespace, name, func() (*StatefulSetDetails, error) {
		return statefulset.NewService(deps).StatefulSet(namespace, name)
	})
}

func (a *App) GetStorageClass(clusterID, name string) (*StorageClassDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "StorageClass", name, func() (*StorageClassDetails, error) {
		return storageclass.NewService(deps).StorageClass(name)
	})
}

func (a *App) GetTLSRoute(clusterID, namespace, name string) (*TLSRouteDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "TLSRoute", namespace, name, func() (*TLSRouteDetails, error) {
		return gatewayapi.NewService(deps).TLSRoute(namespace, name)
	})
}

func (a *App) GetValidatingWebhookConfiguration(clusterID, name string) (*ValidatingWebhookConfigurationDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "ValidatingWebhookConfiguration", name, func() (*ValidatingWebhookConfigurationDetails, error) {
		return admission.NewService(deps).ValidatingWebhookConfiguration(name)
	})
}
