// Code generated by genappbindings; DO NOT EDIT.

package backend

import (
	"context"
	"github.com/luxury-yacht/app/backend/resources/admission"
	"github.com/luxury-yacht/app/backend/resources/backendtlspolicy"
	"github.com/luxury-yacht/app/backend/resources/clusterrole"
	"github.com/luxury-yacht/app/backend/resources/clusterrolebinding"
	"github.com/luxury-yacht/app/backend/resources/configmap"
	"github.com/luxury-yacht/app/backend/resources/cronjob"
	"github.com/luxury-yacht/app/backend/resources/daemonset"
	"github.com/luxury-yacht/app/backend/resources/deployment"
	"github.com/luxury-yacht/app/backend/resources/endpointslice"
	"github.com/luxury-yacht/app/backend/resources/events"
	"github.com/luxury-yacht/app/backend/resources/gateway"
	"github.com/luxury-yacht/app/backend/resources/gatewayclass"
	"github.com/luxury-yacht/app/backend/resources/grpcroute"
	"github.com/luxury-yacht/app/backend/resources/hpa"
	"github.com/luxury-yacht/app/backend/resources/httproute"
	"github.com/luxury-yacht/app/backend/resources/ingress"
	"github.com/luxury-yacht/app/backend/resources/ingressclass"
	"github.com/luxury-yacht/app/backend/resources/job"
	"github.com/luxury-yacht/app/backend/resources/limitrange"
	"github.com/luxury-yacht/app/backend/resources/listenerset"
	"github.com/luxury-yacht/app/backend/resources/namespaces"
	"github.com/luxury-yacht/app/backend/resources/networkpolicy"
	"github.com/luxury-yacht/app/backend/resources/nodes"
	"github.com/luxury-yacht/app/backend/resources/persistentvolume"
	"github.com/luxury-yacht/app/backend/resources/persistentvolumeclaim"
	"github.com/luxury-yacht/app/backend/resources/poddisruptionbudget"
	"github.com/luxury-yacht/app/backend/resources/referencegrant"
	"github.com/luxury-yacht/app/backend/resources/replicaset"
	"github.com/luxury-yacht/app/backend/resources/resourcequota"
	"github.com/luxury-yacht/app/backend/resources/role"
	"github.com/luxury-yacht/app/backend/resources/rolebinding"
	"github.com/luxury-yacht/app/backend/resources/secret"
	"github.com/luxury-yacht/app/backend/resources/service"
	"github.com/luxury-yacht/app/backend/resources/serviceaccount"
	"github.com/luxury-yacht/app/backend/resources/statefulset"
	"github.com/luxury-yacht/app/backend/resources/storageclass"
	"github.com/luxury-yacht/app/backend/resources/tlsroute"
	"github.com/luxury-yacht/app/backend/resources/types"
)

// BindingModelAnchor keeps object-detail DTOs reachable by the Wails generator
// without exporting the backend-only Get<Kind> wrappers to TypeScript.
//
//wails:internal
type BindingModelAnchor struct {
	BackendTLSPolicy               *backendtlspolicy.BackendTLSPolicyDetails
	ClusterRole                    *clusterrole.ClusterRoleDetails
	ClusterRoleBinding             *clusterrolebinding.ClusterRoleBindingDetails
	ConfigMap                      *configmap.ConfigMapDetails
	CronJob                        *cronjob.CronJobDetails
	DaemonSet                      *daemonset.DaemonSetDetails
	Deployment                     *deployment.DeploymentDetails
	EndpointSlice                  *endpointslice.EndpointSliceDetails
	Event                          *events.EventDetails
	GRPCRoute                      *types.GRPCRouteDetails
	Gateway                        *gateway.GatewayDetails
	GatewayClass                   *gatewayclass.GatewayClassDetails
	HTTPRoute                      *types.HTTPRouteDetails
	HorizontalPodAutoscaler        *hpa.HorizontalPodAutoscalerDetails
	Ingress                        *ingress.IngressDetails
	IngressClass                   *ingressclass.IngressClassDetails
	Job                            *job.JobDetails
	LimitRange                     *limitrange.LimitRangeDetails
	ListenerSet                    *listenerset.ListenerSetDetails
	MutatingWebhookConfiguration   *admission.MutatingWebhookConfigurationDetails
	Namespace                      *namespaces.NamespaceDetails
	NetworkPolicy                  *networkpolicy.NetworkPolicyDetails
	Node                           *nodes.NodeDetails
	PersistentVolume               *persistentvolume.PersistentVolumeDetails
	PersistentVolumeClaim          *persistentvolumeclaim.PersistentVolumeClaimDetails
	PodDisruptionBudget            *poddisruptionbudget.PodDisruptionBudgetDetails
	ReferenceGrant                 *referencegrant.ReferenceGrantDetails
	ReplicaSet                     *replicaset.ReplicaSetDetails
	ResourceQuota                  *resourcequota.ResourceQuotaDetails
	Role                           *role.RoleDetails
	RoleBinding                    *rolebinding.RoleBindingDetails
	Secret                         *secret.SecretDetails
	Service                        *service.ServiceDetails
	ServiceAccount                 *serviceaccount.ServiceAccountDetails
	StatefulSet                    *statefulset.StatefulSetDetails
	StorageClass                   *storageclass.StorageClassDetails
	TLSRoute                       *types.TLSRouteDetails
	ValidatingWebhookConfiguration *admission.ValidatingWebhookConfigurationDetails
	CustomResourceDefinition       *CustomResourceDefinitionDetails
	HelmRelease                    *HelmReleaseDetails
	Pod                            *PodDetailInfo
}

//wails:internal
func (a *App) BindingModelAnchor() BindingModelAnchor { return BindingModelAnchor{} }

//wails:ignore
func (a *App) GetBackendTLSPolicy(clusterID, namespace, name string) (*backendtlspolicy.BackendTLSPolicyDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "BackendTLSPolicy", namespace, name, func(ctx context.Context) (*backendtlspolicy.BackendTLSPolicyDetails, error) {
		return backendtlspolicy.NewService(deps).BackendTLSPolicy(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetClusterRole(clusterID, name string) (*clusterrole.ClusterRoleDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "ClusterRole", name, func(ctx context.Context) (*clusterrole.ClusterRoleDetails, error) {
		return clusterrole.NewService(deps).ClusterRole(ctx, name)
	})
}

//wails:ignore
func (a *App) GetClusterRoleBinding(clusterID, name string) (*clusterrolebinding.ClusterRoleBindingDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "ClusterRoleBinding", name, func(ctx context.Context) (*clusterrolebinding.ClusterRoleBindingDetails, error) {
		return clusterrolebinding.NewService(deps).ClusterRoleBinding(ctx, name)
	})
}

//wails:ignore
func (a *App) GetConfigMap(clusterID, namespace, name string) (*configmap.ConfigMapDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ConfigMap", namespace, name, func(ctx context.Context) (*configmap.ConfigMapDetails, error) {
		return configmap.NewService(deps).ConfigMap(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetCronJob(clusterID, namespace, name string) (*cronjob.CronJobDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "CronJob", namespace, name, func(ctx context.Context) (*cronjob.CronJobDetails, error) {
		return cronjob.NewService(deps).CronJob(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetDaemonSet(clusterID, namespace, name string) (*daemonset.DaemonSetDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "DaemonSet", namespace, name, func(ctx context.Context) (*daemonset.DaemonSetDetails, error) {
		return daemonset.NewService(deps).DaemonSet(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetDeployment(clusterID, namespace, name string) (*deployment.DeploymentDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Deployment", namespace, name, func(ctx context.Context) (*deployment.DeploymentDetails, error) {
		return deployment.NewService(deps).Deployment(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetEndpointSlice(clusterID, namespace, name string) (*endpointslice.EndpointSliceDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "EndpointSlice", namespace, name, func(ctx context.Context) (*endpointslice.EndpointSliceDetails, error) {
		return endpointslice.NewService(deps).EndpointSlice(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetEvent(clusterID, namespace, name string) (*events.EventDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Event", namespace, name, func(ctx context.Context) (*events.EventDetails, error) {
		return events.NewService(deps).Event(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetGRPCRoute(clusterID, namespace, name string) (*types.GRPCRouteDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "GRPCRoute", namespace, name, func(ctx context.Context) (*types.GRPCRouteDetails, error) {
		return grpcroute.NewService(deps).GRPCRoute(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetGateway(clusterID, namespace, name string) (*gateway.GatewayDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Gateway", namespace, name, func(ctx context.Context) (*gateway.GatewayDetails, error) {
		return gateway.NewService(deps).Gateway(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetGatewayClass(clusterID, name string) (*gatewayclass.GatewayClassDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "GatewayClass", name, func(ctx context.Context) (*gatewayclass.GatewayClassDetails, error) {
		return gatewayclass.NewService(deps).GatewayClass(ctx, name)
	})
}

//wails:ignore
func (a *App) GetHTTPRoute(clusterID, namespace, name string) (*types.HTTPRouteDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "HTTPRoute", namespace, name, func(ctx context.Context) (*types.HTTPRouteDetails, error) {
		return httproute.NewService(deps).HTTPRoute(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetHorizontalPodAutoscaler(clusterID, namespace, name string) (*hpa.HorizontalPodAutoscalerDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "HPA", namespace, name, func(ctx context.Context) (*hpa.HorizontalPodAutoscalerDetails, error) {
		return hpa.NewService(deps).HorizontalPodAutoscaler(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetIngress(clusterID, namespace, name string) (*ingress.IngressDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Ingress", namespace, name, func(ctx context.Context) (*ingress.IngressDetails, error) {
		return ingress.NewService(deps).Ingress(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetIngressClass(clusterID, name string) (*ingressclass.IngressClassDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "IngressClass", name, func(ctx context.Context) (*ingressclass.IngressClassDetails, error) {
		return ingressclass.NewService(deps).IngressClass(ctx, name)
	})
}

//wails:ignore
func (a *App) GetJob(clusterID, namespace, name string) (*job.JobDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Job", namespace, name, func(ctx context.Context) (*job.JobDetails, error) {
		return job.NewService(deps).Job(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetLimitRange(clusterID, namespace, name string) (*limitrange.LimitRangeDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "LimitRange", namespace, name, func(ctx context.Context) (*limitrange.LimitRangeDetails, error) {
		return limitrange.NewService(deps).LimitRange(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetListenerSet(clusterID, namespace, name string) (*listenerset.ListenerSetDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ListenerSet", namespace, name, func(ctx context.Context) (*listenerset.ListenerSetDetails, error) {
		return listenerset.NewService(deps).ListenerSet(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetMutatingWebhookConfiguration(clusterID, name string) (*admission.MutatingWebhookConfigurationDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "MutatingWebhookConfiguration", name, func(ctx context.Context) (*admission.MutatingWebhookConfigurationDetails, error) {
		return admission.NewService(deps).MutatingWebhookConfiguration(ctx, name)
	})
}

//wails:ignore
func (a *App) GetNamespace(clusterID, name string) (*namespaces.NamespaceDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "Namespace", name, func(ctx context.Context) (*namespaces.NamespaceDetails, error) {
		return namespaces.NewService(deps).Namespace(ctx, name)
	})
}

//wails:ignore
func (a *App) GetNetworkPolicy(clusterID, namespace, name string) (*networkpolicy.NetworkPolicyDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "NetworkPolicy", namespace, name, func(ctx context.Context) (*networkpolicy.NetworkPolicyDetails, error) {
		return networkpolicy.NewService(deps).NetworkPolicy(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetNode(clusterID, name string) (*nodes.NodeDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "Node", name, func(ctx context.Context) (*nodes.NodeDetails, error) {
		return nodes.NewService(deps).Node(ctx, name)
	})
}

//wails:ignore
func (a *App) GetPersistentVolume(clusterID, name string) (*persistentvolume.PersistentVolumeDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "PersistentVolume", name, func(ctx context.Context) (*persistentvolume.PersistentVolumeDetails, error) {
		return persistentvolume.NewService(deps).PersistentVolume(ctx, name)
	})
}

//wails:ignore
func (a *App) GetPersistentVolumeClaim(clusterID, namespace, name string) (*persistentvolumeclaim.PersistentVolumeClaimDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "PVC", namespace, name, func(ctx context.Context) (*persistentvolumeclaim.PersistentVolumeClaimDetails, error) {
		return persistentvolumeclaim.NewService(deps).PersistentVolumeClaim(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetPodDisruptionBudget(clusterID, namespace, name string) (*poddisruptionbudget.PodDisruptionBudgetDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "PodDisruptionBudget", namespace, name, func(ctx context.Context) (*poddisruptionbudget.PodDisruptionBudgetDetails, error) {
		return poddisruptionbudget.NewService(deps).PodDisruptionBudget(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetReferenceGrant(clusterID, namespace, name string) (*referencegrant.ReferenceGrantDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ReferenceGrant", namespace, name, func(ctx context.Context) (*referencegrant.ReferenceGrantDetails, error) {
		return referencegrant.NewService(deps).ReferenceGrant(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetReplicaSet(clusterID, namespace, name string) (*replicaset.ReplicaSetDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ReplicaSet", namespace, name, func(ctx context.Context) (*replicaset.ReplicaSetDetails, error) {
		return replicaset.NewService(deps).ReplicaSet(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetResourceQuota(clusterID, namespace, name string) (*resourcequota.ResourceQuotaDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ResourceQuota", namespace, name, func(ctx context.Context) (*resourcequota.ResourceQuotaDetails, error) {
		return resourcequota.NewService(deps).ResourceQuota(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetRole(clusterID, namespace, name string) (*role.RoleDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Role", namespace, name, func(ctx context.Context) (*role.RoleDetails, error) {
		return role.NewService(deps).Role(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetRoleBinding(clusterID, namespace, name string) (*rolebinding.RoleBindingDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "RoleBinding", namespace, name, func(ctx context.Context) (*rolebinding.RoleBindingDetails, error) {
		return rolebinding.NewService(deps).RoleBinding(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetSecret(clusterID, namespace, name string) (*secret.SecretDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Secret", namespace, name, func(ctx context.Context) (*secret.SecretDetails, error) {
		return secret.NewService(deps).Secret(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetService(clusterID, namespace, name string) (*service.ServiceDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "Service", namespace, name, func(ctx context.Context) (*service.ServiceDetails, error) {
		return service.NewService(deps).GetService(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetServiceAccount(clusterID, namespace, name string) (*serviceaccount.ServiceAccountDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "ServiceAccount", namespace, name, func(ctx context.Context) (*serviceaccount.ServiceAccountDetails, error) {
		return serviceaccount.NewService(deps).ServiceAccount(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetStatefulSet(clusterID, namespace, name string) (*statefulset.StatefulSetDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "StatefulSet", namespace, name, func(ctx context.Context) (*statefulset.StatefulSetDetails, error) {
		return statefulset.NewService(deps).StatefulSet(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetStorageClass(clusterID, name string) (*storageclass.StorageClassDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "StorageClass", name, func(ctx context.Context) (*storageclass.StorageClassDetails, error) {
		return storageclass.NewService(deps).StorageClass(ctx, name)
	})
}

//wails:ignore
func (a *App) GetTLSRoute(clusterID, namespace, name string) (*types.TLSRouteDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchNamespacedResource(a, deps, selectionKey, "TLSRoute", namespace, name, func(ctx context.Context) (*types.TLSRouteDetails, error) {
		return tlsroute.NewService(deps).TLSRoute(ctx, namespace, name)
	})
}

//wails:ignore
func (a *App) GetValidatingWebhookConfiguration(clusterID, name string) (*admission.ValidatingWebhookConfigurationDetails, error) {
	deps, selectionKey, err := a.resolveClusterDependencies(clusterID)
	if err != nil {
		return nil, err
	}
	return FetchClusterResource(a, deps, selectionKey, "ValidatingWebhookConfiguration", name, func(ctx context.Context) (*admission.ValidatingWebhookConfigurationDetails, error) {
		return admission.NewService(deps).ValidatingWebhookConfiguration(ctx, name)
	})
}
