// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyObjectYaml(arg1) {
  return window['go']['backend']['App']['ApplyObjectYaml'](arg1);
}

export function ClearLogs() {
  return window['go']['backend']['App']['ClearLogs']();
}

export function CloseShellSession(arg1) {
  return window['go']['backend']['App']['CloseShellSession'](arg1);
}

export function CordonNode(arg1) {
  return window['go']['backend']['App']['CordonNode'](arg1);
}

export function CreateVersionedEndpoint(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateVersionedEndpoint'](arg1, arg2, arg3, arg4);
}

export function CtxOrBackground() {
  return window['go']['backend']['App']['CtxOrBackground']();
}

export function DeleteHelmRelease(arg1, arg2) {
  return window['go']['backend']['App']['DeleteHelmRelease'](arg1, arg2);
}

export function DeleteNode(arg1) {
  return window['go']['backend']['App']['DeleteNode'](arg1);
}

export function DeletePod(arg1, arg2) {
  return window['go']['backend']['App']['DeletePod'](arg1, arg2);
}

export function DeleteResource(arg1, arg2, arg3) {
  return window['go']['backend']['App']['DeleteResource'](arg1, arg2, arg3);
}

export function DrainNode(arg1, arg2) {
  return window['go']['backend']['App']['DrainNode'](arg1, arg2);
}

export function EvaluateCapabilities(arg1) {
  return window['go']['backend']['App']['EvaluateCapabilities'](arg1);
}

export function ForceDeleteNode(arg1) {
  return window['go']['backend']['App']['ForceDeleteNode'](arg1);
}

export function GetAppInfo() {
  return window['go']['backend']['App']['GetAppInfo']();
}

export function GetAppSettings() {
  return window['go']['backend']['App']['GetAppSettings']();
}

export function GetCatalogDiagnostics() {
  return window['go']['backend']['App']['GetCatalogDiagnostics']();
}

export function GetClusterRole(arg1) {
  return window['go']['backend']['App']['GetClusterRole'](arg1);
}

export function GetClusterRoleBinding(arg1) {
  return window['go']['backend']['App']['GetClusterRoleBinding'](arg1);
}

export function GetConfigMap(arg1, arg2) {
  return window['go']['backend']['App']['GetConfigMap'](arg1, arg2);
}

export function GetCronJob(arg1, arg2) {
  return window['go']['backend']['App']['GetCronJob'](arg1, arg2);
}

export function GetCustomResourceDefinition(arg1) {
  return window['go']['backend']['App']['GetCustomResourceDefinition'](arg1);
}

export function GetDaemonSet(arg1, arg2) {
  return window['go']['backend']['App']['GetDaemonSet'](arg1, arg2);
}

export function GetDeployment(arg1, arg2) {
  return window['go']['backend']['App']['GetDeployment'](arg1, arg2);
}

export function GetEndpointSlice(arg1, arg2) {
  return window['go']['backend']['App']['GetEndpointSlice'](arg1, arg2);
}

export function GetHelmManifest(arg1, arg2) {
  return window['go']['backend']['App']['GetHelmManifest'](arg1, arg2);
}

export function GetHelmReleaseDetails(arg1, arg2) {
  return window['go']['backend']['App']['GetHelmReleaseDetails'](arg1, arg2);
}

export function GetHelmValues(arg1, arg2) {
  return window['go']['backend']['App']['GetHelmValues'](arg1, arg2);
}

export function GetHorizontalPodAutoscaler(arg1, arg2) {
  return window['go']['backend']['App']['GetHorizontalPodAutoscaler'](arg1, arg2);
}

export function GetIngress(arg1, arg2) {
  return window['go']['backend']['App']['GetIngress'](arg1, arg2);
}

export function GetIngressClass(arg1) {
  return window['go']['backend']['App']['GetIngressClass'](arg1);
}

export function GetJob(arg1, arg2) {
  return window['go']['backend']['App']['GetJob'](arg1, arg2);
}

export function GetKubeconfigs() {
  return window['go']['backend']['App']['GetKubeconfigs']();
}

export function GetLimitRange(arg1, arg2) {
  return window['go']['backend']['App']['GetLimitRange'](arg1, arg2);
}

export function GetLogs() {
  return window['go']['backend']['App']['GetLogs']();
}

export function GetMutatingWebhookConfiguration(arg1) {
  return window['go']['backend']['App']['GetMutatingWebhookConfiguration'](arg1);
}

export function GetNamespace(arg1) {
  return window['go']['backend']['App']['GetNamespace'](arg1);
}

export function GetNetworkPolicy(arg1, arg2) {
  return window['go']['backend']['App']['GetNetworkPolicy'](arg1, arg2);
}

export function GetNode(arg1) {
  return window['go']['backend']['App']['GetNode'](arg1);
}

export function GetObjectYAML(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetObjectYAML'](arg1, arg2, arg3);
}

export function GetPersistentVolume(arg1) {
  return window['go']['backend']['App']['GetPersistentVolume'](arg1);
}

export function GetPersistentVolumeClaim(arg1, arg2) {
  return window['go']['backend']['App']['GetPersistentVolumeClaim'](arg1, arg2);
}

export function GetPod(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetPod'](arg1, arg2, arg3);
}

export function GetPodContainers(arg1, arg2) {
  return window['go']['backend']['App']['GetPodContainers'](arg1, arg2);
}

export function GetPodDisruptionBudget(arg1, arg2) {
  return window['go']['backend']['App']['GetPodDisruptionBudget'](arg1, arg2);
}

export function GetRefreshBaseURL() {
  return window['go']['backend']['App']['GetRefreshBaseURL']();
}

export function GetResourceQuota(arg1, arg2) {
  return window['go']['backend']['App']['GetResourceQuota'](arg1, arg2);
}

export function GetRole(arg1, arg2) {
  return window['go']['backend']['App']['GetRole'](arg1, arg2);
}

export function GetRoleBinding(arg1, arg2) {
  return window['go']['backend']['App']['GetRoleBinding'](arg1, arg2);
}

export function GetSecret(arg1, arg2) {
  return window['go']['backend']['App']['GetSecret'](arg1, arg2);
}

export function GetSelectedKubeconfig() {
  return window['go']['backend']['App']['GetSelectedKubeconfig']();
}

export function GetService(arg1, arg2) {
  return window['go']['backend']['App']['GetService'](arg1, arg2);
}

export function GetServiceAccount(arg1, arg2) {
  return window['go']['backend']['App']['GetServiceAccount'](arg1, arg2);
}

export function GetStatefulSet(arg1, arg2) {
  return window['go']['backend']['App']['GetStatefulSet'](arg1, arg2);
}

export function GetStorageClass(arg1) {
  return window['go']['backend']['App']['GetStorageClass'](arg1);
}

export function GetThemeInfo() {
  return window['go']['backend']['App']['GetThemeInfo']();
}

export function GetValidatingWebhookConfiguration(arg1) {
  return window['go']['backend']['App']['GetValidatingWebhookConfiguration'](arg1);
}

export function GetWorkloads(arg1, arg2) {
  return window['go']['backend']['App']['GetWorkloads'](arg1, arg2);
}

export function InitializeForTesting(arg1, arg2) {
  return window['go']['backend']['App']['InitializeForTesting'](arg1, arg2);
}

export function IsDiagnosticsPanelVisible() {
  return window['go']['backend']['App']['IsDiagnosticsPanelVisible']();
}

export function IsLogsPanelVisible() {
  return window['go']['backend']['App']['IsLogsPanelVisible']();
}

export function IsSidebarVisible() {
  return window['go']['backend']['App']['IsSidebarVisible']();
}

export function LoadWindowSettings() {
  return window['go']['backend']['App']['LoadWindowSettings']();
}

export function LogFetcher(arg1) {
  return window['go']['backend']['App']['LogFetcher'](arg1);
}

export function ResizeShellSession(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ResizeShellSession'](arg1, arg2, arg3);
}

export function RestartWorkload(arg1, arg2, arg3) {
  return window['go']['backend']['App']['RestartWorkload'](arg1, arg2, arg3);
}

export function SaveWindowSettings() {
  return window['go']['backend']['App']['SaveWindowSettings']();
}

export function ScaleWorkload(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ScaleWorkload'](arg1, arg2, arg3, arg4);
}

export function SendShellInput(arg1, arg2) {
  return window['go']['backend']['App']['SendShellInput'](arg1, arg2);
}

export function SetApiExtensionsClient(arg1) {
  return window['go']['backend']['App']['SetApiExtensionsClient'](arg1);
}

export function SetDynamicClient(arg1) {
  return window['go']['backend']['App']['SetDynamicClient'](arg1);
}

export function SetKubeconfig(arg1) {
  return window['go']['backend']['App']['SetKubeconfig'](arg1);
}

export function SetLogsPanelVisible(arg1) {
  return window['go']['backend']['App']['SetLogsPanelVisible'](arg1);
}

export function SetMetricsClient(arg1) {
  return window['go']['backend']['App']['SetMetricsClient'](arg1);
}

export function SetRestConfig(arg1) {
  return window['go']['backend']['App']['SetRestConfig'](arg1);
}

export function SetSidebarVisible(arg1) {
  return window['go']['backend']['App']['SetSidebarVisible'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['backend']['App']['SetTheme'](arg1);
}

export function SetUseShortResourceNames(arg1) {
  return window['go']['backend']['App']['SetUseShortResourceNames'](arg1);
}

export function ShowAbout() {
  return window['go']['backend']['App']['ShowAbout']();
}

export function ShowSettings() {
  return window['go']['backend']['App']['ShowSettings']();
}

export function StartShellSession(arg1) {
  return window['go']['backend']['App']['StartShellSession'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function ToggleDiagnosticsPanel() {
  return window['go']['backend']['App']['ToggleDiagnosticsPanel']();
}

export function ToggleLogsPanel() {
  return window['go']['backend']['App']['ToggleLogsPanel']();
}

export function ToggleSidebar() {
  return window['go']['backend']['App']['ToggleSidebar']();
}

export function UncordonNode(arg1) {
  return window['go']['backend']['App']['UncordonNode'](arg1);
}

export function UpdateMenu() {
  return window['go']['backend']['App']['UpdateMenu']();
}

export function ValidateObjectYaml(arg1) {
  return window['go']['backend']['App']['ValidateObjectYaml'](arg1);
}
