// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';
import {types} from '../models';
import {capabilities} from '../models';
import {json} from '../models';
import {kubernetes} from '../models';
import {clientset} from '../models';
import {dynamic} from '../models';
import {versioned} from '../models';
import {rest} from '../models';

export function ApplyObjectYaml(arg1:string,arg2:backend.ObjectYAMLMutationRequest):Promise<backend.ObjectYAMLMutationResponse>;

export function ClearAppState():Promise<void>;

export function ClearGridTablePersistence():Promise<number>;

export function ClearLogs():Promise<void>;

export function CloseShellSession(arg1:string):Promise<void>;

export function CordonNode(arg1:string,arg2:string):Promise<void>;

export function CreateVersionedEndpoint(arg1:string,arg2:string,arg3:any,arg4:string):Promise<backend.VersionedResponse>;

export function CtxOrBackground():Promise<context.Context>;

export function DeleteGridTablePersistence(arg1:string):Promise<void>;

export function DeleteGridTablePersistenceEntries(arg1:Array<string>):Promise<void>;

export function DeleteHelmRelease(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteNode(arg1:string,arg2:string):Promise<void>;

export function DeletePod(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteResource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DrainNode(arg1:string,arg2:string,arg3:types.DrainNodeOptions):Promise<void>;

export function EvaluateCapabilities(arg1:Array<capabilities.CheckRequest>):Promise<Array<capabilities.CheckResult>>;

export function ForceDeleteNode(arg1:string,arg2:string):Promise<void>;

export function GetAllClusterAuthStates():Promise<Record<string, Record<string, any>>>;

export function GetAppInfo():Promise<backend.AppInfo>;

export function GetAppSettings():Promise<types.AppSettings>;

export function GetCatalogDiagnostics():Promise<backend.CatalogDiagnostics>;

export function GetClusterAuthState(arg1:string):Promise<string|string>;

export function GetClusterPortForwardCount(arg1:string):Promise<number>;

export function GetClusterRole(arg1:string,arg2:string):Promise<types.ClusterRoleDetails>;

export function GetClusterRoleBinding(arg1:string,arg2:string):Promise<types.ClusterRoleBindingDetails>;

export function GetClusterTabOrder():Promise<Array<string>>;

export function GetConfigMap(arg1:string,arg2:string,arg3:string):Promise<types.ConfigMapDetails>;

export function GetCronJob(arg1:string,arg2:string,arg3:string):Promise<types.CronJobDetails>;

export function GetCustomResourceDefinition(arg1:string,arg2:string):Promise<types.CustomResourceDefinitionDetails>;

export function GetDaemonSet(arg1:string,arg2:string,arg3:string):Promise<types.DaemonSetDetails>;

export function GetDeployment(arg1:string,arg2:string,arg3:string):Promise<types.DeploymentDetails>;

export function GetEndpointSlice(arg1:string,arg2:string,arg3:string):Promise<types.EndpointSliceDetails>;

export function GetGridTablePersistence():Promise<Record<string, json.RawMessage>>;

export function GetHelmManifest(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetHelmReleaseDetails(arg1:string,arg2:string,arg3:string):Promise<types.HelmReleaseDetails>;

export function GetHelmValues(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetHorizontalPodAutoscaler(arg1:string,arg2:string,arg3:string):Promise<types.HorizontalPodAutoscalerDetails>;

export function GetIngress(arg1:string,arg2:string,arg3:string):Promise<types.IngressDetails>;

export function GetIngressClass(arg1:string,arg2:string):Promise<types.IngressClassDetails>;

export function GetJob(arg1:string,arg2:string,arg3:string):Promise<types.JobDetails>;

export function GetKubeconfigSearchPaths():Promise<Array<string>>;

export function GetKubeconfigs():Promise<Array<types.KubeconfigInfo>>;

export function GetLimitRange(arg1:string,arg2:string,arg3:string):Promise<types.LimitRangeDetails>;

export function GetLogs():Promise<Array<backend.LogEntry>>;

export function GetMutatingWebhookConfiguration(arg1:string,arg2:string):Promise<types.MutatingWebhookConfigurationDetails>;

export function GetNamespace(arg1:string,arg2:string):Promise<types.NamespaceDetails>;

export function GetNetworkPolicy(arg1:string,arg2:string,arg3:string):Promise<types.NetworkPolicyDetails>;

export function GetNode(arg1:string,arg2:string):Promise<types.NodeDetails>;

export function GetObjectYAML(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetPersistentVolume(arg1:string,arg2:string):Promise<types.PersistentVolumeDetails>;

export function GetPersistentVolumeClaim(arg1:string,arg2:string,arg3:string):Promise<types.PersistentVolumeClaimDetails>;

export function GetPod(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<types.PodDetailInfo>;

export function GetPodContainers(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetPodDisruptionBudget(arg1:string,arg2:string,arg3:string):Promise<types.PodDisruptionBudgetDetails>;

export function GetRefreshBaseURL():Promise<string>;

export function GetReplicaSet(arg1:string,arg2:string,arg3:string):Promise<types.ReplicaSetDetails>;

export function GetResourceQuota(arg1:string,arg2:string,arg3:string):Promise<types.ResourceQuotaDetails>;

export function GetRole(arg1:string,arg2:string,arg3:string):Promise<types.RoleDetails>;

export function GetRoleBinding(arg1:string,arg2:string,arg3:string):Promise<types.RoleBindingDetails>;

export function GetSecret(arg1:string,arg2:string,arg3:string):Promise<types.SecretDetails>;

export function GetSelectedKubeconfigs():Promise<Array<string>>;

export function GetService(arg1:string,arg2:string,arg3:string):Promise<types.ServiceDetails>;

export function GetServiceAccount(arg1:string,arg2:string,arg3:string):Promise<types.ServiceAccountDetails>;

export function GetStatefulSet(arg1:string,arg2:string,arg3:string):Promise<types.StatefulSetDetails>;

export function GetStorageClass(arg1:string,arg2:string):Promise<types.StorageClassDetails>;

export function GetTargetPorts(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<backend.ContainerPortInfo>>;

export function GetThemeInfo():Promise<types.ThemeInfo>;

export function GetValidatingWebhookConfiguration(arg1:string,arg2:string):Promise<types.ValidatingWebhookConfigurationDetails>;

export function GetWorkloads(arg1:string,arg2:string,arg3:string):Promise<backend.VersionedResponse>;

export function GetZoomLevel():Promise<number>;

export function InitializeForTesting(arg1:context.Context,arg2:kubernetes.Interface):Promise<void>;

export function IsDiagnosticsPanelVisible():Promise<boolean>;

export function IsLogsPanelVisible():Promise<boolean>;

export function IsSidebarVisible():Promise<boolean>;

export function ListPortForwards():Promise<Array<backend.PortForwardSession>>;

export function LoadWindowSettings():Promise<types.WindowSettings>;

export function LogFetcher(arg1:string,arg2:types.LogFetchRequest):Promise<types.LogFetchResponse>;

export function LogFrontend(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenKubeconfigSearchPathDialog():Promise<string>;

export function ResizeShellSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartWorkload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RetryAuth():Promise<void>;

export function RetryClusterAuth(arg1:string):Promise<void>;

export function SaveWindowSettings():Promise<void>;

export function ScaleWorkload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function SendShellInput(arg1:string,arg2:string):Promise<void>;

export function SetApiExtensionsClient(arg1:clientset.Interface):Promise<void>;

export function SetAutoRefreshEnabled(arg1:boolean):Promise<void>;

export function SetBackgroundRefreshEnabled(arg1:boolean):Promise<void>;

export function SetClusterTabOrder(arg1:Array<string>):Promise<void>;

export function SetDynamicClient(arg1:dynamic.Interface):Promise<void>;

export function SetGridTablePersistence(arg1:string,arg2:json.RawMessage):Promise<void>;

export function SetGridTablePersistenceMode(arg1:string):Promise<void>;

export function SetKubeconfig(arg1:string):Promise<void>;

export function SetKubeconfigSearchPaths(arg1:Array<string>):Promise<void>;

export function SetLogsPanelVisible(arg1:boolean):Promise<void>;

export function SetMetricsClient(arg1:versioned.Clientset):Promise<void>;

export function SetRestConfig(arg1:rest.Config):Promise<void>;

export function SetSelectedKubeconfigs(arg1:Array<string>):Promise<void>;

export function SetSidebarVisible(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetUseShortResourceNames(arg1:boolean):Promise<void>;

export function SetZoomLevel(arg1:number):Promise<void>;

export function ShowAbout():Promise<void>;

export function ShowSettings():Promise<void>;

export function StartPortForward(arg1:string,arg2:backend.PortForwardRequest):Promise<string>;

export function StartShellSession(arg1:string,arg2:types.ShellSessionRequest):Promise<types.ShellSession>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopClusterPortForwards(arg1:string):Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function SuspendCronJob(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ToggleDiagnosticsPanel():Promise<void>;

export function ToggleLogsPanel():Promise<void>;

export function ToggleObjectDiff():Promise<void>;

export function ToggleSidebar():Promise<void>;

export function TriggerCronJob(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UncordonNode(arg1:string,arg2:string):Promise<void>;

export function UpdateMenu():Promise<void>;

export function ValidateObjectYaml(arg1:string,arg2:backend.ObjectYAMLMutationRequest):Promise<backend.ObjectYAMLMutationResponse>;

export function ValidatePortForwardURL(arg1:string):Promise<boolean|string>;
