// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyObjectYaml(arg1, arg2) {
  return window['go']['backend']['App']['ApplyObjectYaml'](arg1, arg2);
}

export function ClearAppState() {
  return window['go']['backend']['App']['ClearAppState']();
}

export function ClearGridTablePersistence() {
  return window['go']['backend']['App']['ClearGridTablePersistence']();
}

export function ClearLogs() {
  return window['go']['backend']['App']['ClearLogs']();
}

export function CloseShellSession(arg1) {
  return window['go']['backend']['App']['CloseShellSession'](arg1);
}

export function CordonNode(arg1, arg2) {
  return window['go']['backend']['App']['CordonNode'](arg1, arg2);
}

export function CreateVersionedEndpoint(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateVersionedEndpoint'](arg1, arg2, arg3, arg4);
}

export function CtxOrBackground() {
  return window['go']['backend']['App']['CtxOrBackground']();
}

export function DeleteGridTablePersistence(arg1) {
  return window['go']['backend']['App']['DeleteGridTablePersistence'](arg1);
}

export function DeleteGridTablePersistenceEntries(arg1) {
  return window['go']['backend']['App']['DeleteGridTablePersistenceEntries'](arg1);
}

export function DeleteHelmRelease(arg1, arg2, arg3) {
  return window['go']['backend']['App']['DeleteHelmRelease'](arg1, arg2, arg3);
}

export function DeleteNode(arg1, arg2) {
  return window['go']['backend']['App']['DeleteNode'](arg1, arg2);
}

export function DeletePod(arg1, arg2, arg3) {
  return window['go']['backend']['App']['DeletePod'](arg1, arg2, arg3);
}

export function DeleteResource(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['DeleteResource'](arg1, arg2, arg3, arg4);
}

export function DrainNode(arg1, arg2, arg3) {
  return window['go']['backend']['App']['DrainNode'](arg1, arg2, arg3);
}

export function EvaluateCapabilities(arg1) {
  return window['go']['backend']['App']['EvaluateCapabilities'](arg1);
}

export function ForceDeleteNode(arg1, arg2) {
  return window['go']['backend']['App']['ForceDeleteNode'](arg1, arg2);
}

export function GetAllClusterAuthStates() {
  return window['go']['backend']['App']['GetAllClusterAuthStates']();
}

export function GetAppInfo() {
  return window['go']['backend']['App']['GetAppInfo']();
}

export function GetAppSettings() {
  return window['go']['backend']['App']['GetAppSettings']();
}

export function GetCatalogDiagnostics() {
  return window['go']['backend']['App']['GetCatalogDiagnostics']();
}

export function GetClusterAuthState(arg1) {
  return window['go']['backend']['App']['GetClusterAuthState'](arg1);
}

export function GetClusterPortForwardCount(arg1) {
  return window['go']['backend']['App']['GetClusterPortForwardCount'](arg1);
}

export function GetClusterRole(arg1, arg2) {
  return window['go']['backend']['App']['GetClusterRole'](arg1, arg2);
}

export function GetClusterRoleBinding(arg1, arg2) {
  return window['go']['backend']['App']['GetClusterRoleBinding'](arg1, arg2);
}

export function GetClusterTabOrder() {
  return window['go']['backend']['App']['GetClusterTabOrder']();
}

export function GetConfigMap(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetConfigMap'](arg1, arg2, arg3);
}

export function GetCronJob(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetCronJob'](arg1, arg2, arg3);
}

export function GetCustomResourceDefinition(arg1, arg2) {
  return window['go']['backend']['App']['GetCustomResourceDefinition'](arg1, arg2);
}

export function GetDaemonSet(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetDaemonSet'](arg1, arg2, arg3);
}

export function GetDeployment(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetDeployment'](arg1, arg2, arg3);
}

export function GetEndpointSlice(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetEndpointSlice'](arg1, arg2, arg3);
}

export function GetGridTablePersistence() {
  return window['go']['backend']['App']['GetGridTablePersistence']();
}

export function GetHelmManifest(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetHelmManifest'](arg1, arg2, arg3);
}

export function GetHelmReleaseDetails(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetHelmReleaseDetails'](arg1, arg2, arg3);
}

export function GetHelmValues(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetHelmValues'](arg1, arg2, arg3);
}

export function GetHorizontalPodAutoscaler(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetHorizontalPodAutoscaler'](arg1, arg2, arg3);
}

export function GetIngress(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetIngress'](arg1, arg2, arg3);
}

export function GetIngressClass(arg1, arg2) {
  return window['go']['backend']['App']['GetIngressClass'](arg1, arg2);
}

export function GetJob(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetJob'](arg1, arg2, arg3);
}

export function GetKubeconfigSearchPaths() {
  return window['go']['backend']['App']['GetKubeconfigSearchPaths']();
}

export function GetKubeconfigs() {
  return window['go']['backend']['App']['GetKubeconfigs']();
}

export function GetLimitRange(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetLimitRange'](arg1, arg2, arg3);
}

export function GetLogs() {
  return window['go']['backend']['App']['GetLogs']();
}

export function GetMutatingWebhookConfiguration(arg1, arg2) {
  return window['go']['backend']['App']['GetMutatingWebhookConfiguration'](arg1, arg2);
}

export function GetNamespace(arg1, arg2) {
  return window['go']['backend']['App']['GetNamespace'](arg1, arg2);
}

export function GetNetworkPolicy(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetNetworkPolicy'](arg1, arg2, arg3);
}

export function GetNode(arg1, arg2) {
  return window['go']['backend']['App']['GetNode'](arg1, arg2);
}

export function GetObjectYAML(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['GetObjectYAML'](arg1, arg2, arg3, arg4);
}

export function GetPersistentVolume(arg1, arg2) {
  return window['go']['backend']['App']['GetPersistentVolume'](arg1, arg2);
}

export function GetPersistentVolumeClaim(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetPersistentVolumeClaim'](arg1, arg2, arg3);
}

export function GetPod(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['GetPod'](arg1, arg2, arg3, arg4);
}

export function GetPodContainers(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetPodContainers'](arg1, arg2, arg3);
}

export function GetPodDisruptionBudget(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetPodDisruptionBudget'](arg1, arg2, arg3);
}

export function GetRefreshBaseURL() {
  return window['go']['backend']['App']['GetRefreshBaseURL']();
}

export function GetReplicaSet(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetReplicaSet'](arg1, arg2, arg3);
}

export function GetResourceQuota(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetResourceQuota'](arg1, arg2, arg3);
}

export function GetRole(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetRole'](arg1, arg2, arg3);
}

export function GetRoleBinding(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetRoleBinding'](arg1, arg2, arg3);
}

export function GetSecret(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetSecret'](arg1, arg2, arg3);
}

export function GetSelectedKubeconfigs() {
  return window['go']['backend']['App']['GetSelectedKubeconfigs']();
}

export function GetService(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetService'](arg1, arg2, arg3);
}

export function GetServiceAccount(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetServiceAccount'](arg1, arg2, arg3);
}

export function GetStatefulSet(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetStatefulSet'](arg1, arg2, arg3);
}

export function GetStorageClass(arg1, arg2) {
  return window['go']['backend']['App']['GetStorageClass'](arg1, arg2);
}

export function GetTargetPorts(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['GetTargetPorts'](arg1, arg2, arg3, arg4);
}

export function GetThemeInfo() {
  return window['go']['backend']['App']['GetThemeInfo']();
}

export function GetValidatingWebhookConfiguration(arg1, arg2) {
  return window['go']['backend']['App']['GetValidatingWebhookConfiguration'](arg1, arg2);
}

export function GetWorkloads(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetWorkloads'](arg1, arg2, arg3);
}

export function GetZoomLevel() {
  return window['go']['backend']['App']['GetZoomLevel']();
}

export function InitializeForTesting(arg1, arg2) {
  return window['go']['backend']['App']['InitializeForTesting'](arg1, arg2);
}

export function IsDiagnosticsPanelVisible() {
  return window['go']['backend']['App']['IsDiagnosticsPanelVisible']();
}

export function IsLogsPanelVisible() {
  return window['go']['backend']['App']['IsLogsPanelVisible']();
}

export function IsPortForwardsPanelVisible() {
  return window['go']['backend']['App']['IsPortForwardsPanelVisible']();
}

export function IsSidebarVisible() {
  return window['go']['backend']['App']['IsSidebarVisible']();
}

export function IsWorkloadHPAManaged(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['IsWorkloadHPAManaged'](arg1, arg2, arg3, arg4);
}

export function ListPortForwards() {
  return window['go']['backend']['App']['ListPortForwards']();
}

export function LoadWindowSettings() {
  return window['go']['backend']['App']['LoadWindowSettings']();
}

export function LogFetcher(arg1, arg2) {
  return window['go']['backend']['App']['LogFetcher'](arg1, arg2);
}

export function LogFrontend(arg1, arg2, arg3) {
  return window['go']['backend']['App']['LogFrontend'](arg1, arg2, arg3);
}

export function OpenKubeconfigSearchPathDialog() {
  return window['go']['backend']['App']['OpenKubeconfigSearchPathDialog']();
}

export function ResizeShellSession(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ResizeShellSession'](arg1, arg2, arg3);
}

export function RestartWorkload(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['RestartWorkload'](arg1, arg2, arg3, arg4);
}

export function RetryAuth() {
  return window['go']['backend']['App']['RetryAuth']();
}

export function RetryClusterAuth(arg1) {
  return window['go']['backend']['App']['RetryClusterAuth'](arg1);
}

export function SaveWindowSettings() {
  return window['go']['backend']['App']['SaveWindowSettings']();
}

export function ScaleWorkload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['ScaleWorkload'](arg1, arg2, arg3, arg4, arg5);
}

export function SendShellInput(arg1, arg2) {
  return window['go']['backend']['App']['SendShellInput'](arg1, arg2);
}

export function SetApiExtensionsClient(arg1) {
  return window['go']['backend']['App']['SetApiExtensionsClient'](arg1);
}

export function SetAutoRefreshEnabled(arg1) {
  return window['go']['backend']['App']['SetAutoRefreshEnabled'](arg1);
}

export function SetBackgroundRefreshEnabled(arg1) {
  return window['go']['backend']['App']['SetBackgroundRefreshEnabled'](arg1);
}

export function SetClusterTabOrder(arg1) {
  return window['go']['backend']['App']['SetClusterTabOrder'](arg1);
}

export function SetDynamicClient(arg1) {
  return window['go']['backend']['App']['SetDynamicClient'](arg1);
}

export function SetGridTablePersistence(arg1, arg2) {
  return window['go']['backend']['App']['SetGridTablePersistence'](arg1, arg2);
}

export function SetGridTablePersistenceMode(arg1) {
  return window['go']['backend']['App']['SetGridTablePersistenceMode'](arg1);
}

export function SetKubeconfig(arg1) {
  return window['go']['backend']['App']['SetKubeconfig'](arg1);
}

export function SetKubeconfigSearchPaths(arg1) {
  return window['go']['backend']['App']['SetKubeconfigSearchPaths'](arg1);
}

export function SetLogsPanelVisible(arg1) {
  return window['go']['backend']['App']['SetLogsPanelVisible'](arg1);
}

export function SetMetricsClient(arg1) {
  return window['go']['backend']['App']['SetMetricsClient'](arg1);
}

export function SetPaletteTint(arg1, arg2) {
  return window['go']['backend']['App']['SetPaletteTint'](arg1, arg2);
}

export function SetPortForwardsPanelVisible(arg1) {
  return window['go']['backend']['App']['SetPortForwardsPanelVisible'](arg1);
}

export function SetRestConfig(arg1) {
  return window['go']['backend']['App']['SetRestConfig'](arg1);
}

export function SetSelectedKubeconfigs(arg1) {
  return window['go']['backend']['App']['SetSelectedKubeconfigs'](arg1);
}

export function SetSidebarVisible(arg1) {
  return window['go']['backend']['App']['SetSidebarVisible'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['backend']['App']['SetTheme'](arg1);
}

export function SetUseShortResourceNames(arg1) {
  return window['go']['backend']['App']['SetUseShortResourceNames'](arg1);
}

export function SetZoomLevel(arg1) {
  return window['go']['backend']['App']['SetZoomLevel'](arg1);
}

export function ShowAbout() {
  return window['go']['backend']['App']['ShowAbout']();
}

export function ShowSettings() {
  return window['go']['backend']['App']['ShowSettings']();
}

export function StartPortForward(arg1, arg2) {
  return window['go']['backend']['App']['StartPortForward'](arg1, arg2);
}

export function StartShellSession(arg1, arg2) {
  return window['go']['backend']['App']['StartShellSession'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function StopClusterPortForwards(arg1) {
  return window['go']['backend']['App']['StopClusterPortForwards'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['backend']['App']['StopPortForward'](arg1);
}

export function SuspendCronJob(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['SuspendCronJob'](arg1, arg2, arg3, arg4);
}

export function ToggleDiagnosticsPanel() {
  return window['go']['backend']['App']['ToggleDiagnosticsPanel']();
}

export function ToggleLogsPanel() {
  return window['go']['backend']['App']['ToggleLogsPanel']();
}

export function ToggleObjectDiff() {
  return window['go']['backend']['App']['ToggleObjectDiff']();
}

export function TogglePortForwardsPanel() {
  return window['go']['backend']['App']['TogglePortForwardsPanel']();
}

export function ToggleSidebar() {
  return window['go']['backend']['App']['ToggleSidebar']();
}

export function TriggerCronJob(arg1, arg2, arg3) {
  return window['go']['backend']['App']['TriggerCronJob'](arg1, arg2, arg3);
}

export function UncordonNode(arg1, arg2) {
  return window['go']['backend']['App']['UncordonNode'](arg1, arg2);
}

export function UpdateMenu() {
  return window['go']['backend']['App']['UpdateMenu']();
}

export function ValidateObjectYaml(arg1, arg2) {
  return window['go']['backend']['App']['ValidateObjectYaml'](arg1, arg2);
}

export function ValidatePortForwardURL(arg1) {
  return window['go']['backend']['App']['ValidatePortForwardURL'](arg1);
}
