package genrefreshcontracts

import (
	"bytes"
	"fmt"
	"path"
	"reflect"
	"sort"
	"strings"
	"unicode"
)

const generatedHeader = `// Code generated by genrefreshcontracts; DO NOT EDIT.
//
// Backend Go DTOs are the source of truth. Regenerate with: go generate ./backend

`

type renderer struct {
	names       map[reflect.Type]string
	typesByName map[string]reflect.Type
	enums       map[reflect.Type]enumSpec
	definitions map[reflect.Type]struct{}
}

// Render generates the TypeScript representation of the backend-owned refresh
// HTTP and stream wire contracts.
func Render() ([]byte, error) {
	r := &renderer{
		names:       make(map[reflect.Type]string),
		typesByName: make(map[string]reflect.Type),
		enums:       make(map[reflect.Type]enumSpec),
		definitions: make(map[reflect.Type]struct{}),
	}

	for _, spec := range contractEnums {
		if err := r.registerName(spec.name, spec.typeOf); err != nil {
			return nil, err
		}
		r.enums[spec.typeOf] = spec
	}
	for _, spec := range contractTypes {
		if err := r.registerName(spec.name, spec.typeOf); err != nil {
			return nil, err
		}
		if indirect(spec.typeOf).Kind() == reflect.Struct {
			r.definitions[indirect(spec.typeOf)] = struct{}{}
		}
	}

	if err := r.discoverDefinitions(); err != nil {
		return nil, err
	}

	var out bytes.Buffer
	out.WriteString(generatedHeader)
	for _, spec := range contractEnums {
		r.renderEnum(&out, spec)
	}

	definitionTypes := make([]reflect.Type, 0, len(r.definitions))
	for typeOf := range r.definitions {
		definitionTypes = append(definitionTypes, typeOf)
	}
	sort.Slice(definitionTypes, func(i, j int) bool {
		return r.names[definitionTypes[i]] < r.names[definitionTypes[j]]
	})
	for _, typeOf := range definitionTypes {
		if err := r.renderInterface(&out, typeOf); err != nil {
			return nil, err
		}
	}
	if err := r.renderSnapshotInterface(&out); err != nil {
		return nil, err
	}

	for _, alias := range contractAliases {
		fmt.Fprintf(&out, "export type %s = %s;\n\n", alias.name, alias.target)
	}

	out.WriteString("export const REFRESH_DOMAINS = [\n")
	for _, domain := range contractDomains {
		fmt.Fprintf(&out, "  %s,\n", quoteString(domain.domain))
	}
	out.WriteString("] as const;\n\n")
	out.WriteString("export type RefreshDomain = (typeof REFRESH_DOMAINS)[number];\n\n")
	r.renderSnapshotAssertion(&out)
	r.renderTelemetryAssertion(&out)
	out.WriteString("export interface BackendDomainPayloadMap {\n")
	for _, domain := range contractDomains {
		if domain.frontendOwned {
			continue
		}
		fmt.Fprintf(&out, "  %s: %s;\n", quoteProperty(domain.domain), domain.payload)
	}
	out.WriteString("}\n")

	return out.Bytes(), nil
}

func (r *renderer) renderEnum(out *bytes.Buffer, spec enumSpec) {
	values := make([]string, 0, len(spec.values))
	for _, value := range spec.values {
		values = append(values, quoteString(value))
	}
	if spec.valuesName != "" {
		inline := fmt.Sprintf("export const %s = [%s] as const;", spec.valuesName, strings.Join(values, ", "))
		if len(inline) <= 100 {
			fmt.Fprintf(out, "%s\n\n", inline)
		} else {
			fmt.Fprintf(out, "export const %s = [\n", spec.valuesName)
			for _, value := range values {
				fmt.Fprintf(out, "  %s,\n", value)
			}
			out.WriteString("] as const;\n\n")
		}
		fmt.Fprintf(out, "export type %s = (typeof %s)[number];\n\n", spec.name, spec.valuesName)
		return
	}
	union := strings.Join(values, " | ")
	inline := fmt.Sprintf("export type %s = %s;", spec.name, union)
	if len(inline) <= 100 {
		fmt.Fprintf(out, "%s\n\n", inline)
		return
	}
	if len("  "+union+";") <= 100 {
		fmt.Fprintf(out, "export type %s =\n  %s;\n\n", spec.name, union)
		return
	}
	fmt.Fprintf(out, "export type %s =\n", spec.name)
	for index, value := range values {
		terminator := ";"
		if index+1 < len(values) {
			terminator = ""
		}
		fmt.Fprintf(out, "  | %s%s\n", value, terminator)
	}
	out.WriteByte('\n')
}

func (r *renderer) renderSnapshotInterface(out *bytes.Buffer) error {
	fields, err := r.renderFields(snapshotEnvelopeType, false)
	if err != nil {
		return err
	}
	out.WriteString("export interface RefreshSnapshot<TPayload> {\n")
	for _, field := range fields {
		typeScript := field.typeScript
		switch field.name {
		case "domain":
			typeScript = "RefreshDomain"
		case "payload":
			typeScript = "TPayload"
		}
		fmt.Fprintf(out, "  %s%s: %s;\n", quoteProperty(field.name), optionalMarker(field.optional), typeScript)
	}
	out.WriteString("}\n\n")
	return nil
}

func (r *renderer) renderSnapshotAssertion(out *bytes.Buffer) {
	out.WriteString(`const isRefreshRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

export function assertRefreshSnapshotEnvelope<TPayload>(
  value: unknown,
  expectedDomain: RefreshDomain
): asserts value is RefreshSnapshot<TPayload> {
  const invalid = (reason: string): Error =>
    new Error(` + "`" + `Invalid refresh snapshot for ${expectedDomain}: ${reason}` + "`" + `);
  if (!isRefreshRecord(value)) {
    throw invalid('expected an object');
  }
  if (value.domain !== expectedDomain) {
    throw invalid(` + "`" + `received domain ${String(value.domain)}` + "`" + `);
  }
  for (const field of ['version', 'generatedAt', 'sequence'] as const) {
    if (typeof value[field] !== 'number' || !Number.isFinite(value[field])) {
      throw invalid(` + "`" + `invalid ${field}` + "`" + `);
    }
  }
  if (typeof value.checksum !== 'string') {
    throw invalid('invalid checksum');
  }
  if (!('payload' in value)) {
    throw invalid('missing payload');
  }
  if (!isRefreshRecord(value.stats)) {
    throw invalid('invalid stats');
  }
  for (const field of ['itemCount', 'buildDurationMs'] as const) {
    if (typeof value.stats[field] !== 'number' || !Number.isFinite(value.stats[field])) {
      throw invalid(` + "`" + `invalid stats.${field}` + "`" + `);
    }
  }
}

`)
}

func (r *renderer) renderTelemetryAssertion(out *bytes.Buffer) {
	out.WriteString(`export function assertTelemetrySummary(value: unknown): asserts value is TelemetrySummary {
  const invalid = (reason: string): Error => new Error(` + "`" + `Invalid telemetry summary: ${reason}` + "`" + `);
  if (!isRefreshRecord(value)) {
    throw invalid('expected an object');
  }
  if (!Array.isArray(value.snapshots)) {
    throw invalid('invalid snapshots');
  }
  if (!Array.isArray(value.streams)) {
    throw invalid('invalid streams');
  }
  if (!isRefreshRecord(value.metrics)) {
    throw invalid('invalid metrics');
  }
  for (const field of [
    'lastCollected',
    'lastDurationMs',
    'consecutiveFailures',
    'successCount',
    'failureCount',
  ] as const) {
    if (typeof value.metrics[field] !== 'number' || !Number.isFinite(value.metrics[field])) {
      throw invalid(` + "`" + `invalid metrics.${field}` + "`" + `);
    }
  }
  if (typeof value.metrics.active !== 'boolean') {
    throw invalid('invalid metrics.active');
  }
  if (!isRefreshRecord(value.connection)) {
    throw invalid('invalid connection');
  }
  for (const field of [
    'retryAttempts',
    'retrySuccesses',
    'retryExhausted',
    'transportRebuilds',
  ] as const) {
    if (typeof value.connection[field] !== 'number' || !Number.isFinite(value.connection[field])) {
      throw invalid(` + "`" + `invalid connection.${field}` + "`" + `);
    }
  }
}

`)
}

func (r *renderer) registerName(name string, typeOf reflect.Type) error {
	typeOf = indirect(typeOf)
	if existing, ok := r.names[typeOf]; ok && existing != name {
		return fmt.Errorf("refresh contract Go type %s is registered as both %s and %s", typeOf, existing, name)
	}
	if existing, ok := r.typesByName[name]; ok && existing != typeOf {
		return fmt.Errorf("refresh contract TypeScript name %s maps to both %s and %s", name, existing, typeOf)
	}
	r.names[typeOf] = name
	r.typesByName[name] = typeOf
	return nil
}

func (r *renderer) discoverDefinitions() error {
	for {
		before := len(r.definitions)
		current := make([]reflect.Type, 0, before)
		for typeOf := range r.definitions {
			current = append(current, typeOf)
		}
		for _, typeOf := range current {
			if err := r.walkStruct(typeOf); err != nil {
				return err
			}
		}
		if len(r.definitions) == before {
			return nil
		}
	}
}

func (r *renderer) walkStruct(typeOf reflect.Type) error {
	for index := 0; index < typeOf.NumField(); index++ {
		field := typeOf.Field(index)
		name, _, skip := jsonField(field)
		if skip {
			continue
		}
		if field.Anonymous && name == "" {
			embedded := indirect(field.Type)
			if embedded.Kind() == reflect.Struct {
				if err := r.walkStruct(embedded); err != nil {
					return err
				}
				continue
			}
		}
		if err := r.walkType(field.Type); err != nil {
			return fmt.Errorf("%s.%s: %w", typeOf, field.Name, err)
		}
	}
	return nil
}

func (r *renderer) walkType(typeOf reflect.Type) error {
	typeOf = indirect(typeOf)
	if isSpecialType(typeOf) || r.enums[typeOf].name != "" {
		return nil
	}
	switch typeOf.Kind() {
	case reflect.Array, reflect.Slice:
		return r.walkType(typeOf.Elem())
	case reflect.Map:
		return r.walkType(typeOf.Elem())
	case reflect.Struct:
		if _, ok := r.names[typeOf]; !ok {
			name := automaticName(typeOf)
			if err := r.registerName(name, typeOf); err != nil {
				return err
			}
		}
		r.definitions[typeOf] = struct{}{}
		return nil
	case reflect.Bool, reflect.Float32, reflect.Float64,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Interface, reflect.String:
		return nil
	default:
		return fmt.Errorf("unsupported Go wire type %s", typeOf)
	}
}

func (r *renderer) renderInterface(out *bytes.Buffer, typeOf reflect.Type) error {
	name := r.names[typeOf]
	if name == "" {
		return fmt.Errorf("missing TypeScript name for %s", typeOf)
	}
	fmt.Fprintf(out, "export interface %s {\n", name)
	fields, err := r.renderFields(typeOf, false)
	if err != nil {
		return err
	}
	for _, field := range fields {
		fmt.Fprintf(out, "  %s%s: %s;\n", quoteProperty(field.name), optionalMarker(field.optional), field.typeScript)
	}
	out.WriteString("}\n\n")
	return nil
}

type renderedField struct {
	name       string
	typeScript string
	optional   bool
}

func (r *renderer) renderFields(typeOf reflect.Type, inheritedOptional bool) ([]renderedField, error) {
	fields := make([]renderedField, 0, typeOf.NumField())
	for index := 0; index < typeOf.NumField(); index++ {
		field := typeOf.Field(index)
		name, optional, skip := jsonField(field)
		if skip {
			continue
		}
		if field.Anonymous && name == "" {
			embedded := indirect(field.Type)
			if embedded.Kind() != reflect.Struct {
				return nil, fmt.Errorf("cannot flatten non-struct embedded field %s.%s", typeOf, field.Name)
			}
			nested, err := r.renderFields(embedded, inheritedOptional || field.Type.Kind() == reflect.Pointer)
			if err != nil {
				return nil, err
			}
			fields = append(fields, nested...)
			continue
		}
		typeScript, err := r.typeScriptType(field.Type)
		if err != nil {
			return nil, fmt.Errorf("%s.%s: %w", typeOf, field.Name, err)
		}
		fields = append(fields, renderedField{
			name:       name,
			typeScript: typeScript,
			optional:   inheritedOptional || optional,
		})
	}
	return fields, nil
}

func (r *renderer) typeScriptType(typeOf reflect.Type) (string, error) {
	if typeOf.Kind() == reflect.Pointer {
		return r.typeScriptType(typeOf.Elem())
	}
	if special, ok := specialTypeScriptType(typeOf); ok {
		return special, nil
	}
	if enum, ok := r.enums[typeOf]; ok {
		return enum.name, nil
	}
	if name, ok := r.names[typeOf]; ok && typeOf.Kind() == reflect.Struct {
		return name, nil
	}
	switch typeOf.Kind() {
	case reflect.Bool:
		return "boolean", nil
	case reflect.Float32, reflect.Float64,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "number", nil
	case reflect.String:
		return "string", nil
	case reflect.Interface:
		return "unknown", nil
	case reflect.Array, reflect.Slice:
		item, err := r.typeScriptType(typeOf.Elem())
		if err != nil {
			return "", err
		}
		return "Array<" + item + ">", nil
	case reflect.Map:
		if typeOf.Key().Kind() != reflect.String {
			return "", fmt.Errorf("map key %s is not representable as a TypeScript record key", typeOf.Key())
		}
		value, err := r.typeScriptType(typeOf.Elem())
		if err != nil {
			return "", err
		}
		return "Record<string, " + value + ">", nil
	case reflect.Struct:
		name := r.names[typeOf]
		if name == "" {
			return "", fmt.Errorf("missing discovered TypeScript name for %s", typeOf)
		}
		return name, nil
	default:
		return "", fmt.Errorf("unsupported Go wire type %s", typeOf)
	}
}

func jsonField(field reflect.StructField) (name string, optional bool, skip bool) {
	if !field.IsExported() {
		return "", false, true
	}
	tag := field.Tag.Get("json")
	parts := strings.Split(tag, ",")
	if len(parts) > 0 && parts[0] == "-" {
		return "", false, true
	}
	if len(parts) > 0 {
		name = parts[0]
	}
	for _, option := range parts[1:] {
		if option == "omitempty" || option == "omitzero" {
			optional = true
		}
	}
	if name == "" && !field.Anonymous {
		name = field.Name
	}
	return name, optional, false
}

func indirect(typeOf reflect.Type) reflect.Type {
	for typeOf.Kind() == reflect.Pointer {
		typeOf = typeOf.Elem()
	}
	return typeOf
}

func isSpecialType(typeOf reflect.Type) bool {
	_, ok := specialTypeScriptType(typeOf)
	return ok
}

func specialTypeScriptType(typeOf reflect.Type) (string, bool) {
	qualified := typeOf.PkgPath() + "." + typeOf.Name()
	switch qualified {
	case "time.Time", "k8s.io/apimachinery/pkg/apis/meta/v1.Time", "k8s.io/apimachinery/pkg/api/resource.Quantity":
		return "string", true
	case "github.com/luxury-yacht/app/backend/resourcemodel.ResourceFacts":
		return "Record<string, unknown>", true
	}
	return "", false
}

func automaticName(typeOf reflect.Type) string {
	packageName := path.Base(typeOf.PkgPath())
	return exportedIdentifier(packageName) + exportedIdentifier(typeOf.Name())
}

func exportedIdentifier(value string) string {
	var out []rune
	upperNext := true
	for _, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upperNext = true
			continue
		}
		if upperNext {
			r = unicode.ToUpper(r)
			upperNext = false
		}
		out = append(out, r)
	}
	return string(out)
}

func quoteProperty(name string) string {
	if name == "" {
		return name
	}
	for index, r := range name {
		if (unicode.IsLetter(r) || r == '_' || r == '$') || (index > 0 && unicode.IsDigit(r)) {
			continue
		}
		return quoteString(name)
	}
	return name
}

func quoteString(value string) string {
	escaped := strings.ReplaceAll(value, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `'`, `\'`)
	escaped = strings.ReplaceAll(escaped, "\n", `\n`)
	escaped = strings.ReplaceAll(escaped, "\r", `\r`)
	escaped = strings.ReplaceAll(escaped, "\t", `\t`)
	return `'` + escaped + `'`
}

func optionalMarker(optional bool) string {
	if optional {
		return "?"
	}
	return ""
}
