package genrefreshcontracts

import (
	"encoding/json"
	"os"
	"sort"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestRenderEmitsBackendOwnedRefreshContract(t *testing.T) {
	generated, err := Render()
	require.NoError(t, err)

	contract := string(generated)
	require.Contains(t, contract, "// Code generated by genrefreshcontracts; DO NOT EDIT.")
	require.Contains(t, contract, "export interface ResourceRef")
	require.Contains(t, contract, "export interface ResourceLifecycle")
	require.NotContains(t, contract, "export interface Resourcemodel")
	require.NotContains(t, contract, "export interface Streamrows")
	require.NotContains(t, contract, "export interface Objectcatalog")
	require.NotContains(t, contract, "export interface Objectmap")
	require.Contains(t, contract, "clusterId: string;")
	require.Contains(t, contract, "group: string;")
	require.Contains(t, contract, "version: string;")
	require.Contains(t, contract, "kind: string;")
	require.Contains(t, contract, "export type DrainEventPhase =")
	require.Contains(t, contract, "export type NamespaceScopeStatus =")
	require.Contains(t, contract, "scopeStatus?: NamespaceScopeStatus;")
	require.Contains(t, contract, "export type ResourceQueryAnchorReason =")
	require.Contains(t, contract, "reason?: ResourceQueryAnchorReason;")
	require.Contains(t, contract, "export type RefreshDomain =")
	require.Contains(t, contract, "export interface RefreshSnapshot<TPayload>")
	require.Contains(t, contract, "payload: TPayload;")
	require.Contains(t, contract, "export function assertRefreshSnapshotEnvelope<TPayload>(")
	require.Contains(t, contract, "export function assertTelemetrySummary(")
	require.Contains(t, contract, "export interface ContainerLogsStreamEventPayload")
	require.Contains(t, contract, "export interface ResourceStreamClientMessage")
	require.Contains(t, contract, "export interface ResourceStreamServerMessage")
	require.Contains(t, contract, "export const RESOURCE_STREAM_MESSAGE_TYPES = [")
	require.Contains(t, contract, "export const RESOURCE_STREAM_SIGNALS = [")
	require.Contains(t, contract, "export interface BackendDomainPayloadMap")
	require.Contains(t, contract, "'object-maintenance': NodeMaintenanceSnapshotPayload;")
}

func TestContractDomainsMatchAuthoredDomainInventory(t *testing.T) {
	contents, err := os.ReadFile("../../refresh/domain/refresh-domain-contract.json")
	require.NoError(t, err)

	var authored struct {
		DomainInventory map[string]json.RawMessage `json:"domainInventory"`
	}
	require.NoError(t, json.Unmarshal(contents, &authored))

	want := make([]string, 0, len(authored.DomainInventory))
	for domain := range authored.DomainInventory {
		want = append(want, domain)
	}
	got := make([]string, 0, len(contractDomains))
	frontendOwned := make([]string, 0, 1)
	for _, domain := range contractDomains {
		got = append(got, domain.domain)
		if domain.frontendOwned {
			frontendOwned = append(frontendOwned, domain.domain)
		}
	}
	sort.Strings(want)
	sort.Strings(got)
	require.Equal(t, want, got)
	require.Equal(t, []string{"container-logs"}, frontendOwned)
}
