// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export interface SecretDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "secretType": string;
    "data"?: { [_ in string]?: string } | null;
    "dataKeys": string[] | null;
    "dataCount": number;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
    "usedBy"?: types$0.ObjectRef[] | null;
}
