name: Install NSIS
description: Installs NSIS (Windows only)

inputs:
  nsis-version:
    description: "The version of NSIS to install"
    required: true

runs:
  using: composite
  steps:
    - name: Install NSIS
      shell: pwsh
      run: |
        & "$env:GITHUB_ACTION_PATH\install-nsis.ps1" `
          -NsisVersion "${{ inputs.nsis-version }}" `
          -AddToGitHubPath
