// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../../k8s.io/apimachinery/pkg/apis/meta/v1/models.js";

export interface CronJobDetails {
    /**
     * Basic information
     */
    "kind": string;
    "name": string;
    "namespace": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;
    "details": string;

    /**
     * Schedule information
     */
    "schedule": string;
    "suspend": boolean;
    "lastScheduleTime"?: v1$0.Time | null;
    "lastSuccessfulTime"?: v1$0.Time | null;
    "nextScheduleTime"?: string;
    "timeUntilNextSchedule"?: string;

    /**
     * Derived from owned Jobs — bounded by job-history retention. A
     * nil value can mean "never happened" OR "happened but the job
     * record has been garbage-collected"; the UI should hint at this.
     */
    "lastManualTime"?: v1$0.Time | null;
    "lastFailureTime"?: v1$0.Time | null;

    /**
     * Job configuration
     */
    "concurrencyPolicy": string;
    "startingDeadlineSeconds"?: number | null;
    "successfulJobsHistory": number;
    "failedJobsHistory": number;

    /**
     * Active jobs
     */
    "activeJobs"?: types$0.JobReference[] | null;

    /**
     * All owned jobs (completed, failed, running, etc.)
     */
    "jobs"?: types$0.JobSimpleInfo[] | null;

    /**
     * Job template information
     */
    "jobTemplate": types$0.JobTemplateDetails;

    /**
     * Labels and annotations
     */
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;

    /**
     * Related pods
     */
    "pods"?: types$0.PodSimpleInfo[] | null;
    "podMetricsSummary"?: types$0.PodMetricsSummary | null;
}
