// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ResourceQuotaDetails captures usage and limits for a namespace quota.
 */
export class ResourceQuotaDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "hard": { [_ in string]?: string };
    "used": { [_ in string]?: string };
    "scopes"?: string[];
    "scopeSelector"?: ScopeSelector | null;
    "usedPercentage"?: { [_ in string]?: number };
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };

    /** Creates a new ResourceQuotaDetails instance. */
    constructor($$source: Partial<ResourceQuotaDetails> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("hard" in $$source)) {
            this["hard"] = {};
        }
        if (!("used" in $$source)) {
            this["used"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceQuotaDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceQuotaDetails {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hard" in $$parsedSource) {
            $$parsedSource["hard"] = $$createField4_0($$parsedSource["hard"]);
        }
        if ("used" in $$parsedSource) {
            $$parsedSource["used"] = $$createField5_0($$parsedSource["used"]);
        }
        if ("scopes" in $$parsedSource) {
            $$parsedSource["scopes"] = $$createField6_0($$parsedSource["scopes"]);
        }
        if ("scopeSelector" in $$parsedSource) {
            $$parsedSource["scopeSelector"] = $$createField7_0($$parsedSource["scopeSelector"]);
        }
        if ("usedPercentage" in $$parsedSource) {
            $$parsedSource["usedPercentage"] = $$createField8_0($$parsedSource["usedPercentage"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField9_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField10_0($$parsedSource["annotations"]);
        }
        return new ResourceQuotaDetails($$parsedSource as Partial<ResourceQuotaDetails>);
    }
}

/**
 * ScopeSelector refines the resources controlled by a quota.
 */
export class ScopeSelector {
    "matchExpressions"?: ScopeSelectorRequirement[];

    /** Creates a new ScopeSelector instance. */
    constructor($$source: Partial<ScopeSelector> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScopeSelector instance from a string or object.
     */
    static createFrom($$source: any = {}): ScopeSelector {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matchExpressions" in $$parsedSource) {
            $$parsedSource["matchExpressions"] = $$createField0_0($$parsedSource["matchExpressions"]);
        }
        return new ScopeSelector($$parsedSource as Partial<ScopeSelector>);
    }
}

/**
 * ScopeSelectorRequirement mirrors corev1.ScopedResourceSelectorRequirement for transport.
 */
export class ScopeSelectorRequirement {
    "scopeName": string;
    "operator": string;
    "values"?: string[];

    /** Creates a new ScopeSelectorRequirement instance. */
    constructor($$source: Partial<ScopeSelectorRequirement> = {}) {
        if (!("scopeName" in $$source)) {
            this["scopeName"] = "";
        }
        if (!("operator" in $$source)) {
            this["operator"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScopeSelectorRequirement instance from a string or object.
     */
    static createFrom($$source: any = {}): ScopeSelectorRequirement {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField2_0($$parsedSource["values"]);
        }
        return new ScopeSelectorRequirement($$parsedSource as Partial<ScopeSelectorRequirement>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = ScopeSelector.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = ScopeSelectorRequirement.createFrom;
const $$createType6 = $Create.Array($$createType5);
