// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface IngressBackendDetails {
    "serviceName"?: string;
    "servicePort"?: string;
    "resource"?: string;
}

export interface IngressDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "ingressClassName"?: string | null;
    "rules": IngressRuleDetails[] | null;
    "tls"?: IngressTLSDetails[] | null;
    "loadBalancerStatus"?: string[] | null;
    "defaultBackend"?: IngressBackendDetails | null;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
}

export interface IngressPathDetails {
    "path": string;
    "pathType": string;
    "backend": IngressBackendDetails;
}

export interface IngressRuleDetails {
    "host"?: string;
    "paths": IngressPathDetails[] | null;
}

export interface IngressTLSDetails {
    "hosts": string[] | null;
    "secretName"?: string;
}
