name: Bug
description: File a bug/issue
title: '[BUG] <title>'
labels: ['Bug']
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this bug.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: Clearly describe what you are experiencing. If the bug is intermittent, please mention that.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How does the bug happen?
    validations:
      required: true

  - type: dropdown
    attributes:
      label: OS Type
      description: What type of operating system are you using?
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: input
    attributes:
      label: OS Version
      description: What version of the operating system are you using? If Linux, please include the distro name.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: OS Architecture
      description: What is the architecture of your operating system?
      options:
        - amd64 (x86_64)
        - arm64 (aarch64)
    validations:
      required: true

  - type: input
    attributes:
      label: App Version
      description: What version of the app are you using? You can find this in the "About" window.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Is there anything else you'd like to add to help clarify the issue? Screenshots, links, etc.
    validations:
      required: false
