name: Bug
description: File a bug/issue
title: '[BUG] <title>'
labels: ['Bug']
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this bug.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: Clearly describe what you are experiencing. If the bug is intermittent, please mention that.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How does the bug happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        example:
        OS, Version, Arch: Windows 11, 24H2, amd64
        App Version: v1.0.5
      value: |
        OS, Version, Arch:
        App Version:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Is there anything else you'd like to add?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
