// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * DataSourceInfo represents the data source of a PVC.
 */
export interface DataSourceInfo {
    "kind": string;
    "name": string;
}

export interface PersistentVolumeClaimDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;
    "volumeName"?: string;
    "storageClass"?: string | null;
    "accessModes": string[] | null;
    "capacity": string;
    "volumeMode": string;
    "selector"?: { [_ in string]?: string } | null;
    "dataSource"?: DataSourceInfo | null;
    "conditions"?: string[] | null;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
    "mountedBy"?: types$0.ObjectRef[] | null;
}
