// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resourcemodel$0 from "../../resourcemodel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * DataSourceInfo represents the data source of a PVC.
 */
export class DataSourceInfo {
    "kind": string;
    "name": string;

    /** Creates a new DataSourceInfo instance. */
    constructor($$source: Partial<DataSourceInfo> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSourceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DataSourceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DataSourceInfo($$parsedSource as Partial<DataSourceInfo>);
    }
}

export class PersistentVolumeClaimDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;
    "volumeName"?: string;
    "storageClass"?: string | null;
    "accessModes": string[];
    "capacity": string;
    "volumeMode": string;
    "selector"?: { [_ in string]?: string };
    "dataSource"?: DataSourceInfo | null;
    "conditions"?: string[];
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };
    "mountedBy"?: types$0.ObjectRef[];

    /** Creates a new PersistentVolumeClaimDetails instance. */
    constructor($$source: Partial<PersistentVolumeClaimDetails> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("accessModes" in $$source)) {
            this["accessModes"] = [];
        }
        if (!("capacity" in $$source)) {
            this["capacity"] = "";
        }
        if (!("volumeMode" in $$source)) {
            this["volumeMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PersistentVolumeClaimDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): PersistentVolumeClaimDetails {
        const $$createField10_0 = $$createType0;
        const $$createField13_0 = $$createType1;
        const $$createField14_0 = $$createType3;
        const $$createField15_0 = $$createType0;
        const $$createField16_0 = $$createType1;
        const $$createField17_0 = $$createType1;
        const $$createField18_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accessModes" in $$parsedSource) {
            $$parsedSource["accessModes"] = $$createField10_0($$parsedSource["accessModes"]);
        }
        if ("selector" in $$parsedSource) {
            $$parsedSource["selector"] = $$createField13_0($$parsedSource["selector"]);
        }
        if ("dataSource" in $$parsedSource) {
            $$parsedSource["dataSource"] = $$createField14_0($$parsedSource["dataSource"]);
        }
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField15_0($$parsedSource["conditions"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField16_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField17_0($$parsedSource["annotations"]);
        }
        if ("mountedBy" in $$parsedSource) {
            $$parsedSource["mountedBy"] = $$createField18_0($$parsedSource["mountedBy"]);
        }
        return new PersistentVolumeClaimDetails($$parsedSource as Partial<PersistentVolumeClaimDetails>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = DataSourceInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = resourcemodel$0.ResourceRef.createFrom;
const $$createType5 = $Create.Array($$createType4);
