// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../../k8s.io/apimachinery/pkg/apis/meta/v1/models.js";

/**
 * PodDisruptionBudgetDetails represents comprehensive PDB information.
 */
export class PodDisruptionBudgetDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "minAvailable"?: string | null;
    "maxUnavailable"?: string | null;
    "selector"?: { [_ in string]?: string };
    "currentHealthy": number;
    "desiredHealthy": number;
    "disruptionsAllowed": number;
    "expectedPods": number;
    "observedGeneration": number;
    "disruptedPods"?: { [_ in string]?: v1$0.Time };
    "conditions"?: string[];
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };

    /** Creates a new PodDisruptionBudgetDetails instance. */
    constructor($$source: Partial<PodDisruptionBudgetDetails> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("currentHealthy" in $$source)) {
            this["currentHealthy"] = 0;
        }
        if (!("desiredHealthy" in $$source)) {
            this["desiredHealthy"] = 0;
        }
        if (!("disruptionsAllowed" in $$source)) {
            this["disruptionsAllowed"] = 0;
        }
        if (!("expectedPods" in $$source)) {
            this["expectedPods"] = 0;
        }
        if (!("observedGeneration" in $$source)) {
            this["observedGeneration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PodDisruptionBudgetDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): PodDisruptionBudgetDetails {
        const $$createField6_0 = $$createType0;
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType2;
        const $$createField14_0 = $$createType0;
        const $$createField15_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("selector" in $$parsedSource) {
            $$parsedSource["selector"] = $$createField6_0($$parsedSource["selector"]);
        }
        if ("disruptedPods" in $$parsedSource) {
            $$parsedSource["disruptedPods"] = $$createField12_0($$parsedSource["disruptedPods"]);
        }
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField13_0($$parsedSource["conditions"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField14_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField15_0($$parsedSource["annotations"]);
        }
        return new PodDisruptionBudgetDetails($$parsedSource as Partial<PodDisruptionBudgetDetails>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($Create.Any);
