// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../../k8s.io/apimachinery/pkg/apis/meta/v1/models.js";

/**
 * PodDisruptionBudgetDetails represents comprehensive PDB information.
 */
export interface PodDisruptionBudgetDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "minAvailable"?: string | null;
    "maxUnavailable"?: string | null;
    "selector"?: { [_ in string]?: string } | null;
    "currentHealthy": number;
    "desiredHealthy": number;
    "disruptionsAllowed": number;
    "expectedPods": number;
    "observedGeneration": number;
    "disruptedPods"?: { [_ in string]?: v1$0.Time } | null;
    "conditions"?: string[] | null;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
}
