// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    NamespaceDiagnostics,
    PermissionQuery,
    PermissionResult,
    QueryPermissionsResponse
} from "./models.js";
