// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NamespaceDiagnostics reports per-namespace SSRR metadata for diagnostics.
 */
export interface NamespaceDiagnostics {
    /**
     * "clusterId|namespace" or "clusterId|__cluster__"
     */
    "key": string;
    "clusterId": string;

    /**
     * empty for cluster-scoped SSAR batch
     */
    "namespace"?: string;

    /**
     * "ssrr" or "ssar"
     */
    "method": string;

    /**
     * was the SSRR response incomplete?
     */
    "ssrrIncomplete": boolean;

    /**
     * number of rules in the SSRR response
     */
    "ssrrRuleCount": number;

    /**
     * checks that fell through to SSAR
     */
    "ssarFallbackCount": number;

    /**
     * total checks in this namespace batch
     */
    "checkCount": number;
}

/**
 * PermissionQuery is a single permission check request from the frontend.
 * 
 * Group and Version together MUST carry a fully-qualified GroupVersionKind
 * — this is what lets the RBAC gate distinguish between two CRDs that
 * share a Kind (e.g. DBInstance under different operators). The backend
 * rejects queries with an empty Version: the legacy kind-only resolver
 * was first-match-wins across colliding CRDs and has been retired.
 */
export interface PermissionQuery {
    "id": string;
    "clusterId": string;
    "group"?: string;
    "version"?: string;
    "resourceKind": string;
    "verb": string;
    "namespace"?: string;
    "subresource"?: string;
    "name"?: string;
}

/**
 * PermissionResult is the response for a single permission check.
 */
export interface PermissionResult {
    "id": string;
    "clusterId": string;
    "group"?: string;
    "version"?: string;
    "resourceKind": string;
    "verb": string;
    "namespace"?: string;
    "subresource"?: string;
    "name"?: string;
    "allowed": boolean;

    /**
     * Source indicates how the result was determined:
     * "ssrr" (matched cached rules), "ssar" (incomplete fallback or
     * cluster-scoped resource routed to SSAR), "denied" (no match,
     * complete rules), "error" (check failed).
     */
    "source": string;

    /**
     * Reason is the denial explanation from the K8s API (SSAR path)
     * or a human-readable "no matching rule" for SSRR denials. Populated
     * when Allowed is false and Source is not "error". Maps to
     * CheckResult.DeniedReason for SSAR results. Used by
     * ClusterResourcesManager to display "Insufficient permissions" or
     * a specific K8s reason string.
     */
    "reason"?: string;

    /**
     * Error is set only when the check itself failed (Source "error").
     * Not set for clean denials — use Reason for those.
     */
    "error"?: string;
}

/**
 * QueryPermissionsResponse wraps per-item results with batch-level
 * diagnostics metadata. The frontend reads Diagnostics to populate
 * the DiagnosticsPanel without fabricating metadata locally.
 */
export interface QueryPermissionsResponse {
    "results": PermissionResult[] | null;
    "diagnostics": NamespaceDiagnostics[] | null;
}
