// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * NamespaceDiagnostics reports per-namespace SSRR metadata for diagnostics.
 */
export class NamespaceDiagnostics {
    /**
     * "clusterId|namespace" or "clusterId|__cluster__"
     */
    "key": string;
    "clusterId": string;

    /**
     * empty for cluster-scoped SSAR batch
     */
    "namespace"?: string;

    /**
     * "ssrr" or "ssar"
     */
    "method": string;

    /**
     * was the SSRR response incomplete?
     */
    "ssrrIncomplete": boolean;

    /**
     * number of rules in the SSRR response
     */
    "ssrrRuleCount": number;

    /**
     * checks that fell through to SSAR
     */
    "ssarFallbackCount": number;

    /**
     * total checks in this namespace batch
     */
    "checkCount": number;

    /** Creates a new NamespaceDiagnostics instance. */
    constructor($$source: Partial<NamespaceDiagnostics> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("clusterId" in $$source)) {
            this["clusterId"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("ssrrIncomplete" in $$source)) {
            this["ssrrIncomplete"] = false;
        }
        if (!("ssrrRuleCount" in $$source)) {
            this["ssrrRuleCount"] = 0;
        }
        if (!("ssarFallbackCount" in $$source)) {
            this["ssarFallbackCount"] = 0;
        }
        if (!("checkCount" in $$source)) {
            this["checkCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NamespaceDiagnostics instance from a string or object.
     */
    static createFrom($$source: any = {}): NamespaceDiagnostics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NamespaceDiagnostics($$parsedSource as Partial<NamespaceDiagnostics>);
    }
}

/**
 * PermissionQuery is a single permission check request from the frontend.
 * 
 * Group and Version together MUST carry a fully-qualified GroupVersionKind
 * — this is what lets the RBAC gate distinguish between two CRDs that
 * share a Kind (e.g. DBInstance under different operators). The backend
 * rejects queries with an empty Version: the legacy kind-only resolver
 * was first-match-wins across colliding CRDs and has been retired.
 */
export class PermissionQuery {
    "id": string;
    "clusterId": string;
    "group"?: string;
    "version"?: string;
    "resourceKind": string;
    "verb": string;
    "namespace"?: string;
    "subresource"?: string;
    "name"?: string;

    /** Creates a new PermissionQuery instance. */
    constructor($$source: Partial<PermissionQuery> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("clusterId" in $$source)) {
            this["clusterId"] = "";
        }
        if (!("resourceKind" in $$source)) {
            this["resourceKind"] = "";
        }
        if (!("verb" in $$source)) {
            this["verb"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionQuery($$parsedSource as Partial<PermissionQuery>);
    }
}

/**
 * PermissionResult is the response for a single permission check.
 */
export class PermissionResult {
    "id": string;
    "clusterId": string;
    "group"?: string;
    "version"?: string;
    "resourceKind": string;
    "verb": string;
    "namespace"?: string;
    "subresource"?: string;
    "name"?: string;
    "allowed": boolean;

    /**
     * Source indicates how the result was determined:
     * "ssrr" (matched cached rules), "ssar" (incomplete fallback or
     * cluster-scoped resource routed to SSAR), "denied" (no match,
     * complete rules), "error" (check failed).
     */
    "source": string;

    /**
     * Reason is the denial explanation from the K8s API (SSAR path)
     * or a human-readable "no matching rule" for SSRR denials. Populated
     * when Allowed is false and Source is not "error". Maps to
     * CheckResult.DeniedReason for SSAR results. Used by
     * ClusterResourcesManager to display "Insufficient permissions" or
     * a specific K8s reason string.
     */
    "reason"?: string;

    /**
     * Error is set only when the check itself failed (Source "error").
     * Not set for clean denials — use Reason for those.
     */
    "error"?: string;

    /** Creates a new PermissionResult instance. */
    constructor($$source: Partial<PermissionResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("clusterId" in $$source)) {
            this["clusterId"] = "";
        }
        if (!("resourceKind" in $$source)) {
            this["resourceKind"] = "";
        }
        if (!("verb" in $$source)) {
            this["verb"] = "";
        }
        if (!("allowed" in $$source)) {
            this["allowed"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionResult($$parsedSource as Partial<PermissionResult>);
    }
}

/**
 * QueryPermissionsResponse wraps per-item results with batch-level
 * diagnostics metadata. The frontend reads Diagnostics to populate
 * the DiagnosticsPanel without fabricating metadata locally.
 */
export class QueryPermissionsResponse {
    "results": PermissionResult[];
    "diagnostics": NamespaceDiagnostics[];

    /** Creates a new QueryPermissionsResponse instance. */
    constructor($$source: Partial<QueryPermissionsResponse> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("diagnostics" in $$source)) {
            this["diagnostics"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryPermissionsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryPermissionsResponse {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField1_0($$parsedSource["diagnostics"]);
        }
        return new QueryPermissionsResponse($$parsedSource as Partial<QueryPermissionsResponse>);
    }
}

// Private type creation functions
const $$createType0 = PermissionResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = NamespaceDiagnostics.createFrom;
const $$createType3 = $Create.Array($$createType2);
