// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    MutatingWebhookConfigurationDetails,
    ValidatingWebhookConfigurationDetails,
    WebhookClientConfig,
    WebhookDetails,
    WebhookRule,
    WebhookSelector,
    WebhookSelectorExpression,
    WebhookService
} from "./models.js";
