// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MutatingWebhookConfigurationDetails captures detailed mutating webhook configuration information.
 */
export class MutatingWebhookConfigurationDetails {
    "kind": string;
    "name": string;
    "details": string;
    "webhooks": WebhookDetails[];
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };

    /** Creates a new MutatingWebhookConfigurationDetails instance. */
    constructor($$source: Partial<MutatingWebhookConfigurationDetails> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("webhooks" in $$source)) {
            this["webhooks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MutatingWebhookConfigurationDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): MutatingWebhookConfigurationDetails {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("webhooks" in $$parsedSource) {
            $$parsedSource["webhooks"] = $$createField3_0($$parsedSource["webhooks"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField4_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField5_0($$parsedSource["annotations"]);
        }
        return new MutatingWebhookConfigurationDetails($$parsedSource as Partial<MutatingWebhookConfigurationDetails>);
    }
}

/**
 * ValidatingWebhookConfigurationDetails captures detailed validating webhook configuration information.
 */
export class ValidatingWebhookConfigurationDetails {
    "kind": string;
    "name": string;
    "details": string;
    "webhooks": WebhookDetails[];
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };

    /** Creates a new ValidatingWebhookConfigurationDetails instance. */
    constructor($$source: Partial<ValidatingWebhookConfigurationDetails> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("webhooks" in $$source)) {
            this["webhooks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidatingWebhookConfigurationDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidatingWebhookConfigurationDetails {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("webhooks" in $$parsedSource) {
            $$parsedSource["webhooks"] = $$createField3_0($$parsedSource["webhooks"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField4_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField5_0($$parsedSource["annotations"]);
        }
        return new ValidatingWebhookConfigurationDetails($$parsedSource as Partial<ValidatingWebhookConfigurationDetails>);
    }
}

/**
 * WebhookClientConfig represents service or URL targeting.
 */
export class WebhookClientConfig {
    "service"?: WebhookService | null;
    "url"?: string;

    /** Creates a new WebhookClientConfig instance. */
    constructor($$source: Partial<WebhookClientConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookClientConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): WebhookClientConfig {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("service" in $$parsedSource) {
            $$parsedSource["service"] = $$createField0_0($$parsedSource["service"]);
        }
        return new WebhookClientConfig($$parsedSource as Partial<WebhookClientConfig>);
    }
}

/**
 * WebhookDetails describes a single webhook entry shared across mutating/validating types.
 */
export class WebhookDetails {
    "name": string;
    "clientConfig": WebhookClientConfig;
    "rules": WebhookRule[];
    "failurePolicy"?: string;
    "matchPolicy"?: string;
    "namespaceSelector"?: WebhookSelector | null;
    "objectSelector"?: WebhookSelector | null;
    "sideEffects"?: string;
    "timeoutSeconds"?: number | null;
    "admissionReviewVersions"?: string[];
    "reinvocationPolicy"?: string;

    /** Creates a new WebhookDetails instance. */
    constructor($$source: Partial<WebhookDetails> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("clientConfig" in $$source)) {
            this["clientConfig"] = (new WebhookClientConfig());
        }
        if (!("rules" in $$source)) {
            this["rules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): WebhookDetails {
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        const $$createField5_0 = $$createType9;
        const $$createField6_0 = $$createType9;
        const $$createField9_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clientConfig" in $$parsedSource) {
            $$parsedSource["clientConfig"] = $$createField1_0($$parsedSource["clientConfig"]);
        }
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField2_0($$parsedSource["rules"]);
        }
        if ("namespaceSelector" in $$parsedSource) {
            $$parsedSource["namespaceSelector"] = $$createField5_0($$parsedSource["namespaceSelector"]);
        }
        if ("objectSelector" in $$parsedSource) {
            $$parsedSource["objectSelector"] = $$createField6_0($$parsedSource["objectSelector"]);
        }
        if ("admissionReviewVersions" in $$parsedSource) {
            $$parsedSource["admissionReviewVersions"] = $$createField9_0($$parsedSource["admissionReviewVersions"]);
        }
        return new WebhookDetails($$parsedSource as Partial<WebhookDetails>);
    }
}

/**
 * WebhookRule captures rule matching for a webhook.
 */
export class WebhookRule {
    "apiGroups"?: string[];
    "apiVersions"?: string[];
    "resources"?: string[];
    "operations"?: string[];
    "scope"?: string;

    /** Creates a new WebhookRule instance. */
    constructor($$source: Partial<WebhookRule> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookRule instance from a string or object.
     */
    static createFrom($$source: any = {}): WebhookRule {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apiGroups" in $$parsedSource) {
            $$parsedSource["apiGroups"] = $$createField0_0($$parsedSource["apiGroups"]);
        }
        if ("apiVersions" in $$parsedSource) {
            $$parsedSource["apiVersions"] = $$createField1_0($$parsedSource["apiVersions"]);
        }
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField2_0($$parsedSource["resources"]);
        }
        if ("operations" in $$parsedSource) {
            $$parsedSource["operations"] = $$createField3_0($$parsedSource["operations"]);
        }
        return new WebhookRule($$parsedSource as Partial<WebhookRule>);
    }
}

/**
 * WebhookSelector holds selector criteria.
 */
export class WebhookSelector {
    "matchLabels"?: { [_ in string]?: string };
    "matchExpressions"?: WebhookSelectorExpression[];

    /** Creates a new WebhookSelector instance. */
    constructor($$source: Partial<WebhookSelector> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookSelector instance from a string or object.
     */
    static createFrom($$source: any = {}): WebhookSelector {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matchLabels" in $$parsedSource) {
            $$parsedSource["matchLabels"] = $$createField0_0($$parsedSource["matchLabels"]);
        }
        if ("matchExpressions" in $$parsedSource) {
            $$parsedSource["matchExpressions"] = $$createField1_0($$parsedSource["matchExpressions"]);
        }
        return new WebhookSelector($$parsedSource as Partial<WebhookSelector>);
    }
}

/**
 * WebhookSelectorExpression represents a label selector requirement.
 */
export class WebhookSelectorExpression {
    "key": string;
    "operator": string;
    "values"?: string[];

    /** Creates a new WebhookSelectorExpression instance. */
    constructor($$source: Partial<WebhookSelectorExpression> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("operator" in $$source)) {
            this["operator"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookSelectorExpression instance from a string or object.
     */
    static createFrom($$source: any = {}): WebhookSelectorExpression {
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField2_0($$parsedSource["values"]);
        }
        return new WebhookSelectorExpression($$parsedSource as Partial<WebhookSelectorExpression>);
    }
}

/**
 * WebhookService references a Kubernetes service target.
 */
export class WebhookService {
    "namespace": string;
    "name": string;
    "path"?: string | null;
    "port"?: number | null;

    /** Creates a new WebhookService instance. */
    constructor($$source: Partial<WebhookService> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebhookService instance from a string or object.
     */
    static createFrom($$source: any = {}): WebhookService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebhookService($$parsedSource as Partial<WebhookService>);
    }
}

// Private type creation functions
const $$createType0 = WebhookDetails.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = WebhookService.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = WebhookClientConfig.createFrom;
const $$createType6 = WebhookRule.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = WebhookSelector.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = WebhookSelectorExpression.createFrom;
const $$createType12 = $Create.Array($$createType11);
