// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export class ClusterRoleBindingDetails {
    "kind": string;
    "name": string;
    "details": string;
    "roleRef": types$0.RoleRef;
    "subjects": types$0.Subject[];
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };

    /** Creates a new ClusterRoleBindingDetails instance. */
    constructor($$source: Partial<ClusterRoleBindingDetails> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("roleRef" in $$source)) {
            this["roleRef"] = (new types$0.RoleRef());
        }
        if (!("subjects" in $$source)) {
            this["subjects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterRoleBindingDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterRoleBindingDetails {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roleRef" in $$parsedSource) {
            $$parsedSource["roleRef"] = $$createField3_0($$parsedSource["roleRef"]);
        }
        if ("subjects" in $$parsedSource) {
            $$parsedSource["subjects"] = $$createField4_0($$parsedSource["subjects"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField5_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField6_0($$parsedSource["annotations"]);
        }
        return new ClusterRoleBindingDetails($$parsedSource as Partial<ClusterRoleBindingDetails>);
    }
}

// Private type creation functions
const $$createType0 = types$0.RoleRef.createFrom;
const $$createType1 = types$0.Subject.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
