// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resourcemodel$0 from "../resourcemodel/models.js";

/**
 * ActionFacts carries lightweight, action-relevant state for catalog rows.
 * Identity stays on Summary; these fields only answer whether a known action
 * variant is appropriate for the current object state.
 */
export interface ActionFacts {
    "status"?: string;
    "unschedulable"?: boolean | null;
    "portForwardAvailable"?: boolean | null;
    "hpaManaged"?: boolean | null;
    "desiredReplicas"?: number | null;
}

/**
 * Scope describes whether a resource is cluster- or namespace-scoped.
 */
export enum Scope {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ScopeCluster indicates a cluster-scoped resource (no namespace).
     */
    ScopeCluster = "Cluster",

    /**
     * ScopeNamespace indicates a namespace-scoped resource.
     */
    ScopeNamespace = "Namespace",
};

/**
 * Summary represents the lightweight metadata captured for each Kubernetes object.
 */
export interface Summary {
    "ref": resourcemodel$0.ResourceRef;

    /**
     * resource version
     */
    "resourceVersion": string;

    /**
     * resource creation timestamp
     */
    "creationTimestamp": string;

    /**
     * resource scope
     */
    "scope": Scope;

    /**
     * optional digest of resource labels
     */
    "labelsDigest"?: string;

    /**
     * optional facts needed to present object actions correctly
     */
    "actionFacts"?: ActionFacts | null;
}
