// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface IPBlock {
    "cidr": string;
    "except"?: string[] | null;
}

export interface LabelSelector {
    "matchLabels"?: { [_ in string]?: string } | null;
    "matchExpressions"?: LabelSelectorRequirement[] | null;
}

export interface LabelSelectorRequirement {
    "key": string;
    "operator": string;
    "values"?: string[] | null;
}

export interface NetworkPolicyDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "podSelector": LabelSelector;
    "policyTypes": string[] | null;
    "ingressRules"?: NetworkPolicyRule[] | null;
    "egressRules"?: NetworkPolicyRule[] | null;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
}

/**
 * NetworkPolicyPeer omits an unset selector; an empty selector ({}) matches everything.
 */
export interface NetworkPolicyPeer {
    "podSelector"?: LabelSelector | null;
    "namespaceSelector"?: LabelSelector | null;
    "ipBlock"?: IPBlock | null;
}

export interface NetworkPolicyPort {
    "protocol"?: string;
    "port"?: string | null;
    "endPort"?: number | null;
}

export interface NetworkPolicyRule {
    "from"?: NetworkPolicyPeer[] | null;
    "to"?: NetworkPolicyPeer[] | null;
    "ports"?: NetworkPolicyPort[] | null;
}
