// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../../k8s.io/apimachinery/pkg/apis/meta/v1/models.js";

/**
 * HorizontalPodAutoscalerDetails represents comprehensive HPA information.
 */
export interface HorizontalPodAutoscalerDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "scaleTargetRef": ScaleTargetReference;
    "minReplicas"?: number | null;
    "maxReplicas": number;
    "currentReplicas": number;
    "desiredReplicas": number;
    "metrics": MetricSpec[] | null;
    "currentMetrics"?: MetricStatus[] | null;
    "behavior"?: ScalingBehavior | null;
    "conditions"?: string[] | null;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
    "lastScaleTime"?: v1$0.Time | null;
}

/**
 * MetricSpec represents a metric specification.
 */
export interface MetricSpec {
    "kind": string;
    "target": { [_ in string]?: string } | null;
}

/**
 * MetricStatus represents the current status of a metric.
 */
export interface MetricStatus {
    "kind": string;
    "current": { [_ in string]?: string } | null;
}

/**
 * ScaleTargetReference represents the target of the HPA.
 */
export interface ScaleTargetReference {
    "kind": string;
    "name": string;
    "apiVersion"?: string;
}

/**
 * ScalingBehavior represents the scaling behavior configuration.
 */
export interface ScalingBehavior {
    "scaleUp"?: ScalingRules | null;
    "scaleDown"?: ScalingRules | null;
}

/**
 * ScalingRules represents rules for scaling.
 */
export interface ScalingRules {
    "stabilizationWindowSeconds"?: number | null;
    "selectPolicy"?: string;
    "policies"?: string[] | null;
}
