// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SnapshotLastStatus is the closed set of refresh outcomes recorded per domain.
 */
export enum SnapshotLastStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SnapshotLastStatusSuccess = "success",
    SnapshotLastStatusError = "error",
};
