// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resourcemodel$0 from "../../resourcemodel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../../k8s.io/apimachinery/pkg/apis/meta/v1/models.js";

/**
 * AppPreferenceChange updates one persisted/runtime app preference.
 */
export interface AppPreferenceChange {
    "key": string;
    "value": any;
}

/**
 * AppPreferenceSchema describes one persisted/runtime app preference the
 * frontend can edit through the settings contract.
 */
export interface AppPreferenceSchema {
    "key": string;
    "type": string;
    "defaultValue": any;
    "currentValue": any;
    "min"?: number | null;
    "max"?: number | null;
    "enumOptions"?: string[] | null;
    "validation"?: string;
    "runtimeSideEffect": boolean;
}

/**
 * AppSettings represents the application settings
 */
export interface AppSettings {
    /**
     * Random local installation identifier used for pseudonymous telemetry
     */
    "anonymizedId": string;

    /**
     * "light", "dark", or "system"
     */
    "appearanceMode": string;

    /**
     * Multi-cluster selections in "path:context" form
     */
    "selectedKubeconfigs": string[] | null;

    /**
     * Use short names like "po" for pods in badges/headers
     */
    "useShortResourceNames": boolean;

    /**
     * Dim namespaces with no workloads in the sidebar
     */
    "dimInactiveNamespaces": boolean;

    /**
     * Allow only one expanded namespace in the sidebar
     */
    "exclusiveNamespaces": boolean;

    /**
     * Send production error reports
     */
    "errorReportingEnabled": boolean;

    /**
     * Enable automatic refresh cycles
     */
    "autoRefreshEnabled": boolean;

    /**
     * Refresh inactive clusters in the background
     */
    "refreshBackgroundClustersEnabled": boolean;

    /**
     * Metrics refresh interval (ms)
     */
    "metricsRefreshIntervalMs": number;

    /**
     * Per-cluster Kubernetes REST client QPS
     */
    "kubernetesClientQPS": number;

    /**
     * Per-cluster Kubernetes REST client burst allowance
     */
    "kubernetesClientBurst": number;

    /**
     * Concurrent namespace SelfSubjectRulesReview fetches
     */
    "permissionSSRRFetchConcurrency": number;

    /**
     * Max container log entries kept in memory per Object Panel Logs Tab (100-10000)
     */
    "objPanelLogsBufferMaxSize": number;

    /**
     * Max pod/container Object Panel Logs Tab targets per Logs tab (1-1000)
     */
    "objPanelLogsTargetPerScopeLimit": number;

    /**
     * Max pod/container Object Panel Logs Tab targets across all log tabs (1-1000)
     */
    "objPanelLogsTargetGlobalLimit": number;

    /**
     * Day.js format for the Kubernetes API timestamp shown in container logs
     */
    "objPanelLogsApiTimestampFormat": string;

    /**
     * Render the Kubernetes API timestamp in the user's local timezone instead of UTC
     */
    "objPanelLogsApiTimestampUseLocalTimeZone": boolean;

    /**
     * "shared" or "namespaced"
     */
    "gridTablePersistenceMode": string;

    /**
     * Default rows per page for tables without a persisted page size
     */
    "defaultTablePageSize": number;

    /**
     * "right", "bottom", or "floating"
     */
    "defaultObjectPanelPosition": string;

    /**
     * Default width when docked right (px)
     */
    "objectPanelDockedRightWidth": number;

    /**
     * Default height when docked bottom (px)
     */
    "objectPanelDockedBottomHeight": number;

    /**
     * Default floating width (px)
     */
    "objectPanelFloatingWidth": number;

    /**
     * Default floating height (px)
     */
    "objectPanelFloatingHeight": number;

    /**
     * Default floating X position (px)
     */
    "objectPanelFloatingX": number;

    /**
     * Default floating Y position (px)
     */
    "objectPanelFloatingY": number;

    /**
     * Hue for gray palette tint in light mode (0-360)
     */
    "paletteHueLight": number;

    /**
     * Saturation intensity for gray palette tint in light mode (0-100)
     */
    "paletteSaturationLight": number;

    /**
     * Brightness offset for gray palette in light mode (-50 to +50)
     */
    "paletteBrightnessLight": number;

    /**
     * Hue for gray palette tint in dark mode (0-360)
     */
    "paletteHueDark": number;

    /**
     * Saturation intensity for gray palette tint in dark mode (0-100)
     */
    "paletteSaturationDark": number;

    /**
     * Brightness offset for gray palette in dark mode (-50 to +50)
     */
    "paletteBrightnessDark": number;

    /**
     * Custom accent hex for light mode (empty = default)
     */
    "accentColorLight": string;

    /**
     * Custom accent hex for dark mode (empty = default)
     */
    "accentColorDark": string;

    /**
     * Custom link hex for light mode (empty = default)
     */
    "linkColorLight": string;

    /**
     * Custom link hex for dark mode (empty = default)
     */
    "linkColorDark": string;

    /**
     * Saved theme library
     */
    "themes": Theme[] | null;
}

/**
 * AppSettingsSchema describes the persisted/runtime settings contract.
 */
export interface AppSettingsSchema {
    "anonymizedId": string;
    "preferences": AppPreferenceSchema[] | null;
}

/**
 * AppearanceModeInfo represents the appearance mode payload sent to the frontend.
 */
export interface AppearanceModeInfo {
    /**
     * Stored appearance mode: "light", "dark", or "system"
     */
    "currentMode": string;

    /**
     * Stored appearance mode: "light", "dark", or "system"
     */
    "userMode": string;
}

export interface ConditionState {
    "type"?: string;
    "status": string;
    "reason"?: string;
    "message"?: string;
    "lastTransitionTime"?: string;
}

export interface ConditionsSummary {
    "accepted"?: ConditionState | null;
    "programmed"?: ConditionState | null;
    "ready"?: ConditionState | null;
    "resolvedRefs"?: ConditionState | null;
}

/**
 * ContainerLogsEntry represents a single log line with metadata
 */
export interface ContainerLogsEntry {
    /**
     * RFC3339Nano format
     */
    "timestamp": string;
    "pod": string;
    "container": string;
    "line": string;

    /**
     * Whether this is from an init container
     */
    "isInit": boolean;

    /**
     * Whether this is from an ephemeral/debug container
     */
    "isEphemeral"?: boolean;
}

/**
 * ContainerLogsFetchRequest represents parameters for fetching logs
 */
export interface ContainerLogsFetchRequest {
    "scope"?: string;
    "podFilter"?: string;
    "podInclude"?: string;
    "podExclude"?: string;
    "selectedFilters"?: string[] | null;
    "matchNone"?: boolean;

    /**
     * empty means all containers
     */
    "container"?: string;
    "includeInit"?: boolean | null;
    "includeEphemeral"?: boolean | null;
    "containerState"?: string;
    "include"?: string;
    "exclude"?: string;
    "previous": boolean;
    "tailLines": number;
    "sinceSeconds"?: number;
}

/**
 * ContainerLogsFetchResponse represents the response from FetchContainerLogs
 */
export interface ContainerLogsFetchResponse {
    "entries": ContainerLogsEntry[] | null;
    "warnings"?: string[] | null;
    "error"?: string;
}

/**
 * DebugContainerResponse contains the result of creating an ephemeral debug container.
 */
export interface DebugContainerResponse {
    "containerName": string;
    "podName": string;
    "namespace": string;
}

/**
 * DisplayRef preserves unresolved cross-references that cannot be opened safely
 * because the source object did not provide a full GVK.
 */
export type DisplayRef = resourcemodel$0.DisplayRef;

/**
 * DrainNodeOptions contains options for draining a node.
 */
export interface DrainNodeOptions {
    "gracePeriodSeconds"?: number | null;
    "timeoutSeconds"?: number | null;
    "ignoreDaemonSets": boolean;
    "deleteEmptyDirData": boolean;
    "force": boolean;
    "disableEviction": boolean;
    "skipWaitForPodsToTerminate": boolean;
}

export type GRPCRouteDetails = RouteDetails;

export interface GatewayListenerDetails {
    "name": string;
    "hostname"?: string;
    "port": number;
    "protocol": string;
    "attachedRoutes": number;
    "conditions"?: ConditionState[] | null;
}

export type HTTPRouteDetails = RouteDetails;

export interface JobReference {
    "name": string;
    "startTime"?: v1$0.Time | null;
}

/**
 * JobSimpleInfo provides a summary of a Job for list/tab views.
 */
export interface JobSimpleInfo {
    "kind": string;
    "name": string;
    "namespace": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;

    /**
     * e.g. "1/1"
     */
    "completions": string;
    "succeeded": number;
    "failed": number;
    "active": number;
    "startTime"?: v1$0.Time | null;
    "completionTime"?: v1$0.Time | null;
    "duration"?: string;
    "durationSeconds"?: number;
    "age": string;
    "ageTimestamp"?: number;
}

export interface JobTemplateDetails {
    "completions"?: number | null;
    "parallelism"?: number | null;
    "backoffLimit"?: number | null;
    "activeDeadlineSeconds"?: number | null;
    "ttlSecondsAfterFinished"?: number | null;
    "containers"?: PodDetailInfoContainer[] | null;
}

/**
 * KubeconfigInfo represents information about a kubeconfig context
 */
export interface KubeconfigInfo {
    /**
     * Display name (filename)
     */
    "name": string;

    /**
     * Path to the kubeconfig file
     */
    "path": string;

    /**
     * Context name within the file
     */
    "context": string;

    /**
     * Whether this is from the default config file
     */
    "isDefault": boolean;

    /**
     * Whether this is the current context in the file
     */
    "isCurrentContext": boolean;

    /**
     * Structural validation (clientcmd ConfirmUsable) failed; zero value = valid
     */
    "invalid": boolean;

    /**
     * Why the context is invalid (empty when valid)
     */
    "invalidReason": string;
}

/**
 * NodeLogDiscoveryResponse describes whether node logs are usable and which sources are available.
 */
export interface NodeLogDiscoveryResponse {
    "supported": boolean;
    "sources"?: NodeLogSource[] | null;
    "reason"?: string;
}

/**
 * NodeLogFetchRequest selects a discovered node log source to fetch.
 */
export interface NodeLogFetchRequest {
    "sourcePath": string;
    "sinceTime"?: string;
    "tailBytes"?: number;
}

/**
 * NodeLogFetchResponse contains raw node log content for a selected source.
 */
export interface NodeLogFetchResponse {
    "content"?: string;
    "source": NodeLogSource;
    "error"?: string;
    "sourcePath"?: string;
    "truncated"?: boolean;
}

/**
 * NodeLogSource represents a discovered node log source that can be fetched directly.
 */
export interface NodeLogSource {
    "id": string;
    "label": string;
    "kind": string;
    "path": string;
}

/**
 * ObjectRef is the shared openable Kubernetes object identity.
 */
export type ObjectRef = resourcemodel$0.ResourceRef;

/**
 * PodDetailInfo represents comprehensive pod information for the object panel
 */
export interface PodDetailInfo {
    /**
     * Basic information (same as PodSimpleInfo)
     */
    "name": string;
    "namespace": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;
    "ready": string;
    "restarts": number;
    "cpuRequest": string;
    "cpuLimit": string;
    "cpuUsage": string;
    "memRequest": string;
    "memLimit": string;
    "memUsage": string;

    /**
     * Ownership information
     */
    "ownerKind": string;
    "ownerName": string;

    /**
     * OwnerAPIVersion carries the wire-form apiVersion of the controlling
     * owner so the panel can open CRD-as-Pod-owner targets correctly. See
     *  and PodSimpleInfo.OwnerAPIVersion.
     */
    "ownerApiVersion"?: string;

    /**
     * Additional details for object panel
     */
    "node": string;
    "nodeIP"?: string;
    "podIP"?: string;
    "qosClass": string;
    "priority"?: number | null;
    "priorityClass"?: string;
    "serviceAccount": string;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
    "conditions"?: string[] | null;
    "containers": PodDetailInfoContainer[] | null;
    "initContainers"?: PodDetailInfoContainer[] | null;
    "volumes"?: string[] | null;
    "tolerations"?: string[] | null;
    "affinity"?: { [_ in string]?: any } | null;
    "hostNetwork": boolean;
    "hostPID": boolean;
    "hostIPC": boolean;
    "dnsPolicy"?: string;
    "restartPolicy": string;
    "schedulerName"?: string;
    "runtimeClass"?: string;
    "securityContext"?: { [_ in string]?: any } | null;
}

/**
 * PodDetailInfoContainer represents detailed container information within a pod
 */
export interface PodDetailInfoContainer {
    "name": string;
    "image": string;
    "imagePullPolicy": string;
    "ready": boolean;
    "restartCount": number;

    /**
     * waiting, running, terminated
     */
    "state": string;
    "stateReason"?: string;
    "stateMessage"?: string;
    "startedAt"?: string;
    "cpuRequest": string;
    "cpuLimit": string;
    "memRequest": string;
    "memLimit": string;
    "ports"?: string[] | null;
    "volumeMounts"?: string[] | null;
    "environment"?: { [_ in string]?: string } | null;
    "command"?: string[] | null;
    "args"?: string[] | null;
}

export interface PodMetricsSummary {
    "pods": number;
    "readyPods": number;
    "cpuUsage"?: string;
    "memUsage"?: string;
    "cpuRequest"?: string;
    "cpuLimit"?: string;
    "memRequest"?: string;
    "memLimit"?: string;
}

/**
 * PodSimpleInfo represents basic pod information for list views
 */
export interface PodSimpleInfo {
    /**
     * pod
     */
    "kind": string;
    "name": string;
    "namespace": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;
    "ready": string;

    /**
     * Total restart count across all containers
     */
    "restarts": number;
    "age": string;

    /**
     * Aggregated CPU requests
     */
    "cpuRequest": string;

    /**
     * Aggregated CPU limits
     */
    "cpuLimit": string;

    /**
     * Current CPU usage from metrics
     */
    "cpuUsage": string;

    /**
     * Aggregated memory requests
     */
    "memRequest": string;

    /**
     * Aggregated memory limits
     */
    "memLimit": string;

    /**
     * Current memory usage from metrics
     */
    "memUsage": string;

    /**
     * Kind of the owner (Deployment, StatefulSet, etc)
     */
    "ownerKind": string;

    /**
     * Name of the owner resource
     */
    "ownerName": string;

    /**
     * OwnerAPIVersion is the wire-form apiVersion of the owner (e.g.
     * "apps/v1", "argoproj.io/v1alpha1", "kubevirt.io/v1"). Threaded from
     * pod.OwnerReferences[*].APIVersion (or hardcoded apps/v1 for the
     * ReplicaSet→Deployment collapse) so the frontend can open
     * CRD-as-Pod-owner targets in the object panel with a fully-qualified
     * GVK. Required for Argo Rollouts, KubeVirt VMI, Tekton TaskRun,
     * Spark SparkApplication, etc.
     */
    "ownerApiVersion"?: string;
}

export interface PolicyRule {
    "apiGroups"?: string[] | null;
    "resources"?: string[] | null;
    "resourceNames"?: string[] | null;
    "verbs": string[] | null;
    "nonResourceURLs"?: string[] | null;
}

export interface RefOrDisplay {
    "ref"?: ObjectRef | null;
    "display"?: DisplayRef | null;
}

export interface ReferenceGrantFromInfo {
    "group": string;
    "kind": string;
    "namespace": string;
}

export interface ReplicaSetSummary {
    "name": string;
    "revision": string;
    "replicas": string;
    "readyReplicas": string;
    "availableReplicas": string;
    "age": string;
}

export interface RoleRef {
    "apiGroup": string;
    "kind": string;
    "name": string;
}

export interface RouteDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "age": string;
    "details": string;
    "hostnames"?: string[] | null;
    "parentRefs"?: RefOrDisplay[] | null;
    "backendRefs"?: RefOrDisplay[] | null;
    "rules"?: RouteRuleDetails[] | null;
    "conditions"?: ConditionState[] | null;
    "summary": ConditionsSummary;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
}

export interface RouteRuleDetails {
    "matches"?: string[] | null;
    "backendRefs"?: RefOrDisplay[] | null;
}

/**
 * ShellSession contains details about an active exec session.
 */
export interface ShellSession {
    "sessionId": string;
    "namespace": string;
    "podName": string;
    "container": string;
    "command": string[] | null;
    "containers": string[] | null;
}

/**
 * ShellSessionInfo describes a tracked shell exec session.
 */
export interface ShellSessionInfo {
    "sessionId": string;
    "clusterId": string;
    "clusterName": string;
    "namespace": string;
    "podName": string;
    "container": string;
    "command": string[] | null;
    "startedAt": v1$0.Time;
}

/**
 * ShellSessionRequest describes the namespace/pod/container to exec into.
 */
export interface ShellSessionRequest {
    "namespace": string;
    "podName": string;
    "container"?: string;
    "command"?: string[] | null;
}

export interface Subject {
    "kind": string;
    "apiGroup"?: string;
    "name": string;
    "namespace"?: string;
}

export type TLSRouteDetails = RouteDetails;

/**
 * Theme represents a saved color theme with optional cluster pattern matching.
 * Themes are ordered; when matching clusters, the first match wins.
 */
export interface Theme {
    /**
     * UUID
     */
    "id": string;

    /**
     * Display name, e.g. "Danger Red"
     */
    "name": string;

    /**
     * Glob pattern matched against context name, e.g. "prod*"; empty = "*" catch-all
     */
    "clusterPattern": string;

    /**
     * 0-360
     */
    "paletteHueLight": number;

    /**
     * 0-100
     */
    "paletteSaturationLight": number;

    /**
     * -50 to +50
     */
    "paletteBrightnessLight": number;

    /**
     * 0-360
     */
    "paletteHueDark": number;

    /**
     * 0-100
     */
    "paletteSaturationDark": number;

    /**
     * -50 to +50
     */
    "paletteBrightnessDark": number;

    /**
     * Hex "#rrggbb" or empty for default
     */
    "accentColorLight"?: string;

    /**
     * Hex "#rrggbb" or empty for default
     */
    "accentColorDark"?: string;

    /**
     * Hex "#rrggbb" or empty for default
     */
    "linkColorLight"?: string;

    /**
     * Hex "#rrggbb" or empty for default
     */
    "linkColorDark"?: string;
}

/**
 * ThemeClusterPatternValidationResult reports whether a saved theme cluster
 * pattern can be parsed by the app glob matcher.
 */
export interface ThemeClusterPatternValidationResult {
    "valid": boolean;
    "message"?: string;
}

/**
 * UpdateAppPreferencesRequest applies one atomic batch of preference changes.
 */
export interface UpdateAppPreferencesRequest {
    "changes": AppPreferenceChange[] | null;
}

/**
 * UpdateAppPreferencesResponse returns the normalized settings after an update.
 */
export interface UpdateAppPreferencesResponse {
    "settings": AppSettings | null;
    "changedKeys": string[] | null;
}

/**
 * WindowSettings represents the window position and size
 */
export interface WindowSettings {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximized": boolean;
}
