// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resourcemodel$0 from "../../resourcemodel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../../k8s.io/apimachinery/pkg/apis/meta/v1/models.js";

/**
 * AppPreferenceChange updates one persisted/runtime app preference.
 */
export class AppPreferenceChange {
    "key": string;
    "value": any;

    /** Creates a new AppPreferenceChange instance. */
    constructor($$source: Partial<AppPreferenceChange> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppPreferenceChange instance from a string or object.
     */
    static createFrom($$source: any = {}): AppPreferenceChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppPreferenceChange($$parsedSource as Partial<AppPreferenceChange>);
    }
}

/**
 * AppPreferenceSchema describes one persisted/runtime app preference the
 * frontend can edit through the settings contract.
 */
export class AppPreferenceSchema {
    "key": string;
    "type": string;
    "defaultValue": any;
    "currentValue": any;
    "min"?: number | null;
    "max"?: number | null;
    "enumOptions"?: string[];
    "validation"?: string;
    "runtimeSideEffect": boolean;

    /** Creates a new AppPreferenceSchema instance. */
    constructor($$source: Partial<AppPreferenceSchema> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("defaultValue" in $$source)) {
            this["defaultValue"] = null;
        }
        if (!("currentValue" in $$source)) {
            this["currentValue"] = null;
        }
        if (!("runtimeSideEffect" in $$source)) {
            this["runtimeSideEffect"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppPreferenceSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): AppPreferenceSchema {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enumOptions" in $$parsedSource) {
            $$parsedSource["enumOptions"] = $$createField6_0($$parsedSource["enumOptions"]);
        }
        return new AppPreferenceSchema($$parsedSource as Partial<AppPreferenceSchema>);
    }
}

/**
 * AppSettings represents the application settings
 */
export class AppSettings {
    /**
     * Random local installation identifier used for pseudonymous telemetry
     */
    "anonymizedId": string;

    /**
     * "light", "dark", or "system"
     */
    "appearanceMode": string;

    /**
     * Multi-cluster selections in "path:context" form
     */
    "selectedKubeconfigs": string[];

    /**
     * Use short names like "po" for pods in badges/headers
     */
    "useShortResourceNames": boolean;

    /**
     * Dim namespaces with no workloads in the sidebar
     */
    "dimInactiveNamespaces": boolean;

    /**
     * Allow only one expanded namespace in the sidebar
     */
    "exclusiveNamespaces": boolean;

    /**
     * Send production error reports
     */
    "errorReportingEnabled": boolean;

    /**
     * Enable automatic refresh cycles
     */
    "autoRefreshEnabled": boolean;

    /**
     * Refresh inactive clusters in the background
     */
    "refreshBackgroundClustersEnabled": boolean;

    /**
     * Metrics refresh interval (ms)
     */
    "metricsRefreshIntervalMs": number;

    /**
     * Per-cluster Kubernetes REST client QPS
     */
    "kubernetesClientQPS": number;

    /**
     * Per-cluster Kubernetes REST client burst allowance
     */
    "kubernetesClientBurst": number;

    /**
     * Concurrent namespace SelfSubjectRulesReview fetches
     */
    "permissionSSRRFetchConcurrency": number;

    /**
     * Max container log entries kept in memory per Object Panel Logs Tab (100-10000)
     */
    "objPanelLogsBufferMaxSize": number;

    /**
     * Max pod/container Object Panel Logs Tab targets per Logs tab (1-1000)
     */
    "objPanelLogsTargetPerScopeLimit": number;

    /**
     * Max pod/container Object Panel Logs Tab targets across all log tabs (1-1000)
     */
    "objPanelLogsTargetGlobalLimit": number;

    /**
     * Day.js format for the Kubernetes API timestamp shown in container logs
     */
    "objPanelLogsApiTimestampFormat": string;

    /**
     * Render the Kubernetes API timestamp in the user's local timezone instead of UTC
     */
    "objPanelLogsApiTimestampUseLocalTimeZone": boolean;

    /**
     * "shared" or "namespaced"
     */
    "gridTablePersistenceMode": string;

    /**
     * Default rows per page for tables without a persisted page size
     */
    "defaultTablePageSize": number;

    /**
     * "right", "bottom", or "floating"
     */
    "defaultObjectPanelPosition": string;

    /**
     * Default width when docked right (px)
     */
    "objectPanelDockedRightWidth": number;

    /**
     * Default height when docked bottom (px)
     */
    "objectPanelDockedBottomHeight": number;

    /**
     * Default floating width (px)
     */
    "objectPanelFloatingWidth": number;

    /**
     * Default floating height (px)
     */
    "objectPanelFloatingHeight": number;

    /**
     * Default floating X position (px)
     */
    "objectPanelFloatingX": number;

    /**
     * Default floating Y position (px)
     */
    "objectPanelFloatingY": number;

    /**
     * Hue for gray palette tint in light mode (0-360)
     */
    "paletteHueLight": number;

    /**
     * Saturation intensity for gray palette tint in light mode (0-100)
     */
    "paletteSaturationLight": number;

    /**
     * Brightness offset for gray palette in light mode (-50 to +50)
     */
    "paletteBrightnessLight": number;

    /**
     * Hue for gray palette tint in dark mode (0-360)
     */
    "paletteHueDark": number;

    /**
     * Saturation intensity for gray palette tint in dark mode (0-100)
     */
    "paletteSaturationDark": number;

    /**
     * Brightness offset for gray palette in dark mode (-50 to +50)
     */
    "paletteBrightnessDark": number;

    /**
     * Custom accent hex for light mode (empty = default)
     */
    "accentColorLight": string;

    /**
     * Custom accent hex for dark mode (empty = default)
     */
    "accentColorDark": string;

    /**
     * Custom link hex for light mode (empty = default)
     */
    "linkColorLight": string;

    /**
     * Custom link hex for dark mode (empty = default)
     */
    "linkColorDark": string;

    /**
     * Saved theme library
     */
    "themes": Theme[];

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("anonymizedId" in $$source)) {
            this["anonymizedId"] = "";
        }
        if (!("appearanceMode" in $$source)) {
            this["appearanceMode"] = "";
        }
        if (!("selectedKubeconfigs" in $$source)) {
            this["selectedKubeconfigs"] = [];
        }
        if (!("useShortResourceNames" in $$source)) {
            this["useShortResourceNames"] = false;
        }
        if (!("dimInactiveNamespaces" in $$source)) {
            this["dimInactiveNamespaces"] = false;
        }
        if (!("exclusiveNamespaces" in $$source)) {
            this["exclusiveNamespaces"] = false;
        }
        if (!("errorReportingEnabled" in $$source)) {
            this["errorReportingEnabled"] = false;
        }
        if (!("autoRefreshEnabled" in $$source)) {
            this["autoRefreshEnabled"] = false;
        }
        if (!("refreshBackgroundClustersEnabled" in $$source)) {
            this["refreshBackgroundClustersEnabled"] = false;
        }
        if (!("metricsRefreshIntervalMs" in $$source)) {
            this["metricsRefreshIntervalMs"] = 0;
        }
        if (!("kubernetesClientQPS" in $$source)) {
            this["kubernetesClientQPS"] = 0;
        }
        if (!("kubernetesClientBurst" in $$source)) {
            this["kubernetesClientBurst"] = 0;
        }
        if (!("permissionSSRRFetchConcurrency" in $$source)) {
            this["permissionSSRRFetchConcurrency"] = 0;
        }
        if (!("objPanelLogsBufferMaxSize" in $$source)) {
            this["objPanelLogsBufferMaxSize"] = 0;
        }
        if (!("objPanelLogsTargetPerScopeLimit" in $$source)) {
            this["objPanelLogsTargetPerScopeLimit"] = 0;
        }
        if (!("objPanelLogsTargetGlobalLimit" in $$source)) {
            this["objPanelLogsTargetGlobalLimit"] = 0;
        }
        if (!("objPanelLogsApiTimestampFormat" in $$source)) {
            this["objPanelLogsApiTimestampFormat"] = "";
        }
        if (!("objPanelLogsApiTimestampUseLocalTimeZone" in $$source)) {
            this["objPanelLogsApiTimestampUseLocalTimeZone"] = false;
        }
        if (!("gridTablePersistenceMode" in $$source)) {
            this["gridTablePersistenceMode"] = "";
        }
        if (!("defaultTablePageSize" in $$source)) {
            this["defaultTablePageSize"] = 0;
        }
        if (!("defaultObjectPanelPosition" in $$source)) {
            this["defaultObjectPanelPosition"] = "";
        }
        if (!("objectPanelDockedRightWidth" in $$source)) {
            this["objectPanelDockedRightWidth"] = 0;
        }
        if (!("objectPanelDockedBottomHeight" in $$source)) {
            this["objectPanelDockedBottomHeight"] = 0;
        }
        if (!("objectPanelFloatingWidth" in $$source)) {
            this["objectPanelFloatingWidth"] = 0;
        }
        if (!("objectPanelFloatingHeight" in $$source)) {
            this["objectPanelFloatingHeight"] = 0;
        }
        if (!("objectPanelFloatingX" in $$source)) {
            this["objectPanelFloatingX"] = 0;
        }
        if (!("objectPanelFloatingY" in $$source)) {
            this["objectPanelFloatingY"] = 0;
        }
        if (!("paletteHueLight" in $$source)) {
            this["paletteHueLight"] = 0;
        }
        if (!("paletteSaturationLight" in $$source)) {
            this["paletteSaturationLight"] = 0;
        }
        if (!("paletteBrightnessLight" in $$source)) {
            this["paletteBrightnessLight"] = 0;
        }
        if (!("paletteHueDark" in $$source)) {
            this["paletteHueDark"] = 0;
        }
        if (!("paletteSaturationDark" in $$source)) {
            this["paletteSaturationDark"] = 0;
        }
        if (!("paletteBrightnessDark" in $$source)) {
            this["paletteBrightnessDark"] = 0;
        }
        if (!("accentColorLight" in $$source)) {
            this["accentColorLight"] = "";
        }
        if (!("accentColorDark" in $$source)) {
            this["accentColorDark"] = "";
        }
        if (!("linkColorLight" in $$source)) {
            this["linkColorLight"] = "";
        }
        if (!("linkColorDark" in $$source)) {
            this["linkColorDark"] = "";
        }
        if (!("themes" in $$source)) {
            this["themes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        const $$createField2_0 = $$createType0;
        const $$createField37_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("selectedKubeconfigs" in $$parsedSource) {
            $$parsedSource["selectedKubeconfigs"] = $$createField2_0($$parsedSource["selectedKubeconfigs"]);
        }
        if ("themes" in $$parsedSource) {
            $$parsedSource["themes"] = $$createField37_0($$parsedSource["themes"]);
        }
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * AppSettingsSchema describes the persisted/runtime settings contract.
 */
export class AppSettingsSchema {
    "anonymizedId": string;
    "preferences": AppPreferenceSchema[];

    /** Creates a new AppSettingsSchema instance. */
    constructor($$source: Partial<AppSettingsSchema> = {}) {
        if (!("anonymizedId" in $$source)) {
            this["anonymizedId"] = "";
        }
        if (!("preferences" in $$source)) {
            this["preferences"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettingsSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettingsSchema {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preferences" in $$parsedSource) {
            $$parsedSource["preferences"] = $$createField1_0($$parsedSource["preferences"]);
        }
        return new AppSettingsSchema($$parsedSource as Partial<AppSettingsSchema>);
    }
}

/**
 * AppearanceModeInfo represents the appearance mode payload sent to the frontend.
 */
export class AppearanceModeInfo {
    /**
     * Stored appearance mode: "light", "dark", or "system"
     */
    "currentMode": string;

    /**
     * Stored appearance mode: "light", "dark", or "system"
     */
    "userMode": string;

    /** Creates a new AppearanceModeInfo instance. */
    constructor($$source: Partial<AppearanceModeInfo> = {}) {
        if (!("currentMode" in $$source)) {
            this["currentMode"] = "";
        }
        if (!("userMode" in $$source)) {
            this["userMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppearanceModeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppearanceModeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppearanceModeInfo($$parsedSource as Partial<AppearanceModeInfo>);
    }
}

export class ConditionState {
    "type"?: string;
    "status": string;
    "reason"?: string;
    "message"?: string;
    "lastTransitionTime"?: string;

    /** Creates a new ConditionState instance. */
    constructor($$source: Partial<ConditionState> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConditionState instance from a string or object.
     */
    static createFrom($$source: any = {}): ConditionState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConditionState($$parsedSource as Partial<ConditionState>);
    }
}

export class ConditionsSummary {
    "accepted"?: ConditionState | null;
    "programmed"?: ConditionState | null;
    "ready"?: ConditionState | null;
    "resolvedRefs"?: ConditionState | null;

    /** Creates a new ConditionsSummary instance. */
    constructor($$source: Partial<ConditionsSummary> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConditionsSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ConditionsSummary {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accepted" in $$parsedSource) {
            $$parsedSource["accepted"] = $$createField0_0($$parsedSource["accepted"]);
        }
        if ("programmed" in $$parsedSource) {
            $$parsedSource["programmed"] = $$createField1_0($$parsedSource["programmed"]);
        }
        if ("ready" in $$parsedSource) {
            $$parsedSource["ready"] = $$createField2_0($$parsedSource["ready"]);
        }
        if ("resolvedRefs" in $$parsedSource) {
            $$parsedSource["resolvedRefs"] = $$createField3_0($$parsedSource["resolvedRefs"]);
        }
        return new ConditionsSummary($$parsedSource as Partial<ConditionsSummary>);
    }
}

/**
 * ContainerLogsEntry represents a single log line with metadata
 */
export class ContainerLogsEntry {
    /**
     * RFC3339Nano format
     */
    "timestamp": string;
    "pod": string;
    "container": string;
    "line": string;

    /**
     * Whether this is from an init container
     */
    "isInit": boolean;

    /**
     * Whether this is from an ephemeral/debug container
     */
    "isEphemeral"?: boolean;

    /** Creates a new ContainerLogsEntry instance. */
    constructor($$source: Partial<ContainerLogsEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("pod" in $$source)) {
            this["pod"] = "";
        }
        if (!("container" in $$source)) {
            this["container"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = "";
        }
        if (!("isInit" in $$source)) {
            this["isInit"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContainerLogsEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ContainerLogsEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContainerLogsEntry($$parsedSource as Partial<ContainerLogsEntry>);
    }
}

/**
 * ContainerLogsFetchRequest represents parameters for fetching logs
 */
export class ContainerLogsFetchRequest {
    "scope"?: string;
    "podFilter"?: string;
    "podInclude"?: string;
    "podExclude"?: string;
    "selectedFilters"?: string[];
    "matchNone"?: boolean;

    /**
     * empty means all containers
     */
    "container"?: string;
    "includeInit"?: boolean | null;
    "includeEphemeral"?: boolean | null;
    "containerState"?: string;
    "include"?: string;
    "exclude"?: string;
    "previous": boolean;
    "tailLines": number;
    "sinceSeconds"?: number;

    /** Creates a new ContainerLogsFetchRequest instance. */
    constructor($$source: Partial<ContainerLogsFetchRequest> = {}) {
        if (!("previous" in $$source)) {
            this["previous"] = false;
        }
        if (!("tailLines" in $$source)) {
            this["tailLines"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContainerLogsFetchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ContainerLogsFetchRequest {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("selectedFilters" in $$parsedSource) {
            $$parsedSource["selectedFilters"] = $$createField4_0($$parsedSource["selectedFilters"]);
        }
        return new ContainerLogsFetchRequest($$parsedSource as Partial<ContainerLogsFetchRequest>);
    }
}

/**
 * ContainerLogsFetchResponse represents the response from FetchContainerLogs
 */
export class ContainerLogsFetchResponse {
    "entries": ContainerLogsEntry[];
    "warnings"?: string[];
    "error"?: string;

    /** Creates a new ContainerLogsFetchResponse instance. */
    constructor($$source: Partial<ContainerLogsFetchResponse> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContainerLogsFetchResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ContainerLogsFetchResponse {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField1_0($$parsedSource["warnings"]);
        }
        return new ContainerLogsFetchResponse($$parsedSource as Partial<ContainerLogsFetchResponse>);
    }
}

/**
 * DebugContainerResponse contains the result of creating an ephemeral debug container.
 */
export class DebugContainerResponse {
    "containerName": string;
    "podName": string;
    "namespace": string;

    /** Creates a new DebugContainerResponse instance. */
    constructor($$source: Partial<DebugContainerResponse> = {}) {
        if (!("containerName" in $$source)) {
            this["containerName"] = "";
        }
        if (!("podName" in $$source)) {
            this["podName"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DebugContainerResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DebugContainerResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DebugContainerResponse($$parsedSource as Partial<DebugContainerResponse>);
    }
}

/**
 * DisplayRef preserves unresolved cross-references that cannot be opened safely
 * because the source object did not provide a full GVK.
 */
export const DisplayRef = resourcemodel$0.DisplayRef;

/**
 * DisplayRef preserves unresolved cross-references that cannot be opened safely
 * because the source object did not provide a full GVK.
 */
export type DisplayRef = resourcemodel$0.DisplayRef;

/**
 * DrainNodeOptions contains options for draining a node.
 */
export class DrainNodeOptions {
    "gracePeriodSeconds"?: number | null;
    "timeoutSeconds"?: number | null;
    "ignoreDaemonSets": boolean;
    "deleteEmptyDirData": boolean;
    "force": boolean;
    "disableEviction": boolean;
    "skipWaitForPodsToTerminate": boolean;

    /** Creates a new DrainNodeOptions instance. */
    constructor($$source: Partial<DrainNodeOptions> = {}) {
        if (!("ignoreDaemonSets" in $$source)) {
            this["ignoreDaemonSets"] = false;
        }
        if (!("deleteEmptyDirData" in $$source)) {
            this["deleteEmptyDirData"] = false;
        }
        if (!("force" in $$source)) {
            this["force"] = false;
        }
        if (!("disableEviction" in $$source)) {
            this["disableEviction"] = false;
        }
        if (!("skipWaitForPodsToTerminate" in $$source)) {
            this["skipWaitForPodsToTerminate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DrainNodeOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): DrainNodeOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DrainNodeOptions($$parsedSource as Partial<DrainNodeOptions>);
    }
}

export class GatewayListenerDetails {
    "name": string;
    "hostname"?: string;
    "port": number;
    "protocol": string;
    "attachedRoutes": number;
    "conditions"?: ConditionState[];

    /** Creates a new GatewayListenerDetails instance. */
    constructor($$source: Partial<GatewayListenerDetails> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("attachedRoutes" in $$source)) {
            this["attachedRoutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayListenerDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayListenerDetails {
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField5_0($$parsedSource["conditions"]);
        }
        return new GatewayListenerDetails($$parsedSource as Partial<GatewayListenerDetails>);
    }
}

export class JobReference {
    "name": string;
    "startTime"?: v1$0.Time | null;

    /** Creates a new JobReference instance. */
    constructor($$source: Partial<JobReference> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobReference instance from a string or object.
     */
    static createFrom($$source: any = {}): JobReference {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobReference($$parsedSource as Partial<JobReference>);
    }
}

/**
 * JobSimpleInfo provides a summary of a Job for list/tab views.
 */
export class JobSimpleInfo {
    "kind": string;
    "name": string;
    "namespace": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;

    /**
     * e.g. "1/1"
     */
    "completions": string;
    "succeeded": number;
    "failed": number;
    "active": number;
    "startTime"?: v1$0.Time | null;
    "completionTime"?: v1$0.Time | null;
    "duration"?: string;
    "durationSeconds"?: number;
    "age": string;
    "ageTimestamp"?: number;

    /** Creates a new JobSimpleInfo instance. */
    constructor($$source: Partial<JobSimpleInfo> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("completions" in $$source)) {
            this["completions"] = "";
        }
        if (!("succeeded" in $$source)) {
            this["succeeded"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("active" in $$source)) {
            this["active"] = 0;
        }
        if (!("age" in $$source)) {
            this["age"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobSimpleInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): JobSimpleInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobSimpleInfo($$parsedSource as Partial<JobSimpleInfo>);
    }
}

export class JobTemplateDetails {
    "completions"?: number | null;
    "parallelism"?: number | null;
    "backoffLimit"?: number | null;
    "activeDeadlineSeconds"?: number | null;
    "ttlSecondsAfterFinished"?: number | null;
    "containers"?: PodDetailInfoContainer[];

    /** Creates a new JobTemplateDetails instance. */
    constructor($$source: Partial<JobTemplateDetails> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobTemplateDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): JobTemplateDetails {
        const $$createField5_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("containers" in $$parsedSource) {
            $$parsedSource["containers"] = $$createField5_0($$parsedSource["containers"]);
        }
        return new JobTemplateDetails($$parsedSource as Partial<JobTemplateDetails>);
    }
}

/**
 * KubeconfigInfo represents information about a kubeconfig context
 */
export class KubeconfigInfo {
    /**
     * Display name (filename)
     */
    "name": string;

    /**
     * Path to the kubeconfig file
     */
    "path": string;

    /**
     * Context name within the file
     */
    "context": string;

    /**
     * Whether this is from the default config file
     */
    "isDefault": boolean;

    /**
     * Whether this is the current context in the file
     */
    "isCurrentContext": boolean;

    /**
     * Structural validation (clientcmd ConfirmUsable) failed; zero value = valid
     */
    "invalid": boolean;

    /**
     * Why the context is invalid (empty when valid)
     */
    "invalidReason": string;

    /** Creates a new KubeconfigInfo instance. */
    constructor($$source: Partial<KubeconfigInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = "";
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }
        if (!("isCurrentContext" in $$source)) {
            this["isCurrentContext"] = false;
        }
        if (!("invalid" in $$source)) {
            this["invalid"] = false;
        }
        if (!("invalidReason" in $$source)) {
            this["invalidReason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KubeconfigInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): KubeconfigInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KubeconfigInfo($$parsedSource as Partial<KubeconfigInfo>);
    }
}

/**
 * NodeLogDiscoveryResponse describes whether node logs are usable and which sources are available.
 */
export class NodeLogDiscoveryResponse {
    "supported": boolean;
    "sources"?: NodeLogSource[];
    "reason"?: string;

    /** Creates a new NodeLogDiscoveryResponse instance. */
    constructor($$source: Partial<NodeLogDiscoveryResponse> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeLogDiscoveryResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeLogDiscoveryResponse {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField1_0($$parsedSource["sources"]);
        }
        return new NodeLogDiscoveryResponse($$parsedSource as Partial<NodeLogDiscoveryResponse>);
    }
}

/**
 * NodeLogFetchRequest selects a discovered node log source to fetch.
 */
export class NodeLogFetchRequest {
    "sourcePath": string;
    "sinceTime"?: string;
    "tailBytes"?: number;

    /** Creates a new NodeLogFetchRequest instance. */
    constructor($$source: Partial<NodeLogFetchRequest> = {}) {
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeLogFetchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeLogFetchRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeLogFetchRequest($$parsedSource as Partial<NodeLogFetchRequest>);
    }
}

/**
 * NodeLogFetchResponse contains raw node log content for a selected source.
 */
export class NodeLogFetchResponse {
    "content"?: string;
    "source": NodeLogSource;
    "error"?: string;
    "sourcePath"?: string;
    "truncated"?: boolean;

    /** Creates a new NodeLogFetchResponse instance. */
    constructor($$source: Partial<NodeLogFetchResponse> = {}) {
        if (!("source" in $$source)) {
            this["source"] = (new NodeLogSource());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeLogFetchResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeLogFetchResponse {
        const $$createField1_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField1_0($$parsedSource["source"]);
        }
        return new NodeLogFetchResponse($$parsedSource as Partial<NodeLogFetchResponse>);
    }
}

/**
 * NodeLogSource represents a discovered node log source that can be fetched directly.
 */
export class NodeLogSource {
    "id": string;
    "label": string;
    "kind": string;
    "path": string;

    /** Creates a new NodeLogSource instance. */
    constructor($$source: Partial<NodeLogSource> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeLogSource instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeLogSource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeLogSource($$parsedSource as Partial<NodeLogSource>);
    }
}

/**
 * ObjectRef is the shared openable Kubernetes object identity.
 */
export const ObjectRef = resourcemodel$0.ResourceRef;

/**
 * ObjectRef is the shared openable Kubernetes object identity.
 */
export type ObjectRef = resourcemodel$0.ResourceRef;

/**
 * PodDetailInfo represents comprehensive pod information for the object panel
 */
export class PodDetailInfo {
    /**
     * Basic information (same as PodSimpleInfo)
     */
    "name": string;
    "namespace": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;
    "ready": string;
    "restarts": number;
    "cpuRequest": string;
    "cpuLimit": string;
    "cpuUsage": string;
    "memRequest": string;
    "memLimit": string;
    "memUsage": string;

    /**
     * Ownership information
     */
    "ownerKind": string;
    "ownerName": string;

    /**
     * OwnerAPIVersion carries the wire-form apiVersion of the controlling
     * owner so the panel can open CRD-as-Pod-owner targets correctly. See
     *  and PodSimpleInfo.OwnerAPIVersion.
     */
    "ownerApiVersion"?: string;

    /**
     * Additional details for object panel
     */
    "node": string;
    "nodeIP"?: string;
    "podIP"?: string;
    "qosClass": string;
    "priority"?: number | null;
    "priorityClass"?: string;
    "serviceAccount": string;
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };
    "conditions"?: string[];
    "containers": PodDetailInfoContainer[];
    "initContainers"?: PodDetailInfoContainer[];
    "volumes"?: string[];
    "tolerations"?: string[];
    "affinity"?: { [_ in string]?: any };
    "hostNetwork": boolean;
    "hostPID": boolean;
    "hostIPC": boolean;
    "dnsPolicy"?: string;
    "restartPolicy": string;
    "schedulerName"?: string;
    "runtimeClass"?: string;
    "securityContext"?: { [_ in string]?: any };

    /** Creates a new PodDetailInfo instance. */
    constructor($$source: Partial<PodDetailInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = "";
        }
        if (!("restarts" in $$source)) {
            this["restarts"] = 0;
        }
        if (!("cpuRequest" in $$source)) {
            this["cpuRequest"] = "";
        }
        if (!("cpuLimit" in $$source)) {
            this["cpuLimit"] = "";
        }
        if (!("cpuUsage" in $$source)) {
            this["cpuUsage"] = "";
        }
        if (!("memRequest" in $$source)) {
            this["memRequest"] = "";
        }
        if (!("memLimit" in $$source)) {
            this["memLimit"] = "";
        }
        if (!("memUsage" in $$source)) {
            this["memUsage"] = "";
        }
        if (!("ownerKind" in $$source)) {
            this["ownerKind"] = "";
        }
        if (!("ownerName" in $$source)) {
            this["ownerName"] = "";
        }
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("qosClass" in $$source)) {
            this["qosClass"] = "";
        }
        if (!("serviceAccount" in $$source)) {
            this["serviceAccount"] = "";
        }
        if (!("containers" in $$source)) {
            this["containers"] = [];
        }
        if (!("hostNetwork" in $$source)) {
            this["hostNetwork"] = false;
        }
        if (!("hostPID" in $$source)) {
            this["hostPID"] = false;
        }
        if (!("hostIPC" in $$source)) {
            this["hostIPC"] = false;
        }
        if (!("restartPolicy" in $$source)) {
            this["restartPolicy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PodDetailInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PodDetailInfo {
        const $$createField24_0 = $$createType14;
        const $$createField25_0 = $$createType14;
        const $$createField26_0 = $$createType0;
        const $$createField27_0 = $$createType11;
        const $$createField28_0 = $$createType11;
        const $$createField29_0 = $$createType0;
        const $$createField30_0 = $$createType0;
        const $$createField31_0 = $$createType15;
        const $$createField39_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField24_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField25_0($$parsedSource["annotations"]);
        }
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField26_0($$parsedSource["conditions"]);
        }
        if ("containers" in $$parsedSource) {
            $$parsedSource["containers"] = $$createField27_0($$parsedSource["containers"]);
        }
        if ("initContainers" in $$parsedSource) {
            $$parsedSource["initContainers"] = $$createField28_0($$parsedSource["initContainers"]);
        }
        if ("volumes" in $$parsedSource) {
            $$parsedSource["volumes"] = $$createField29_0($$parsedSource["volumes"]);
        }
        if ("tolerations" in $$parsedSource) {
            $$parsedSource["tolerations"] = $$createField30_0($$parsedSource["tolerations"]);
        }
        if ("affinity" in $$parsedSource) {
            $$parsedSource["affinity"] = $$createField31_0($$parsedSource["affinity"]);
        }
        if ("securityContext" in $$parsedSource) {
            $$parsedSource["securityContext"] = $$createField39_0($$parsedSource["securityContext"]);
        }
        return new PodDetailInfo($$parsedSource as Partial<PodDetailInfo>);
    }
}

/**
 * PodDetailInfoContainer represents detailed container information within a pod
 */
export class PodDetailInfoContainer {
    "name": string;
    "image": string;
    "imagePullPolicy": string;
    "ready": boolean;
    "restartCount": number;

    /**
     * waiting, running, terminated
     */
    "state": string;
    "stateReason"?: string;
    "stateMessage"?: string;
    "startedAt"?: string;
    "cpuRequest": string;
    "cpuLimit": string;
    "memRequest": string;
    "memLimit": string;
    "ports"?: string[];
    "volumeMounts"?: string[];
    "environment"?: { [_ in string]?: string };
    "command"?: string[];
    "args"?: string[];

    /** Creates a new PodDetailInfoContainer instance. */
    constructor($$source: Partial<PodDetailInfoContainer> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("imagePullPolicy" in $$source)) {
            this["imagePullPolicy"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("restartCount" in $$source)) {
            this["restartCount"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("cpuRequest" in $$source)) {
            this["cpuRequest"] = "";
        }
        if (!("cpuLimit" in $$source)) {
            this["cpuLimit"] = "";
        }
        if (!("memRequest" in $$source)) {
            this["memRequest"] = "";
        }
        if (!("memLimit" in $$source)) {
            this["memLimit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PodDetailInfoContainer instance from a string or object.
     */
    static createFrom($$source: any = {}): PodDetailInfoContainer {
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType0;
        const $$createField15_0 = $$createType14;
        const $$createField16_0 = $$createType0;
        const $$createField17_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField13_0($$parsedSource["ports"]);
        }
        if ("volumeMounts" in $$parsedSource) {
            $$parsedSource["volumeMounts"] = $$createField14_0($$parsedSource["volumeMounts"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField15_0($$parsedSource["environment"]);
        }
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField16_0($$parsedSource["command"]);
        }
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField17_0($$parsedSource["args"]);
        }
        return new PodDetailInfoContainer($$parsedSource as Partial<PodDetailInfoContainer>);
    }
}

export class PodMetricsSummary {
    "pods": number;
    "readyPods": number;
    "cpuUsage"?: string;
    "memUsage"?: string;
    "cpuRequest"?: string;
    "cpuLimit"?: string;
    "memRequest"?: string;
    "memLimit"?: string;

    /** Creates a new PodMetricsSummary instance. */
    constructor($$source: Partial<PodMetricsSummary> = {}) {
        if (!("pods" in $$source)) {
            this["pods"] = 0;
        }
        if (!("readyPods" in $$source)) {
            this["readyPods"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PodMetricsSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PodMetricsSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PodMetricsSummary($$parsedSource as Partial<PodMetricsSummary>);
    }
}

/**
 * PodSimpleInfo represents basic pod information for list views
 */
export class PodSimpleInfo {
    /**
     * pod
     */
    "kind": string;
    "name": string;
    "namespace": string;
    "status": string;
    "statusState"?: string;
    "statusPresentation"?: string;
    "statusReason"?: string;
    "ready": string;

    /**
     * Total restart count across all containers
     */
    "restarts": number;
    "age": string;

    /**
     * Aggregated CPU requests
     */
    "cpuRequest": string;

    /**
     * Aggregated CPU limits
     */
    "cpuLimit": string;

    /**
     * Current CPU usage from metrics
     */
    "cpuUsage": string;

    /**
     * Aggregated memory requests
     */
    "memRequest": string;

    /**
     * Aggregated memory limits
     */
    "memLimit": string;

    /**
     * Current memory usage from metrics
     */
    "memUsage": string;

    /**
     * Kind of the owner (Deployment, StatefulSet, etc)
     */
    "ownerKind": string;

    /**
     * Name of the owner resource
     */
    "ownerName": string;

    /**
     * OwnerAPIVersion is the wire-form apiVersion of the owner (e.g.
     * "apps/v1", "argoproj.io/v1alpha1", "kubevirt.io/v1"). Threaded from
     * pod.OwnerReferences[*].APIVersion (or hardcoded apps/v1 for the
     * ReplicaSet→Deployment collapse) so the frontend can open
     * CRD-as-Pod-owner targets in the object panel with a fully-qualified
     * GVK. Required for Argo Rollouts, KubeVirt VMI, Tekton TaskRun,
     * Spark SparkApplication, etc.
     */
    "ownerApiVersion"?: string;

    /** Creates a new PodSimpleInfo instance. */
    constructor($$source: Partial<PodSimpleInfo> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = "";
        }
        if (!("restarts" in $$source)) {
            this["restarts"] = 0;
        }
        if (!("age" in $$source)) {
            this["age"] = "";
        }
        if (!("cpuRequest" in $$source)) {
            this["cpuRequest"] = "";
        }
        if (!("cpuLimit" in $$source)) {
            this["cpuLimit"] = "";
        }
        if (!("cpuUsage" in $$source)) {
            this["cpuUsage"] = "";
        }
        if (!("memRequest" in $$source)) {
            this["memRequest"] = "";
        }
        if (!("memLimit" in $$source)) {
            this["memLimit"] = "";
        }
        if (!("memUsage" in $$source)) {
            this["memUsage"] = "";
        }
        if (!("ownerKind" in $$source)) {
            this["ownerKind"] = "";
        }
        if (!("ownerName" in $$source)) {
            this["ownerName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PodSimpleInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PodSimpleInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PodSimpleInfo($$parsedSource as Partial<PodSimpleInfo>);
    }
}

export class PolicyRule {
    "apiGroups"?: string[];
    "resources"?: string[];
    "resourceNames"?: string[];
    "verbs": string[];
    "nonResourceURLs"?: string[];

    /** Creates a new PolicyRule instance. */
    constructor($$source: Partial<PolicyRule> = {}) {
        if (!("verbs" in $$source)) {
            this["verbs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PolicyRule instance from a string or object.
     */
    static createFrom($$source: any = {}): PolicyRule {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apiGroups" in $$parsedSource) {
            $$parsedSource["apiGroups"] = $$createField0_0($$parsedSource["apiGroups"]);
        }
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField1_0($$parsedSource["resources"]);
        }
        if ("resourceNames" in $$parsedSource) {
            $$parsedSource["resourceNames"] = $$createField2_0($$parsedSource["resourceNames"]);
        }
        if ("verbs" in $$parsedSource) {
            $$parsedSource["verbs"] = $$createField3_0($$parsedSource["verbs"]);
        }
        if ("nonResourceURLs" in $$parsedSource) {
            $$parsedSource["nonResourceURLs"] = $$createField4_0($$parsedSource["nonResourceURLs"]);
        }
        return new PolicyRule($$parsedSource as Partial<PolicyRule>);
    }
}

export class RefOrDisplay {
    "ref"?: ObjectRef | null;
    "display"?: DisplayRef | null;

    /** Creates a new RefOrDisplay instance. */
    constructor($$source: Partial<RefOrDisplay> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefOrDisplay instance from a string or object.
     */
    static createFrom($$source: any = {}): RefOrDisplay {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField0_0($$parsedSource["ref"]);
        }
        if ("display" in $$parsedSource) {
            $$parsedSource["display"] = $$createField1_0($$parsedSource["display"]);
        }
        return new RefOrDisplay($$parsedSource as Partial<RefOrDisplay>);
    }
}

export class ReferenceGrantFromInfo {
    "group": string;
    "kind": string;
    "namespace": string;

    /** Creates a new ReferenceGrantFromInfo instance. */
    constructor($$source: Partial<ReferenceGrantFromInfo> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReferenceGrantFromInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ReferenceGrantFromInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReferenceGrantFromInfo($$parsedSource as Partial<ReferenceGrantFromInfo>);
    }
}

export class ReplicaSetSummary {
    "name": string;
    "revision": string;
    "replicas": string;
    "readyReplicas": string;
    "availableReplicas": string;
    "age": string;

    /** Creates a new ReplicaSetSummary instance. */
    constructor($$source: Partial<ReplicaSetSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("revision" in $$source)) {
            this["revision"] = "";
        }
        if (!("replicas" in $$source)) {
            this["replicas"] = "";
        }
        if (!("readyReplicas" in $$source)) {
            this["readyReplicas"] = "";
        }
        if (!("availableReplicas" in $$source)) {
            this["availableReplicas"] = "";
        }
        if (!("age" in $$source)) {
            this["age"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplicaSetSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplicaSetSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplicaSetSummary($$parsedSource as Partial<ReplicaSetSummary>);
    }
}

export class RoleRef {
    "apiGroup": string;
    "kind": string;
    "name": string;

    /** Creates a new RoleRef instance. */
    constructor($$source: Partial<RoleRef> = {}) {
        if (!("apiGroup" in $$source)) {
            this["apiGroup"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoleRef instance from a string or object.
     */
    static createFrom($$source: any = {}): RoleRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoleRef($$parsedSource as Partial<RoleRef>);
    }
}

export class RouteDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "age": string;
    "details": string;
    "hostnames"?: string[];
    "parentRefs"?: RefOrDisplay[];
    "backendRefs"?: RefOrDisplay[];
    "rules"?: RouteRuleDetails[];
    "conditions"?: ConditionState[];
    "summary": ConditionsSummary;
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };

    /** Creates a new RouteDetails instance. */
    constructor($$source: Partial<RouteDetails> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("age" in $$source)) {
            this["age"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new ConditionsSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RouteDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): RouteDetails {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType21;
        const $$createField7_0 = $$createType21;
        const $$createField8_0 = $$createType23;
        const $$createField9_0 = $$createType9;
        const $$createField10_0 = $$createType24;
        const $$createField11_0 = $$createType14;
        const $$createField12_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hostnames" in $$parsedSource) {
            $$parsedSource["hostnames"] = $$createField5_0($$parsedSource["hostnames"]);
        }
        if ("parentRefs" in $$parsedSource) {
            $$parsedSource["parentRefs"] = $$createField6_0($$parsedSource["parentRefs"]);
        }
        if ("backendRefs" in $$parsedSource) {
            $$parsedSource["backendRefs"] = $$createField7_0($$parsedSource["backendRefs"]);
        }
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField8_0($$parsedSource["rules"]);
        }
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField9_0($$parsedSource["conditions"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField10_0($$parsedSource["summary"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField11_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField12_0($$parsedSource["annotations"]);
        }
        return new RouteDetails($$parsedSource as Partial<RouteDetails>);
    }
}

export const GRPCRouteDetails = RouteDetails;
export type GRPCRouteDetails = RouteDetails;

export const HTTPRouteDetails = RouteDetails;
export type HTTPRouteDetails = RouteDetails;

export class RouteRuleDetails {
    "matches"?: string[];
    "backendRefs"?: RefOrDisplay[];

    /** Creates a new RouteRuleDetails instance. */
    constructor($$source: Partial<RouteRuleDetails> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RouteRuleDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): RouteRuleDetails {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField0_0($$parsedSource["matches"]);
        }
        if ("backendRefs" in $$parsedSource) {
            $$parsedSource["backendRefs"] = $$createField1_0($$parsedSource["backendRefs"]);
        }
        return new RouteRuleDetails($$parsedSource as Partial<RouteRuleDetails>);
    }
}

/**
 * ShellSession contains details about an active exec session.
 */
export class ShellSession {
    "sessionId": string;
    "namespace": string;
    "podName": string;
    "container": string;
    "command": string[];
    "containers": string[];

    /** Creates a new ShellSession instance. */
    constructor($$source: Partial<ShellSession> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            this["podName"] = "";
        }
        if (!("container" in $$source)) {
            this["container"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = [];
        }
        if (!("containers" in $$source)) {
            this["containers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellSession instance from a string or object.
     */
    static createFrom($$source: any = {}): ShellSession {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField4_0($$parsedSource["command"]);
        }
        if ("containers" in $$parsedSource) {
            $$parsedSource["containers"] = $$createField5_0($$parsedSource["containers"]);
        }
        return new ShellSession($$parsedSource as Partial<ShellSession>);
    }
}

/**
 * ShellSessionInfo describes a tracked shell exec session.
 */
export class ShellSessionInfo {
    "sessionId": string;
    "clusterId": string;
    "clusterName": string;
    "namespace": string;
    "podName": string;
    "container": string;
    "command": string[];
    "startedAt": v1$0.Time;

    /** Creates a new ShellSessionInfo instance. */
    constructor($$source: Partial<ShellSessionInfo> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("clusterId" in $$source)) {
            this["clusterId"] = "";
        }
        if (!("clusterName" in $$source)) {
            this["clusterName"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            this["podName"] = "";
        }
        if (!("container" in $$source)) {
            this["container"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = [];
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellSessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ShellSessionInfo {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField6_0($$parsedSource["command"]);
        }
        return new ShellSessionInfo($$parsedSource as Partial<ShellSessionInfo>);
    }
}

/**
 * ShellSessionRequest describes the namespace/pod/container to exec into.
 */
export class ShellSessionRequest {
    "namespace": string;
    "podName": string;
    "container"?: string;
    "command"?: string[];

    /** Creates a new ShellSessionRequest instance. */
    constructor($$source: Partial<ShellSessionRequest> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            this["podName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellSessionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ShellSessionRequest {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField3_0($$parsedSource["command"]);
        }
        return new ShellSessionRequest($$parsedSource as Partial<ShellSessionRequest>);
    }
}

export class Subject {
    "kind": string;
    "apiGroup"?: string;
    "name": string;
    "namespace"?: string;

    /** Creates a new Subject instance. */
    constructor($$source: Partial<Subject> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subject instance from a string or object.
     */
    static createFrom($$source: any = {}): Subject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Subject($$parsedSource as Partial<Subject>);
    }
}

export const TLSRouteDetails = RouteDetails;
export type TLSRouteDetails = RouteDetails;

/**
 * Theme represents a saved color theme with optional cluster pattern matching.
 * Themes are ordered; when matching clusters, the first match wins.
 */
export class Theme {
    /**
     * UUID
     */
    "id": string;

    /**
     * Display name, e.g. "Danger Red"
     */
    "name": string;

    /**
     * Glob pattern matched against context name, e.g. "prod*"; empty = "*" catch-all
     */
    "clusterPattern": string;

    /**
     * 0-360
     */
    "paletteHueLight": number;

    /**
     * 0-100
     */
    "paletteSaturationLight": number;

    /**
     * -50 to +50
     */
    "paletteBrightnessLight": number;

    /**
     * 0-360
     */
    "paletteHueDark": number;

    /**
     * 0-100
     */
    "paletteSaturationDark": number;

    /**
     * -50 to +50
     */
    "paletteBrightnessDark": number;

    /**
     * Hex "#rrggbb" or empty for default
     */
    "accentColorLight"?: string;

    /**
     * Hex "#rrggbb" or empty for default
     */
    "accentColorDark"?: string;

    /**
     * Hex "#rrggbb" or empty for default
     */
    "linkColorLight"?: string;

    /**
     * Hex "#rrggbb" or empty for default
     */
    "linkColorDark"?: string;

    /** Creates a new Theme instance. */
    constructor($$source: Partial<Theme> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("clusterPattern" in $$source)) {
            this["clusterPattern"] = "";
        }
        if (!("paletteHueLight" in $$source)) {
            this["paletteHueLight"] = 0;
        }
        if (!("paletteSaturationLight" in $$source)) {
            this["paletteSaturationLight"] = 0;
        }
        if (!("paletteBrightnessLight" in $$source)) {
            this["paletteBrightnessLight"] = 0;
        }
        if (!("paletteHueDark" in $$source)) {
            this["paletteHueDark"] = 0;
        }
        if (!("paletteSaturationDark" in $$source)) {
            this["paletteSaturationDark"] = 0;
        }
        if (!("paletteBrightnessDark" in $$source)) {
            this["paletteBrightnessDark"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     */
    static createFrom($$source: any = {}): Theme {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Theme($$parsedSource as Partial<Theme>);
    }
}

/**
 * ThemeClusterPatternValidationResult reports whether a saved theme cluster
 * pattern can be parsed by the app glob matcher.
 */
export class ThemeClusterPatternValidationResult {
    "valid": boolean;
    "message"?: string;

    /** Creates a new ThemeClusterPatternValidationResult instance. */
    constructor($$source: Partial<ThemeClusterPatternValidationResult> = {}) {
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeClusterPatternValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeClusterPatternValidationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeClusterPatternValidationResult($$parsedSource as Partial<ThemeClusterPatternValidationResult>);
    }
}

/**
 * UpdateAppPreferencesRequest applies one atomic batch of preference changes.
 */
export class UpdateAppPreferencesRequest {
    "changes": AppPreferenceChange[];

    /** Creates a new UpdateAppPreferencesRequest instance. */
    constructor($$source: Partial<UpdateAppPreferencesRequest> = {}) {
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateAppPreferencesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateAppPreferencesRequest {
        const $$createField0_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField0_0($$parsedSource["changes"]);
        }
        return new UpdateAppPreferencesRequest($$parsedSource as Partial<UpdateAppPreferencesRequest>);
    }
}

/**
 * UpdateAppPreferencesResponse returns the normalized settings after an update.
 */
export class UpdateAppPreferencesResponse {
    "settings": AppSettings | null;
    "changedKeys": string[];

    /** Creates a new UpdateAppPreferencesResponse instance. */
    constructor($$source: Partial<UpdateAppPreferencesResponse> = {}) {
        if (!("settings" in $$source)) {
            this["settings"] = null;
        }
        if (!("changedKeys" in $$source)) {
            this["changedKeys"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateAppPreferencesResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateAppPreferencesResponse {
        const $$createField0_0 = $$createType28;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        if ("changedKeys" in $$parsedSource) {
            $$parsedSource["changedKeys"] = $$createField1_0($$parsedSource["changedKeys"]);
        }
        return new UpdateAppPreferencesResponse($$parsedSource as Partial<UpdateAppPreferencesResponse>);
    }
}

/**
 * WindowSettings represents the window position and size
 */
export class WindowSettings {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximized": boolean;

    /** Creates a new WindowSettings instance. */
    constructor($$source: Partial<WindowSettings> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("maximized" in $$source)) {
            this["maximized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowSettings($$parsedSource as Partial<WindowSettings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Theme.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = AppPreferenceSchema.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ConditionState.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = ContainerLogsEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType5);
const $$createType10 = PodDetailInfoContainer.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = NodeLogSource.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
const $$createType15 = $Create.Map($Create.Any, $Create.Any);
const $$createType16 = resourcemodel$0.ResourceRef.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = resourcemodel$0.DisplayRef.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = RefOrDisplay.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = RouteRuleDetails.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = ConditionsSummary.createFrom;
const $$createType25 = AppPreferenceChange.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = AppSettings.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
