export const EVENT_LABELS = {
  type: 'Type',
  namespace: 'Namespace',
  source: 'Source',
  object: 'Object',
  objectType: 'Object Type',
  objectName: 'Object Name',
  subobject: 'Subobject',
  reason: 'Reason',
  message: 'Message',
  count: 'Count',
  firstSeen: 'First Seen',
  lastSeen: 'Last Seen',
  eventTime: 'Event Time',
  seriesCount: 'Series Count',
  seriesLastSeen: 'Series Last Seen',
  action: 'Action',
  reportingController: 'Controller',
  reportingInstance: 'Reporting Instance',
  relatedObject: 'Related Object',
  relatedSubobject: 'Related Subobject',
} as const;
