import type React from 'react';

import {
  CordonIcon,
  DrainIcon,
  DeleteIcon,
  ScaleIcon,
  ForceDeleteIcon,
  ExpandIcon,
  CollapseIcon,
  ExpandAllIcon,
  CollapseAllIcon,
  SortAscIcon,
  SortDescIcon,
  OpenIcon,
  RestartIcon,
  RollbackIcon,
  NamespaceIcon,
  NamespaceOpenIcon,
  SettingsIcon,
  CollapseSidebarIcon,
  ExpandSidebarIcon,
  ClusterOverviewIcon,
  ClusterResourcesIcon,
  CategoryIcon,
  CloseIcon,
  CaseSensitiveIcon,
  MetadataIcon,
  PortForwardIcon,
  ResetFiltersIcon,
  CheckIcon,
  EditIcon,
  InfoIcon,
  DiagnosticsIcon,
  DiffIcon,
  LogsIcon,
  RefreshIcon,
  ModalCloseIcon,
  IconBarSeparatorIcon,
  WarningTriangleIcon,
  WarningOutlineIcon,
  ShortcutArrowIcon,
  TabOverflowIcon,
  TooltipInfoIcon,
  StatusDotIcon,
  StopSquareIcon,
  PlusIcon,
} from './SharedIcons';
import {
  DockRightIcon,
  DockBottomIcon,
  FloatPanelIcon,
  MaximizePanelIcon,
  RestorePanelIcon,
} from './DockableIcons';
import { DropdownSelectAllIcon, DropdownSelectNoneIcon, DropdownArrowIcon } from './DropdownIcons';
import {
  FavoriteOutlineIcon,
  FavoriteFilledIcon,
  FavoriteGenericIcon,
  FavoritePinIcon,
  ChevronUpIcon,
  ChevronDownIcon,
} from './FavoriteIcons';
import {
  AutoScrollIcon,
  AutoRefreshIcon,
  PreviousLogsIcon,
  TimestampIcon,
  WrapTextIcon,
  AnsiColorIcon,
  ParseJsonIcon,
  PrettyJsonIcon,
  CopyIcon,
  HighlightSearchIcon,
  InverseSearchIcon,
  RegexSearchIcon,
} from './LogIcons';
import {
  ObjectMapIcon,
  ZoomInIcon,
  ZoomOutIcon,
  ResetZoomIcon,
  FitToViewIcon,
  AutoFitIcon,
  FocusModeIcon,
  LegendIcon,
  ObjectMapLegendSwatchIcon,
} from './ObjectMapIcons';
import {
  KubeconfigsIcon,
  DisplayIcon,
  AdvancedIcon,
  AppearanceModeIcon,
  KubeconfigFolderIcon,
} from './SettingsIcons';
import {
  YamlManagedFieldsIcon,
  YamlEditIcon,
  YamlCancelIcon,
  YamlSaveIcon,
  YamlPreviousIcon,
  YamlNextIcon,
} from './YamlIcons';
import ewResizeCursorUrl from './cursors/ew-resize.svg';
import neswResizeCursorUrl from './cursors/nesw-resize.svg';
import nsResizeCursorUrl from './cursors/ns-resize.svg';
import nwseResizeCursorUrl from './cursors/nwse-resize.svg';

export type IconDebugEntry =
  | {
      kind: 'component';
      name: string;
      file: string;
      Component: React.ElementType;
      previewProps?: Record<string, unknown>;
      usedBy: string[];
    }
  | { kind: 'asset'; name: string; file: string; src: string; usedBy: string[] };

export const iconDebugEntries: IconDebugEntry[] = [
  {
    kind: 'component',
    name: 'CordonIcon',
    file: 'SharedIcons.tsx',
    Component: CordonIcon,
    usedBy: ['shared/hooks/useObjectActions.tsx'],
  },
  {
    kind: 'component',
    name: 'DrainIcon',
    file: 'SharedIcons.tsx',
    Component: DrainIcon,
    usedBy: [
      'modules/cluster/components/ClusterViewNodes.tsx',
      'modules/object-panel/components/ObjectPanel/Details/Overview/NodeOverview.tsx',
      'shared/hooks/useObjectActions.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'DeleteIcon',
    file: 'SharedIcons.tsx',
    Component: DeleteIcon,
    usedBy: [
      'shared/hooks/useObjectActions.tsx',
      'ui/favorites/FavMenuDropdown.tsx',
      'ui/panels/app-logs/AppLogsPanel.tsx',
      'ui/settings/sections/AppearanceSection.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'ScaleIcon',
    file: 'SharedIcons.tsx',
    Component: ScaleIcon,
    usedBy: ['shared/hooks/useObjectActions.tsx'],
  },
  {
    kind: 'component',
    name: 'ForceDeleteIcon',
    file: 'SharedIcons.tsx',
    Component: ForceDeleteIcon,
    usedBy: [],
  },
  {
    kind: 'component',
    name: 'ExpandIcon',
    file: 'SharedIcons.tsx',
    Component: ExpandIcon,
    usedBy: [],
  },
  {
    kind: 'component',
    name: 'CollapseIcon',
    file: 'SharedIcons.tsx',
    Component: CollapseIcon,
    usedBy: [],
  },
  {
    kind: 'component',
    name: 'ExpandAllIcon',
    file: 'SharedIcons.tsx',
    Component: ExpandAllIcon,
    usedBy: [],
  },
  {
    kind: 'component',
    name: 'CollapseAllIcon',
    file: 'SharedIcons.tsx',
    Component: CollapseAllIcon,
    usedBy: [],
  },
  {
    kind: 'component',
    name: 'SortAscIcon',
    file: 'SharedIcons.tsx',
    Component: SortAscIcon,
    usedBy: [
      'shared/components/tables/hooks/useGridTableContextMenuItems.tsx',
      'shared/components/tables/hooks/useGridTableController.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'SortDescIcon',
    file: 'SharedIcons.tsx',
    Component: SortDescIcon,
    usedBy: [
      'shared/components/tables/hooks/useGridTableContextMenuItems.tsx',
      'shared/components/tables/hooks/useGridTableController.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'OpenIcon',
    file: 'SharedIcons.tsx',
    Component: OpenIcon,
    usedBy: ['shared/hooks/useObjectActions.tsx', 'ui/status/SessionsStatus.tsx'],
  },
  {
    kind: 'component',
    name: 'RestartIcon',
    file: 'SharedIcons.tsx',
    Component: RestartIcon,
    usedBy: ['shared/hooks/useObjectActions.tsx', 'ui/status/SessionsStatus.tsx'],
  },
  {
    kind: 'component',
    name: 'RollbackIcon',
    file: 'SharedIcons.tsx',
    Component: RollbackIcon,
    usedBy: ['shared/hooks/useObjectActions.tsx'],
  },
  {
    kind: 'component',
    name: 'NamespaceIcon',
    file: 'SharedIcons.tsx',
    Component: NamespaceIcon,
    usedBy: ['ui/layout/Sidebar.tsx'],
  },
  {
    kind: 'component',
    name: 'NamespaceOpenIcon',
    file: 'SharedIcons.tsx',
    Component: NamespaceOpenIcon,
    usedBy: ['ui/layout/Sidebar.tsx'],
  },
  {
    kind: 'component',
    name: 'SettingsIcon',
    file: 'SharedIcons.tsx',
    Component: SettingsIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'ui/command-palette/CommandPaletteCommands.tsx',
      'ui/layout/AppHeader.tsx',
      'ui/modals/SettingsModal.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'CollapseSidebarIcon',
    file: 'SharedIcons.tsx',
    Component: CollapseSidebarIcon,
    usedBy: ['ui/command-palette/CommandPaletteCommands.tsx', 'ui/layout/Sidebar.tsx'],
  },
  {
    kind: 'component',
    name: 'ExpandSidebarIcon',
    file: 'SharedIcons.tsx',
    Component: ExpandSidebarIcon,
    usedBy: ['ui/command-palette/CommandPaletteCommands.tsx', 'ui/layout/Sidebar.tsx'],
  },
  {
    kind: 'component',
    name: 'ClusterOverviewIcon',
    file: 'SharedIcons.tsx',
    Component: ClusterOverviewIcon,
    usedBy: ['ui/layout/Sidebar.tsx'],
  },
  {
    kind: 'component',
    name: 'ClusterResourcesIcon',
    file: 'SharedIcons.tsx',
    Component: ClusterResourcesIcon,
    usedBy: ['ui/layout/Sidebar.tsx'],
  },
  {
    kind: 'component',
    name: 'CategoryIcon',
    file: 'SharedIcons.tsx',
    Component: CategoryIcon,
    usedBy: ['ui/layout/Sidebar.tsx'],
  },
  {
    kind: 'component',
    name: 'CloseIcon',
    file: 'SharedIcons.tsx',
    Component: CloseIcon,
    usedBy: [
      'modules/object-map/ObjectMap.tsx',
      'modules/object-panel/components/ObjectPanel/Yaml/YamlTab.tsx',
      'ui/command-palette/CommandPaletteCommands.tsx',
      'ui/dockable/DockablePanelControls.tsx',
      'ui/dockable/DockableTabBar.tsx',
      'ui/favorites/FavSaveModal.tsx',
      'ui/layout/ClusterTabs.tsx',
      'ui/layout/DebugOverlay.tsx',
      'ui/modals/AboutModal.tsx',
      'ui/modals/ObjPanelLogsSettingsModal.tsx',
      'ui/modals/ObjectDiffModal.tsx',
      'ui/modals/SettingsModal.tsx',
      'ui/settings/sections/AppearanceSection.tsx',
      'ui/settings/sections/KubeconfigsSection.tsx',
      'ui/shortcuts/components/ShortcutHelpModal.tsx',
      'ui/status/SessionsStatus.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'CaseSensitiveIcon',
    file: 'SharedIcons.tsx',
    Component: CaseSensitiveIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'modules/object-panel/components/ObjectPanel/NodeLogs/NodeLogsTab.tsx',
      'modules/object-panel/components/ObjectPanel/Yaml/YamlTab.tsx',
      'shared/components/tables/GridTableFiltersBar.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'MetadataIcon',
    file: 'SharedIcons.tsx',
    Component: MetadataIcon,
    usedBy: ['shared/components/tables/hooks/useMetadataSearch.tsx'],
  },
  {
    kind: 'component',
    name: 'PortForwardIcon',
    file: 'SharedIcons.tsx',
    Component: PortForwardIcon,
    usedBy: ['shared/hooks/useObjectActions.tsx'],
  },
  {
    kind: 'component',
    name: 'ResetFiltersIcon',
    file: 'SharedIcons.tsx',
    Component: ResetFiltersIcon,
    usedBy: [
      'modules/object-map/ObjectMap.tsx',
      'shared/components/tables/GridTableFiltersBar.tsx',
      'ui/command-palette/CommandPaletteCommands.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'CheckIcon',
    file: 'SharedIcons.tsx',
    Component: CheckIcon,
    usedBy: ['ui/settings/sections/AppearanceSection.tsx'],
  },
  {
    kind: 'component',
    name: 'EditIcon',
    file: 'SharedIcons.tsx',
    Component: EditIcon,
    usedBy: ['ui/settings/sections/AppearanceSection.tsx'],
  },
  {
    kind: 'component',
    name: 'InfoIcon',
    file: 'SharedIcons.tsx',
    Component: InfoIcon,
    usedBy: ['ui/command-palette/CommandPaletteCommands.tsx'],
  },
  {
    kind: 'component',
    name: 'DiagnosticsIcon',
    file: 'SharedIcons.tsx',
    Component: DiagnosticsIcon,
    usedBy: ['ui/command-palette/CommandPaletteCommands.tsx'],
  },
  {
    kind: 'component',
    name: 'DiffIcon',
    file: 'SharedIcons.tsx',
    Component: DiffIcon,
    usedBy: ['shared/hooks/useObjectActions.tsx', 'ui/command-palette/CommandPaletteCommands.tsx'],
  },
  {
    kind: 'component',
    name: 'LogsIcon',
    file: 'SharedIcons.tsx',
    Component: LogsIcon,
    usedBy: ['ui/command-palette/CommandPaletteCommands.tsx'],
  },
  {
    kind: 'component',
    name: 'RefreshIcon',
    file: 'SharedIcons.tsx',
    Component: RefreshIcon,
    usedBy: ['modules/object-map/ObjectMap.tsx', 'ui/command-palette/CommandPaletteCommands.tsx'],
  },
  {
    kind: 'component',
    name: 'ModalCloseIcon',
    file: 'SharedIcons.tsx',
    Component: ModalCloseIcon,
    usedBy: [
      'modules/port-forward/PortForwardModal.tsx',
      'shared/components/modals/RollbackModal.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'IconBarSeparatorIcon',
    file: 'SharedIcons.tsx',
    Component: IconBarSeparatorIcon,
    usedBy: ['shared/components/IconBar/IconBar.tsx'],
  },
  {
    kind: 'component',
    name: 'WarningTriangleIcon',
    file: 'SharedIcons.tsx',
    Component: WarningTriangleIcon,
    usedBy: ['modules/namespace/components/NsViewPods.tsx'],
  },
  {
    kind: 'component',
    name: 'WarningOutlineIcon',
    file: 'SharedIcons.tsx',
    Component: WarningOutlineIcon,
    usedBy: ['modules/object-panel/components/ObjectPanel/Details/DetailsTab.tsx'],
  },
  {
    kind: 'component',
    name: 'ShortcutArrowIcon',
    file: 'SharedIcons.tsx',
    Component: ShortcutArrowIcon,
    previewProps: { direction: 'right' },
    usedBy: ['ui/shortcuts/components/ShortcutHelpModal.tsx'],
  },
  {
    kind: 'component',
    name: 'TabOverflowIcon',
    file: 'SharedIcons.tsx',
    Component: TabOverflowIcon,
    previewProps: { direction: 'right' },
    usedBy: ['shared/components/tabs/Tabs.tsx'],
  },
  {
    kind: 'component',
    name: 'TooltipInfoIcon',
    file: 'SharedIcons.tsx',
    Component: TooltipInfoIcon,
    usedBy: ['shared/components/Tooltip.tsx'],
  },
  {
    kind: 'component',
    name: 'StatusDotIcon',
    file: 'SharedIcons.tsx',
    Component: StatusDotIcon,
    previewProps: { outlined: true },
    usedBy: ['ui/status/SessionsStatus.tsx'],
  },
  {
    kind: 'component',
    name: 'StopSquareIcon',
    file: 'SharedIcons.tsx',
    Component: StopSquareIcon,
    usedBy: ['ui/status/SessionsStatus.tsx'],
  },
  {
    kind: 'component',
    name: 'PlusIcon',
    file: 'SharedIcons.tsx',
    Component: PlusIcon,
    usedBy: ['ui/settings/sections/KubeconfigsSection.tsx'],
  },
  {
    kind: 'component',
    name: 'DockRightIcon',
    file: 'DockableIcons.tsx',
    Component: DockRightIcon,
    usedBy: ['ui/dockable/DockablePanelControls.tsx'],
  },
  {
    kind: 'component',
    name: 'DockBottomIcon',
    file: 'DockableIcons.tsx',
    Component: DockBottomIcon,
    usedBy: ['ui/dockable/DockablePanelControls.tsx'],
  },
  {
    kind: 'component',
    name: 'FloatPanelIcon',
    file: 'DockableIcons.tsx',
    Component: FloatPanelIcon,
    usedBy: ['ui/dockable/DockablePanelControls.tsx', 'ui/modals/SettingsModal.tsx'],
  },
  {
    kind: 'component',
    name: 'MaximizePanelIcon',
    file: 'DockableIcons.tsx',
    Component: MaximizePanelIcon,
    usedBy: ['ui/dockable/DockablePanelControls.tsx'],
  },
  {
    kind: 'component',
    name: 'RestorePanelIcon',
    file: 'DockableIcons.tsx',
    Component: RestorePanelIcon,
    usedBy: ['ui/dockable/DockablePanelControls.tsx'],
  },
  {
    kind: 'component',
    name: 'DropdownSelectAllIcon',
    file: 'DropdownIcons.tsx',
    Component: DropdownSelectAllIcon,
    usedBy: ['shared/components/dropdowns/Dropdown/Dropdown.tsx'],
  },
  {
    kind: 'component',
    name: 'DropdownSelectNoneIcon',
    file: 'DropdownIcons.tsx',
    Component: DropdownSelectNoneIcon,
    usedBy: ['shared/components/dropdowns/Dropdown/Dropdown.tsx'],
  },
  {
    kind: 'component',
    name: 'DropdownArrowIcon',
    file: 'DropdownIcons.tsx',
    Component: DropdownArrowIcon,
    usedBy: ['shared/components/dropdowns/Dropdown/Dropdown.tsx'],
  },
  {
    kind: 'component',
    name: 'FavoriteOutlineIcon',
    file: 'FavoriteIcons.tsx',
    Component: FavoriteOutlineIcon,
    usedBy: ['ui/favorites/FavToggle.tsx'],
  },
  {
    kind: 'component',
    name: 'FavoriteFilledIcon',
    file: 'FavoriteIcons.tsx',
    Component: FavoriteFilledIcon,
    usedBy: ['ui/favorites/FavMenuDropdown.tsx', 'ui/favorites/FavToggle.tsx'],
  },
  {
    kind: 'component',
    name: 'FavoriteGenericIcon',
    file: 'FavoriteIcons.tsx',
    Component: FavoriteGenericIcon,
    usedBy: ['ui/command-palette/CommandPaletteCommands.tsx', 'ui/favorites/FavMenuDropdown.tsx'],
  },
  {
    kind: 'component',
    name: 'FavoritePinIcon',
    file: 'FavoriteIcons.tsx',
    Component: FavoritePinIcon,
    usedBy: ['ui/command-palette/CommandPaletteCommands.tsx', 'ui/favorites/FavMenuDropdown.tsx'],
  },
  {
    kind: 'component',
    name: 'ChevronUpIcon',
    file: 'FavoriteIcons.tsx',
    Component: ChevronUpIcon,
    usedBy: ['ui/favorites/FavMenuDropdown.tsx'],
  },
  {
    kind: 'component',
    name: 'ChevronDownIcon',
    file: 'FavoriteIcons.tsx',
    Component: ChevronDownIcon,
    usedBy: ['ui/favorites/FavMenuDropdown.tsx'],
  },
  {
    kind: 'component',
    name: 'AutoScrollIcon',
    file: 'LogIcons.tsx',
    Component: AutoScrollIcon,
    usedBy: ['ui/panels/app-logs/AppLogsPanel.tsx'],
  },
  {
    kind: 'component',
    name: 'AutoRefreshIcon',
    file: 'LogIcons.tsx',
    Component: AutoRefreshIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'modules/object-panel/components/ObjectPanel/NodeLogs/NodeLogsTab.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'PreviousLogsIcon',
    file: 'LogIcons.tsx',
    Component: PreviousLogsIcon,
    usedBy: ['modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx'],
  },
  {
    kind: 'component',
    name: 'TimestampIcon',
    file: 'LogIcons.tsx',
    Component: TimestampIcon,
    usedBy: ['modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx'],
  },
  {
    kind: 'component',
    name: 'WrapTextIcon',
    file: 'LogIcons.tsx',
    Component: WrapTextIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'modules/object-panel/components/ObjectPanel/NodeLogs/NodeLogsTab.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'AnsiColorIcon',
    file: 'LogIcons.tsx',
    Component: AnsiColorIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'modules/object-panel/components/ObjectPanel/NodeLogs/NodeLogsTab.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'ParseJsonIcon',
    file: 'LogIcons.tsx',
    Component: ParseJsonIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'modules/object-panel/components/ObjectPanel/NodeLogs/NodeLogsTab.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'PrettyJsonIcon',
    file: 'LogIcons.tsx',
    Component: PrettyJsonIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'modules/object-panel/components/ObjectPanel/NodeLogs/NodeLogsTab.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'CopyIcon',
    file: 'LogIcons.tsx',
    Component: CopyIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'modules/object-panel/components/ObjectPanel/NodeLogs/NodeLogsTab.tsx',
      'shared/components/tables/hooks/useGridTableFiltersWiring.tsx',
      'ui/layout/AppLayout.tsx',
      'ui/panels/app-logs/AppLogsPanel.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'HighlightSearchIcon',
    file: 'LogIcons.tsx',
    Component: HighlightSearchIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'modules/object-panel/components/ObjectPanel/NodeLogs/NodeLogsTab.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'InverseSearchIcon',
    file: 'LogIcons.tsx',
    Component: InverseSearchIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'modules/object-panel/components/ObjectPanel/NodeLogs/NodeLogsTab.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'RegexSearchIcon',
    file: 'LogIcons.tsx',
    Component: RegexSearchIcon,
    usedBy: [
      'modules/object-panel/components/ObjectPanel/Logs/LogViewer.tsx',
      'modules/object-panel/components/ObjectPanel/NodeLogs/NodeLogsTab.tsx',
      'modules/object-panel/components/ObjectPanel/Yaml/YamlTab.tsx',
    ],
  },
  {
    kind: 'component',
    name: 'ObjectMapIcon',
    file: 'ObjectMapIcons.tsx',
    Component: ObjectMapIcon,
    usedBy: ['shared/hooks/useObjectActions.tsx'],
  },
  {
    kind: 'component',
    name: 'ZoomInIcon',
    file: 'ObjectMapIcons.tsx',
    Component: ZoomInIcon,
    usedBy: ['modules/object-map/ObjectMap.tsx'],
  },
  {
    kind: 'component',
    name: 'ZoomOutIcon',
    file: 'ObjectMapIcons.tsx',
    Component: ZoomOutIcon,
    usedBy: ['modules/object-map/ObjectMap.tsx'],
  },
  {
    kind: 'component',
    name: 'ResetZoomIcon',
    file: 'ObjectMapIcons.tsx',
    Component: ResetZoomIcon,
    usedBy: ['modules/object-map/ObjectMap.tsx'],
  },
  {
    kind: 'component',
    name: 'FitToViewIcon',
    file: 'ObjectMapIcons.tsx',
    Component: FitToViewIcon,
    usedBy: ['modules/object-map/ObjectMap.tsx'],
  },
  {
    kind: 'component',
    name: 'AutoFitIcon',
    file: 'ObjectMapIcons.tsx',
    Component: AutoFitIcon,
    usedBy: ['modules/object-map/ObjectMap.tsx'],
  },
  {
    kind: 'component',
    name: 'FocusModeIcon',
    file: 'ObjectMapIcons.tsx',
    Component: FocusModeIcon,
    usedBy: ['modules/object-map/ObjectMap.tsx'],
  },
  {
    kind: 'component',
    name: 'LegendIcon',
    file: 'ObjectMapIcons.tsx',
    Component: LegendIcon,
    usedBy: ['modules/object-map/ObjectMap.tsx'],
  },
  {
    kind: 'component',
    name: 'ObjectMapLegendSwatchIcon',
    file: 'ObjectMapIcons.tsx',
    Component: ObjectMapLegendSwatchIcon,
    previewProps: { edgeClassName: 'icon-debug__legend-edge' },
    usedBy: ['modules/object-map/ObjectMap.tsx'],
  },
  {
    kind: 'component',
    name: 'KubeconfigsIcon',
    file: 'SettingsIcons.tsx',
    Component: KubeconfigsIcon,
    usedBy: ['ui/modals/SettingsModal.tsx'],
  },
  {
    kind: 'component',
    name: 'DisplayIcon',
    file: 'SettingsIcons.tsx',
    Component: DisplayIcon,
    usedBy: ['ui/modals/SettingsModal.tsx'],
  },
  {
    kind: 'component',
    name: 'AdvancedIcon',
    file: 'SettingsIcons.tsx',
    Component: AdvancedIcon,
    usedBy: ['ui/modals/SettingsModal.tsx'],
  },
  {
    kind: 'component',
    name: 'AppearanceModeIcon',
    file: 'SettingsIcons.tsx',
    Component: AppearanceModeIcon,
    usedBy: ['ui/command-palette/CommandPaletteCommands.tsx', 'ui/modals/SettingsModal.tsx'],
  },
  {
    kind: 'component',
    name: 'KubeconfigFolderIcon',
    file: 'SettingsIcons.tsx',
    Component: KubeconfigFolderIcon,
    usedBy: ['ui/settings/sections/KubeconfigsSection.tsx'],
  },
  {
    kind: 'component',
    name: 'YamlManagedFieldsIcon',
    file: 'YamlIcons.tsx',
    Component: YamlManagedFieldsIcon,
    usedBy: ['modules/object-panel/components/ObjectPanel/Yaml/YamlTab.tsx'],
  },
  {
    kind: 'component',
    name: 'YamlEditIcon',
    file: 'YamlIcons.tsx',
    Component: YamlEditIcon,
    usedBy: ['modules/object-panel/components/ObjectPanel/Yaml/YamlTab.tsx'],
  },
  {
    kind: 'component',
    name: 'YamlCancelIcon',
    file: 'YamlIcons.tsx',
    Component: YamlCancelIcon,
    usedBy: ['modules/object-panel/components/ObjectPanel/Yaml/YamlTab.tsx'],
  },
  {
    kind: 'component',
    name: 'YamlSaveIcon',
    file: 'YamlIcons.tsx',
    Component: YamlSaveIcon,
    usedBy: ['modules/object-panel/components/ObjectPanel/Yaml/YamlTab.tsx'],
  },
  {
    kind: 'component',
    name: 'YamlPreviousIcon',
    file: 'YamlIcons.tsx',
    Component: YamlPreviousIcon,
    usedBy: ['modules/object-panel/components/ObjectPanel/Yaml/YamlTab.tsx'],
  },
  {
    kind: 'component',
    name: 'YamlNextIcon',
    file: 'YamlIcons.tsx',
    Component: YamlNextIcon,
    usedBy: ['modules/object-panel/components/ObjectPanel/Yaml/YamlTab.tsx'],
  },
  {
    kind: 'asset',
    name: 'ew-resize',
    file: 'cursors/ew-resize.svg',
    src: ewResizeCursorUrl,
    usedBy: ['ui/dockable/DockablePanel.css', 'ui/layout/Sidebar.css'],
  },
  {
    kind: 'asset',
    name: 'nesw-resize',
    file: 'cursors/nesw-resize.svg',
    src: neswResizeCursorUrl,
    usedBy: ['ui/dockable/DockablePanel.css'],
  },
  {
    kind: 'asset',
    name: 'ns-resize',
    file: 'cursors/ns-resize.svg',
    src: nsResizeCursorUrl,
    usedBy: ['ui/dockable/DockablePanel.css'],
  },
  {
    kind: 'asset',
    name: 'nwse-resize',
    file: 'cursors/nwse-resize.svg',
    src: nwseResizeCursorUrl,
    usedBy: ['ui/dockable/DockablePanel.css', 'ui/layout/DebugOverlay.css'],
  },
];
