// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resourcemodel$0 from "../../resourcemodel/models.js";

/**
 * KarpenterSummary contains only the facts shown in the Karpenter table.
 * Capacity and limits supply NodePool usage; scheduling and provider configuration
 * belong to the rich detail DTO.
 */
export interface KarpenterSummary {
    "nodePool"?: resourcemodel$0.ResourceLink | null;
    "nodeClass"?: resourcemodel$0.ResourceLink | null;
    "instanceType"?: string;
    "capacityType"?: string;
    "capacity"?: { [_ in string]?: string } | null;
    "limits"?: { [_ in string]?: string } | null;
}
