// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resourcemodel$0 from "../../resourcemodel/models.js";

/**
 * ArgoCDSummary holds the focused fields used by the Argo CD table.
 */
export interface ArgoCDSummary {
    "health"?: string;
    "healthPresentation"?: string;
    "sync"?: string;
    "syncPresentation"?: string;
    "project"?: string;
    "destination"?: string;
    "destinationNamespace"?: string;
}

export interface CertManagerSummary {
    "issuerType"?: string;
    "server"?: string;
    "issuer"?: resourcemodel$0.ResourceLink | null;
    "secret"?: resourcemodel$0.ResourceLink | null;
    "notAfter"?: string;
}

export interface ExternalSecretsSummary {
    "provider"?: string;
    "storeName"?: string;
    "store"?: resourcemodel$0.ResourceLink | null;
    "target"?: resourcemodel$0.ResourceLink | null;
    "targetName"?: string;
    "refreshInterval"?: string;
}

/**
 * KarpenterSummary contains only the facts shown in the Karpenter table. LimitUsage
 * supplies NodePool usage, computed by the Karpenter facts; scheduling and provider
 * configuration belong to the rich detail DTO.
 */
export interface KarpenterSummary {
    "nodePool"?: resourcemodel$0.ResourceLink | null;
    "nodeClass"?: resourcemodel$0.ResourceLink | null;
    "instanceType"?: string;
    "capacityType"?: string;
    "limitUsage"?: { [_ in string]?: resourcemodel$0.LimitUsage } | null;
}

export interface PrometheusSummary {
    "endpoints"?: number | null;
    "rules"?: number | null;
    "version"?: string;
    "replicas"?: number | null;
    "availableReplicas"?: number | null;
}
