// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum Distribution {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DistributionMacBundle = "mac-bundle",
    DistributionWindowsNSIS = "windows-nsis",
    DistributionLinuxPortable = "linux-portable",
    DistributionLinuxDEB = "linux-deb",
    DistributionLinuxRPM = "linux-rpm",
    DistributionLinuxAppImage = "linux-appimage",
};

export enum EligibilityReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ReasonMacNotInstalledBundle = "mac-not-installed-bundle",
    ReasonMacReadOnly = "mac-read-only",
    ReasonMacUnwritableParent = "mac-unwritable-parent",
    ReasonManagedInstallation = "managed-installation",
    ReasonWindowsUnverifiedInstall = "windows-unverified-install",
    ReasonLinuxPackageManaged = "linux-package-managed",
    ReasonLinuxPortableIneligible = "linux-portable-ineligible",
    ReasonLinuxAppImageIneligible = "linux-appimage-ineligible",
    ReasonUnsupportedDistribution = "unsupported-distribution",
};

export enum RecoveryTarget {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RecoveryMacDownload = "mac-download",
    RecoveryWindowsDownload = "windows-download",
    RecoveryLinuxPackages = "linux-packages",
    RecoveryLinuxPortableDownload = "linux-portable-download",
    RecoveryLinuxAppImageDownload = "linux-appimage-download",
    RecoveryDownloadOptions = "download-options",
};
