// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    NativeRole,
    TabKind,
    TabTransferTarget,
    WindowState
} from "./models.js";

export type {
    ApplicationQuitPreflightRequestedEvent,
    GroupSnapshot,
    NativeDescriptor,
    ObjectOpenAuthorizedEvent,
    ObjectOpenRequestEvent,
    ObjectReference,
    OwnerCloseRequestedEvent,
    SnapshotUpdatedEvent,
    TabCloseAuthorizedEvent,
    TabCloseRequestedEvent,
    TabSnapshot,
    TabTransferCommittedEvent,
    TabTransferFailedEvent,
    TabTransferInsertRequestedEvent,
    TabTransferRequest,
    TabTransferRequestedEvent,
    WindowBounds,
    WindowCloseRequestedEvent,
    WindowClosedEvent,
    WindowDescriptor,
    WindowDockRequestedEvent,
    WindowFocusRequestedEvent,
    WindowGuardRequestedEvent,
    WindowGuardResultEvent,
    WindowOpenedEvent,
    WindowPoint,
    WorkspaceDescriptor
} from "./models.js";
