// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ApplicationQuitPreflightRequestedEvent {
    "transactionId": string;
    "windowName": string;
}

export interface ClusterPanelCloseEvent {
    "transactionId": string;
    "windowName": string;
    "clusterId": string;
}

export interface ClusterTabTransferEvent {
    "request": ClusterTabTransferRequest;
    "snapshot": ClusterViewSnapshot;
    "targetAlreadyOpen": boolean;
}

export interface ClusterTabTransferRequest {
    "transferId": string;
    "sourceWindowName": string;
    "targetWindowName": string;
    "clusterId": string;
    "targetIndex": number;
    "dropPosition"?: WindowPoint | null;
}

export interface ClusterViewSnapshot {
    "schemaVersion": number;
    "viewState": string;
    "groups": WorkspaceGroup[] | null;
}

export interface GroupSnapshot {
    "schemaVersion": number;
    "transferId": string;
    "sourceWindowName": string;
    "clusterId": string;
    "groupId": string;
    "tabs": TabSnapshot[] | null;
    "activePanelId": string;
    "initialBounds"?: WindowBounds | null;
    "initialPositionAnchor"?: WindowPoint | null;
    "useInitialPosition"?: boolean;
}

export interface NativeDescriptor {
    "schemaVersion": number;
    "role": NativeRole;
    "workspace"?: WorkspaceDescriptor | null;
    "panel"?: WindowDescriptor | null;
}

export enum NativeRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NativeRoleWorkspace = "workspace",
    NativeRolePanel = "panel",
};

/**
 * ObjectReference is the complete object identity allowed across a native
 * panel-window boundary. Group and namespace are present but may be empty for
 * core API groups and cluster-scoped objects.
 */
export interface ObjectReference {
    "clusterId": string;
    "group": string;
    "version": string;
    "kind": string;
    "namespace": string;
    "name": string;
}

/**
 * Location is presentation state. The object's cluster identity owns the panel.
 */
export interface PanelLocation {
    "kind": PanelLocationKind;
    "windowName": string;
    "groupId": string;
    "index": number;
    "active": boolean;
}

export enum PanelLocationKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PanelLocationDocked = "docked",
    PanelLocationWindow = "panel-window",
    PanelLocationRetained = "retained",
};

export interface PanelOpenResult {
    "panel": WorkspacePanel;
    "render": boolean;
}

export interface TabCloseAuthorizedEvent {
    "panelId": string;
}

export enum TabKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TabKindObject = "object",
};

export interface TabSnapshot {
    "kind": TabKind;
    "panelId": string;
    "objectRef": ObjectReference;
    "activeView": string;
}

export interface TabTransferCommittedEvent {
    "request": TabTransferRequest;
}

export interface TabTransferFailedEvent {
    "request": TabTransferRequest;
    "reason": string;
}

export interface TabTransferInsertRequestedEvent {
    "request": TabTransferRequest;
}

export interface TabTransferRequest {
    "transferId": string;
    "sourceWindowName": string;
    "targetWindowName": string;
    "clusterId": string;
    "sourceGroupId": string;
    "targetGroupId": string;
    "targetIndex": number;
    "targetKind": TabTransferTarget;
    "cursorX": number;
    "cursorY": number;
    "tab": TabSnapshot;
}

export interface TabTransferRequestedEvent {
    "request": TabTransferRequest;
}

export enum TabTransferTarget {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TabTransferTargetWorkspace = "workspace",
    TabTransferTargetPanelWindow = "panel-window",
    TabTransferTargetNewWindow = "new-window",
};

export interface WindowBounds {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

export interface WindowCloseRequestedEvent {
    "windowName": string;
    "reason": string;
}

export interface WindowClosedEvent {
    "windowName": string;
    "clusterId": string;
    "groupId": string;
}

export interface WindowDescriptor {
    "windowName": string;
    "clusterId": string;
    "groupId": string;
    "state": WindowState;
    "snapshot": GroupSnapshot;
}

export interface WindowDockRequestedEvent {
    "windowName": string;
    "transferId": string;
    "targetPosition": string;
    "snapshot": GroupSnapshot;
}

export interface WindowFocusRequestedEvent {
    "panelId": string;
}

export interface WindowOpenedEvent {
    "windowName": string;
    "transferId": string;
    "clusterId": string;
    "groupId": string;
    "snapshot": GroupSnapshot;
}

export interface WindowPoint {
    "x": number;
    "y": number;
}

export enum WindowState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WindowStateMissing = "missing",
    WindowStateOpening = "opening",
    WindowStateLive = "live",
    WindowStateDocking = "docking",
};

export interface WindowTransferFailedEvent {
    "windowName": string;
    "transferId": string;
    "clusterId": string;
}

export interface WorkspaceChangedEvent {
    "clusterId": string;
}

export interface WorkspaceCloseRequestedEvent {
    "windowName": string;
}

export interface WorkspaceDescriptor {
    "windowName": string;
}

export interface WorkspaceFocusRequestedEvent {
    "clusterId": string;
    "panelId": string;
}

export interface WorkspaceGroup {
    "clusterId": string;
    "groupId": string;
    "tabs": TabSnapshot[] | null;
    "activePanelId": string;
}

export interface WorkspacePanel {
    "tab": TabSnapshot;
    "location": PanelLocation;
}

export interface WorkspaceSnapshot {
    "revision": number;
    "panels": WorkspacePanel[] | null;
}
