// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ApplicationQuitPreflightRequestedEvent {
    "transactionId": string;
    "ownerWindowName": string;
    "panelWindows": string[] | null;
}

export interface GroupSnapshot {
    "schemaVersion": number;
    "transferId": string;
    "ownerWindowName": string;
    "clusterId": string;
    "groupId": string;
    "tabs": TabSnapshot[] | null;
    "activePanelId": string;
    "initialBounds"?: WindowBounds | null;
}

export interface NativeDescriptor {
    "schemaVersion": number;
    "role": NativeRole;
    "workspace"?: WorkspaceDescriptor | null;
    "panel"?: WindowDescriptor | null;
}

export enum NativeRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NativeRoleWorkspace = "workspace",
    NativeRolePanel = "panel",
};

export interface ObjectOpenAuthorizedEvent {
    "panelId": string;
    "objectRef": ObjectReference;
    "activeView": string;
}

export interface ObjectOpenRequestEvent {
    "sourceWindowName": string;
    "ownerWindowName": string;
    "clusterId": string;
    "groupId": string;
    "objectRef": ObjectReference;
    "activeView": string;
}

/**
 * ObjectReference is the complete object identity allowed across a native
 * panel-window boundary. Group and namespace are present but may be empty for
 * core API groups and cluster-scoped objects.
 */
export interface ObjectReference {
    "clusterId": string;
    "group": string;
    "version": string;
    "kind": string;
    "namespace": string;
    "name": string;
}

export interface OwnerCloseRequestedEvent {
    "ownerWindowName": string;
    "panelWindows": string[] | null;
}

export interface SnapshotUpdatedEvent {
    "windowName": string;
    "snapshot": GroupSnapshot;
}

export interface TabCloseAuthorizedEvent {
    "panelId": string;
}

export interface TabCloseRequestedEvent {
    "sourceWindowName": string;
    "ownerWindowName": string;
    "clusterId": string;
    "groupId": string;
    "panelId": string;
}

export enum TabKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TabKindObject = "object",
};

export interface TabSnapshot {
    "kind": TabKind;
    "panelId": string;
    "objectRef": ObjectReference;
    "activeView": string;
}

export interface WindowBounds {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
}

export interface WindowCloseRequestedEvent {
    "windowName": string;
    "reason": string;
}

export interface WindowClosedEvent {
    "windowName": string;
    "clusterId": string;
    "groupId": string;
}

export interface WindowDescriptor {
    "windowName": string;
    "ownerWindowName": string;
    "clusterId": string;
    "groupId": string;
    "state": WindowState;
    "snapshot": GroupSnapshot;
}

export interface WindowDockRequestedEvent {
    "windowName": string;
    "transferId": string;
    "targetPosition": string;
    "snapshot": GroupSnapshot;
}

export interface WindowFocusRequestedEvent {
    "panelId": string;
}

export interface WindowGuardRequestedEvent {
    "requestId": string;
    "windowName": string;
    "reason": string;
}

export interface WindowGuardResultEvent {
    "requestId": string;
    "windowName": string;
    "allowed": boolean;
}

export interface WindowOpenedEvent {
    "windowName": string;
    "transferId": string;
    "clusterId": string;
    "groupId": string;
    "snapshot": GroupSnapshot;
}

export enum WindowState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    WindowStateMissing = "missing",
    WindowStateOpening = "opening",
    WindowStateLive = "live",
    WindowStateDocking = "docking",
};

export interface WorkspaceDescriptor {
    "windowName": string;
}
