// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as v1$0 from "../../../../../k8s.io/apimachinery/pkg/apis/meta/v1/models.js";

export interface ConditionFacts {
    "type": string;
    "status": string;
    "reason"?: string;
    "message"?: string;
    "lastTransitionTime"?: v1$0.Time;
}

/**
 * DetailSegment is one labeled fragment of a table row's Details cells.
 */
export interface DetailSegment {
    /**
     * Slot names the semantic column this segment belongs to (DetailSlot*).
     */
    "slot"?: string;

    /**
     * Label names the segment (e.g. "Rules", "Ready"); empty when the slot's
     * column header already carries the meaning.
     */
    "label"?: string;

    /**
     * Value is the segment's display text. Collapsed lists display
     * "first +N" with the full list carried in Search.
     */
    "value": string;

    /**
     * Search, when set, is the full text behind a collapsed Value; search and
     * tooltips use it so collapsing never hides matches.
     */
    "search"?: string;

    /**
     * Link, when set, marks the value as an openable cross-object reference.
     */
    "link"?: ResourceLink | null;

    /**
     * Presentation is an optional status-presentation token (e.g. "warning")
     * the frontend maps to CSS at the edge; empty renders as plain text.
     */
    "presentation"?: string;
}

export interface DisplayRef {
    "clusterId": string;
    "group"?: string;
    "version"?: string;
    "kind": string;
    "resource"?: string;
    "namespace"?: string;
    "name"?: string;
    "uid"?: string;
}

export interface ResourceLink {
    "ref"?: ResourceRef | null;
    "display"?: DisplayRef | null;
}

export interface ResourceRef {
    "clusterId": string;
    "group": string;
    "version": string;
    "kind": string;
    "resource"?: string;
    "namespace"?: string;
    "name"?: string;
    "uid"?: string;
}

/**
 * ResourceTableMetadata is the exact label/annotation projection carried by
 * resource inventory rows. It intentionally excludes detail-only metadata so
 * table pages do not serialize empty timestamps, versions, or finalizers.
 */
export interface ResourceTableMetadata {
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
}
