// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export interface ServiceAccountDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "secrets"?: types$0.ObjectRef[] | null;
    "imagePullSecrets"?: types$0.ObjectRef[] | null;
    "automountServiceAccountToken"?: boolean | null;
    "labels"?: { [_ in string]?: string } | null;
    "annotations"?: { [_ in string]?: string } | null;
    "usedByPods"?: types$0.ObjectRef[] | null;
    "roleBindings"?: types$0.ObjectRef[] | null;
    "clusterRoleBindings"?: types$0.ObjectRef[] | null;
}
