// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * BackendTLSPolicyDetails is the detail payload for a BackendTLSPolicy.
 */
export class BackendTLSPolicyDetails {
    "kind": string;
    "name": string;
    "namespace": string;
    "details": string;
    "targetRefs"?: types$0.RefOrDisplay[];
    "conditions"?: types$0.ConditionState[];
    "summary": types$0.ConditionsSummary;
    "labels"?: { [_ in string]?: string };
    "annotations"?: { [_ in string]?: string };

    /** Creates a new BackendTLSPolicyDetails instance. */
    constructor($$source: Partial<BackendTLSPolicyDetails> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = (new types$0.ConditionsSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackendTLSPolicyDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): BackendTLSPolicyDetails {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType5;
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targetRefs" in $$parsedSource) {
            $$parsedSource["targetRefs"] = $$createField4_0($$parsedSource["targetRefs"]);
        }
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField5_0($$parsedSource["conditions"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField6_0($$parsedSource["summary"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField7_0($$parsedSource["labels"]);
        }
        if ("annotations" in $$parsedSource) {
            $$parsedSource["annotations"] = $$createField8_0($$parsedSource["annotations"]);
        }
        return new BackendTLSPolicyDetails($$parsedSource as Partial<BackendTLSPolicyDetails>);
    }
}

// Private type creation functions
const $$createType0 = types$0.RefOrDisplay.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = types$0.ConditionState.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = types$0.ConditionsSummary.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
