// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IssueState says why a container's logs could not be read.
 */
export enum IssueState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * IssueUnavailable means the container has no readable log: it has not
     * started, has no previous instance, or its pod is gone.
     */
    IssueUnavailable = "unavailable",

    /**
     * IssueForbidden means the user may not read the container's log.
     */
    IssueForbidden = "forbidden",

    /**
     * IssueFailed means reading the log failed.
     */
    IssueFailed = "failed",
};

/**
 * TargetIssue describes one container whose logs could not be read.
 */
export interface TargetIssue {
    "pod": string;
    "container": string;
    "isInit"?: boolean;
    "isEphemeral"?: boolean;
    "state": IssueState;
    "reason": string;
}
